const API='';
const learnerId=localStorage.getItem('pc_learner_id')||crypto.randomUUID();
localStorage.setItem('pc_learner_id',learnerId);
const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
let modules=[];let currentQuestions=[];let currentAnswers={};let flashcards=[];let flashIndex=0;let flashShow=false;
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
async function api(path,opts={}){const res=await fetch(API+path,{headers:{'Content-Type':'application/json'},...opts});if(!res.ok)throw new Error(await res.text());return res.json()}
function escapeHtml(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function load(){modules=await api('/api/modules');route('dashboard')}
async function route(name,arg){try{if(name==='dashboard')return dashboard();if(name==='modules')return showModules();if(name==='module')return showModule(arg);if(name==='lesson')return showLesson(arg);if(name==='quiz')return quiz(arg);if(name==='flashcards')return showFlashcards();if(name==='coach')return coach()}catch(e){app.innerHTML='<div class="card"><h2>Something went wrong</h2><p>'+escapeHtml(e.message)+'</p></div>'}}
async function dashboard(){const p=await api('/api/progress?learner_id='+encodeURIComponent(learnerId));const plan=await api('/api/study-plan?learner_id='+encodeURIComponent(learnerId));app.innerHTML=`<section class="hero"><div class="card"><div class="eyebrow">General P&C licensing prep</div><h1>Study smarter. Pass with confidence.</h1><p class="muted">Server-based version with API lessons, quizzes, progress tracking, flashcards, mistake review, and Coverage Coach.</p><div class="toolbar"><button class="primary" onclick="route('modules')">Start Studying</button><button onclick="route('quiz')">Take Quiz</button><button onclick="route('coach')">Ask Coach</button></div></div><div class="card"><div class="eyebrow">Exam readiness</div><div class="stat">${plan.readiness_score}%</div><div class="progress"><div class="bar" style="width:${p.percent_complete}%"></div></div><p>${p.completed_lessons}/${p.total_lessons} lessons complete</p><p class="muted">Mistakes saved: ${p.mistake_count}. Average confidence: ${p.average_confidence}.</p></div></section><div class="grid" style="margin-top:1rem"><div class="card"><h2>Recommended next</h2><div class="list">${plan.recommended_lessons.map(x=>`<div class="row"><div><strong>${escapeHtml(x.lesson)}</strong><br><span class="muted">${escapeHtml(x.module)}</span></div><button onclick="route('lesson','${x.lesson_id}')">Open</button></div>`).join('')||'<p>Great work. Review mistakes or take a final quiz.</p>'}</div></div><div class="card"><h2>Quick tools</h2><div class="toolbar"><button onclick="route('flashcards')">Flashcards</button><button onclick="route('quiz')">Question Drill</button><button onclick="route('coach')">Coverage Coach</button></div><p class="muted">Tip: mark each lesson complete and set your confidence score after studying.</p></div></div>`}
async function showModules(){app.innerHTML=`<div class="card"><h1>Modules</h1><p class="muted">No state-specific content. This is the general P&C foundation.</p><div class="grid">${modules.map(m=>`<div class="card"><div class="eyebrow">${m.lesson_count} lessons</div><h2>${escapeHtml(m.title)}</h2><button onclick="route('module','${m.id}')">Open Module</button><button onclick="route('quiz','${m.id}')">Quiz This Module</button></div>`).join('')}</div></div>`}
async function showModule(id){const m=await api('/api/modules/'+id);app.innerHTML=`<div class="card"><button onclick="route('modules')">← Modules</button><h1>${escapeHtml(m.title)}</h1><div class="list">${m.lessons.map(l=>`<div class="row"><div><strong>${escapeHtml(l.title)}</strong><br><span class="muted">${escapeHtml(l.terms.slice(0,4).join(', '))}</span></div><button onclick="route('lesson','${l.id}')">Study</button></div>`).join('')}</div><div class="toolbar"><button onclick="route('quiz','${m.id}')">Module Quiz</button></div></div>`}
async function showLesson(id){const l=await api('/api/lessons/'+id);app.innerHTML=`<article class="lesson card"><button onclick="route('module','${l.module_id}')">← ${escapeHtml(l.module_title)}</button><h1>${escapeHtml(l.title)}</h1><p>${escapeHtml(l.body)}</p><h3>Key terms</h3><p>${l.terms.map(t=>`<span class="term">${escapeHtml(t)}</span>`).join('')}</p><label>Confidence</label><select id="confidence"><option value="1">Need review</option><option value="2">Getting it</option><option value="3">Strong</option></select><label>Notes</label><textarea id="note" rows="5" placeholder="Add your study notes..."></textarea><div class="toolbar"><button class="primary" onclick="saveLesson('${l.id}')">Mark Complete</button><button onclick="speakLesson()">Listen</button></div></article>`}
async function saveLesson(id){await api('/api/progress',{method:'POST',body:JSON.stringify({learner_id:learnerId,lesson_id:id,completed:true,confidence:Number(document.getElementById('confidence').value),note:document.getElementById('note').value,saved:false})});toast('Progress saved')}
function speakLesson(){speechSynthesis.cancel();const text=document.querySelector('.lesson').innerText;speechSynthesis.speak(new SpeechSynthesisUtterance(text))}
async function quiz(moduleId){currentAnswers={};currentQuestions=await api('/api/questions?limit=10'+(moduleId?'&module_id='+encodeURIComponent(moduleId):''));renderQuiz(false)}
function renderQuiz(showResults,results={}){app.innerHTML=`<div class="card"><h1>Question Drill</h1>${currentQuestions.map((q,i)=>`<div class="card"><div class="eyebrow">Question ${i+1}</div><h3>${escapeHtml(q.question)}</h3><div class="choices">${q.choices.map((c,idx)=>{const r=results[q.id];let cls='choice';if(currentAnswers[q.id]===idx)cls+=' selected';if(r&&idx===r.answer)cls+=' correct';if(r&&idx===r.selected&&!r.correct)cls+=' wrong';return `<div class="${cls}" onclick="answer('${q.id}',${idx})">${escapeHtml(c)}</div>`}).join('')}</div>${results[q.id]?`<p><strong>${results[q.id].correct?'Correct':'Review this'}:</strong> ${escapeHtml(results[q.id].explanation)}</p>`:''}</div>`).join('')}<div class="toolbar"><button class="primary" onclick="submitQuiz()">Submit Answers</button><button onclick="quiz()">New Quiz</button></div></div>`}
function answer(qid,idx){currentAnswers[qid]=idx;renderQuiz(false)}
async function submitQuiz(){const out=await api('/api/questions/submit',{method:'POST',body:JSON.stringify({learner_id:learnerId,answers:currentAnswers})});const map={};out.results.forEach(r=>map[r.id]=r);renderQuiz(true,map);toast('Score: '+out.score+'%')}
async function showFlashcards(){flashcards=await api('/api/flashcards');flashIndex=0;flashShow=false;renderFlash()}
function renderFlash(){const c=flashcards[flashIndex]||{term:'No cards',definition:''};app.innerHTML=`<div class="card"><h1>Flashcards</h1><div class="flashcard" onclick="flashShow=!flashShow;renderFlash()"><div>${flashShow?escapeHtml(c.definition):escapeHtml(c.term)}</div></div><p class="muted">${flashIndex+1} of ${flashcards.length} • ${escapeHtml(c.module||'')}</p><div class="toolbar"><button onclick="flashIndex=Math.max(0,flashIndex-1);flashShow=false;renderFlash()">Previous</button><button class="primary" onclick="flashShow=!flashShow;renderFlash()">Flip</button><button onclick="flashIndex=Math.min(flashcards.length-1,flashIndex+1);flashShow=false;renderFlash()">Next</button></div></div>`}
async function coach(){app.innerHTML=`<div class="card"><h1>Coverage Coach</h1><p class="muted">Ask a general P&C exam-prep question. This is not state-specific legal or coverage advice.</p><textarea id="coachQ" rows="5" placeholder="Example: What is the difference between a peril and a hazard?"></textarea><div class="toolbar"><button class="primary" onclick="askCoach()">Ask</button></div><div id="coachA"></div></div>`}
async function askCoach(){const msg=document.getElementById('coachQ').value;const out=await api('/api/tutor',{method:'POST',body:JSON.stringify({message:msg})});document.getElementById('coachA').innerHTML=`<div class="card"><p>${escapeHtml(out.answer)}</p><p class="muted small">${escapeHtml(out.guardrail)}</p></div>`}
load();