#!/usr/bin/env python3
"""
state_law_seed_part2.py — State Law Questions, Part 2
States: Indiana, Iowa, Kansas, Kentucky, Louisiana, Maine, Maryland,
        Massachusetts, Michigan, Minnesota, Mississippi, Missouri, Montana
Both P&C (course='pc') and L&H (course='lh') modules per state.
25 questions per module (14 universal + 6 semi-universal + 5 state-specific).

Run from pc-license-prep-server-v2/:
    .venv/bin/python3 scripts/state_law_seed_part2.py
Safe to re-run — skips existing slugs.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sqlalchemy import select, text
from app.database import SessionLocal, create_all
from app.models import Module, Lesson, Term, Question, AnswerChoice


def build_universal_questions(state_name, regulator_title, guaranty_name,
                               ce_hours, course_label):
    reg = regulator_title
    guar = guaranty_name
    st = state_name
    return [
        (f"Who is primarily responsible for regulating the insurance industry in {st}?",
         "multiple_choice", "standard",
         f"The {reg} is the chief regulator of insurance in {st}, responsible for licensing producers, approving policy forms and rates, and enforcing the state insurance laws.",
         [(f"The {reg}", True, f"Correct. The {reg} has broad authority to regulate all aspects of insurance in {st}."),
          ("The federal Department of Insurance", False, "There is no federal Department of Insurance. Insurance regulation is primarily a state function under the McCarran-Ferguson Act."),
          ("The National Association of Insurance Commissioners (NAIC)", False, "The NAIC is a standard-setting body for regulators but has no direct regulatory authority over insurers or producers."),
          ("The state attorney general", False, "The attorney general handles legal matters but the insurance regulator has primary jurisdiction over insurance regulation.")]),

        (f"Under {st} law, which of the following is an example of misrepresentation by an insurance producer?",
         "multiple_choice", "standard",
         "Misrepresentation is an unfair trade practice that includes making false or misleading statements about the terms, benefits, or conditions of an insurance policy.",
         [("Telling a client that a policy covers losses it does not actually cover", True, "Correct. Making false statements about policy coverage is misrepresentation — a prohibited unfair trade practice in every state."),
          ("Explaining to a client the differences between two competing policies", False, "Explaining policy differences accurately is legitimate sales practice, not misrepresentation."),
          ("Recommending a policy based on the client's stated financial needs", False, "Recommending suitable coverage based on client needs is proper producer duty."),
          ("Delivering a policy within the time required by state law", False, "Timely policy delivery is a producer obligation, not a prohibited practice.")]),

        (f"In {st}, rebating is best defined as:",
         "multiple_choice", "standard",
         "Rebating is offering or giving any valuable consideration as an inducement to purchase insurance. It is prohibited because it undermines the integrity of filed rates.",
         [("Offering anything of value as an inducement to purchase insurance", True, "Correct. Rebating is giving or promising any valuable consideration beyond the policy itself to induce an insurance purchase."),
          ("Charging a client more than the filed premium rate", False, "Charging above filed rates is overcharging, not rebating."),
          ("Replacing one policy with another without the client's consent", False, "Replacing a policy without consent through misrepresentation is twisting."),
          ("Splitting a commission with another licensed producer", False, "Commission sharing between licensed producers is generally permitted.")]),

        (f"An insurance producer in {st} who uses misrepresentation to persuade a policyholder to cancel an existing policy and purchase a new one is guilty of:",
         "multiple_choice", "standard",
         "Twisting is the use of misrepresentation to induce a policyholder to replace an existing policy. It is a prohibited unfair trade practice in all states.",
         [("Twisting", True, "Correct. Using misrepresentation to induce a policyholder to replace an existing policy is twisting."),
          ("Rebating", False, "Rebating involves giving something of value as an inducement to purchase, not misrepresentation to replace."),
          ("Defamation", False, "Defamation involves making false statements about another insurer or producer."),
          ("Churning", False, "Churning is replacement within the same company primarily for commission.")]),

        (f"Under {st} insurance law, a producer's license may be suspended or revoked for which of the following reasons?",
         "multiple_choice", "standard",
         "Insurance licenses may be suspended or revoked for misconduct including misappropriation of premiums, misrepresentation, and fraud.",
         [("Misappropriating client premium funds", True, "Correct. Misappropriating client premiums is a serious violation of fiduciary duty and grounds for license action in every state."),
          ("Failing the licensing exam on the first attempt", False, "Failing an exam is not grounds for license discipline."),
          ("Selling only one type of insurance product", False, "Specializing in one type of insurance is not a violation."),
          ("Recommending a competitor's product to a client", False, "Recommending a competitor's product is not a prohibited act.")]),

        (f"In {st}, when a licensed producer collects a premium payment from a client, those funds are considered:",
         "multiple_choice", "standard",
         "Premium funds collected by a producer must be held in a fiduciary capacity — the producer may not commingle them with personal or business funds.",
         [("Fiduciary funds that must be held separately from the producer's own money", True, "Correct. Collected premiums are fiduciary funds that must not be commingled with personal funds."),
          ("The producer's personal income until transmitted to the insurer", False, "Premium funds are never the producer's personal income."),
          ("Subject to a producer's lien until earned commissions are deducted", False, "Producers cannot retain premiums as a lien for commissions."),
          ("Unclaimed until the policy is formally issued", False, "Premium funds must be held as fiduciary property from the moment they are collected.")]),

        (f"The purpose of {st}'s insurance guaranty association is to:",
         "multiple_choice", "standard",
         f"The {guar} protects policyholders when a licensed insurer becomes insolvent, paying covered claims up to specified limits.",
         [(f"Pay covered claims when a licensed insurer becomes insolvent", True, f"Correct. The {guar} protects policyholders by paying covered claims when a licensed insurer is declared insolvent."),
          ("Regulate insurance rates to keep premiums affordable", False, "Rate regulation is the function of the state insurance regulator, not the guaranty association."),
          ("Provide reinsurance to small insurance companies", False, "Reinsurance is a private market function; the guaranty association does not provide reinsurance."),
          ("Manage the state's high-risk insurance pool", False, "High-risk pools are separate mechanisms from the guaranty association.")]),

        (f"Under {st} law, when a producer wants to replace a client's existing life insurance policy with a new one, the producer must:",
         "multiple_choice", "standard",
         "Replacement regulations require producers to provide written comparison documents and notify the existing insurer.",
         [("Provide a written comparison disclosure and notify the existing insurer", True, "Correct. Replacement regulations require comparison disclosures and notification to the insurer whose policy is being replaced."),
          ("Obtain written approval from the state insurance department", False, "State approval is not required for individual replacements."),
          ("Cancel the existing policy before placing the new policy", False, "The replacement should be in place before cancelling the existing policy."),
          ("Charge no commission on the replacement policy", False, "Commission restrictions are not a standard replacement regulation requirement.")]),

        (f"In {st}, a nonresident producer who is licensed in another state wants to obtain a {st} license. Generally, this producer:",
         "multiple_choice", "standard",
         "Most states grant nonresident licenses by reciprocity without requiring a separate exam for producers in good standing in their home state.",
         [("May be issued a nonresident license without taking the state exam if their home state offers reciprocity", True, "Correct. Most states waive the exam for nonresident applicants whose home state has a reciprocal licensing agreement."),
          ("Must take and pass the full state licensing exam regardless of home state license", False, "Most states waive the exam requirement for nonresident applicants with reciprocal home state licenses."),
          ("Must establish a business office in the state before receiving a license", False, "Nonresident producers are not required to maintain a physical office in the nonresident state."),
          ("Is exempt from all continuing education requirements in the nonresident state", False, "Nonresident producers may be subject to CE requirements.")]),

        (f"In {st}, which of the following activities constitutes coercion in the sale of insurance?",
         "multiple_choice", "standard",
         "Coercion is using threats, force, or economic pressure to compel someone to purchase insurance. It is a prohibited unfair trade practice.",
         [("Threatening to cancel a client's business contract unless they purchase insurance through you", True, "Correct. Using threats or economic pressure to compel an insurance purchase is coercion — a prohibited unfair trade practice."),
          ("Recommending a specific insurer based on financial strength ratings", False, "Recommending an insurer based on objective criteria is legitimate sales practice."),
          ("Explaining the penalties for driving without required auto insurance", False, "Explaining legal requirements is not coercion."),
          ("Offering a client a choice between two different policy options", False, "Offering policy choices is standard sales practice, not coercion.")]),

        (f"A {st} insurance producer's license must be renewed every:",
         "multiple_choice", "standard",
         f"Most states require license renewal every two years with continuing education requirements.",
         [("Two years, with continuing education requirements", True, f"Correct. Most states including {st} require license renewal every two years with required continuing education."),
          ("One year, without any continuing education requirement", False, "Annual renewal without CE is not the standard."),
          ("Five years, with no exam required at renewal", False, "5-year renewal cycles are not standard."),
          ("There is no renewal requirement once a license is issued", False, "All state insurance licenses require periodic renewal.")]),

        (f"Under {st} law, a temporary insurance license may be issued to:",
         "multiple_choice", "standard",
         "Temporary licenses are most commonly issued to allow continuity of an agency after the death or incapacitation of the licensed producer.",
         [("A surviving spouse or family member to continue an agency after the death of a licensed producer", True, "Correct. Temporary licenses are most commonly issued for agency continuity after death or incapacitation."),
          ("Any person who applies for a license while waiting for exam results", False, "Waiting for exam results does not qualify for a temporary license."),
          ("A person who failed the licensing exam and needs time to retake it", False, "Exam failure does not qualify for a temporary license."),
          ("Any unlicensed employee of an insurance agency", False, "Simply being employed by an agency does not qualify for a temporary license.")]),

        (f"In {st}, which of the following best describes an agent's express authority?",
         "multiple_choice", "standard",
         "Express authority is explicitly granted in writing through the agency agreement between the producer and the insurer.",
         [("Authority that is specifically granted in the written agency agreement", True, "Correct. Express authority is explicitly stated in the written contract between the producer and the insurer."),
          ("Authority that arises from the producer's position and normal business customs", False, "Authority arising from position and custom is implied authority."),
          ("Authority created when a third party reasonably believes the producer has authority based on the insurer's conduct", False, "Authority created by the insurer's conduct is apparent authority."),
          ("Authority that the producer assumes without any written agreement", False, "Assumed authority without written authorization is not a valid type of authority.")]),

        (f"Under {st} insurance law, defamation by an insurance producer is best defined as:",
         "multiple_choice", "standard",
         "Defamation is making false statements about another insurer or producer that injure their reputation. Truth is a complete defense.",
         [("Making false statements that injure the reputation of another insurer or producer", True, "Correct. Defamation is making false statements about another insurer or producer. Truthful statements are not defamation."),
          ("Accurately reporting a competitor's financial difficulties to a client", False, "Truthful statements are not defamation."),
          ("Failing to disclose a material fact about a policy to a client", False, "Failure to disclose is misrepresentation by omission, not defamation."),
          ("Using intimidation to prevent a client from shopping other insurers", False, "Using intimidation is coercion, not defamation.")]),
    ]


def build_semi_universal(state_name, regulator_title, guaranty_name,
                          ce_hours, course_label):
    st = state_name
    reg = regulator_title
    return [
        (f"A {st} insurance producer who moves to a new address must notify the {reg} within:",
         "multiple_choice", "standard",
         "Most states require producers to notify the regulator of address changes within 30 days.",
         [("30 days of the address change", True, f"Correct. Most states require notification of address changes within 30 days."),
          ("5 business days", False, "5 business days is shorter than the standard requirement."),
          ("60 days", False, "60 days exceeds the typical requirement."),
          ("At the next license renewal", False, "Address changes must be reported promptly, not deferred until renewal.")]),

        (f"In {st}, continuing education requirements for licensed insurance producers typically include:",
         "multiple_choice", "standard",
         "Most states require CE hours per renewal cycle including a required ethics component.",
         [(f"A specified number of hours including an ethics component", True, "Correct. Most states require a minimum number of CE hours with a required ethics component."),
          ("Only product knowledge courses with no ethics requirement", False, "Ethics is a required component of CE in virtually all states."),
          ("CE is optional — only required if the producer had a complaint filed", False, "CE is a mandatory renewal requirement."),
          ("A state exam retake every renewal cycle", False, "Retaking the exam is not a CE requirement.")]),

        (f"Under {st} law, an insurance producer who is convicted of a felony must:",
         "multiple_choice", "standard",
         "Most states require producers to report criminal convictions to the state insurance regulator within a specified timeframe.",
         [("Report the conviction to the state insurance regulator within the required timeframe", True, "Correct. Most states require reporting of felony convictions to the regulator."),
          ("Immediately surrender their license without any hearing", False, "A conviction triggers reporting requirements and may lead to a hearing but not automatic immediate surrender."),
          ("Only report the conviction if it relates to financial crimes", False, "Most states require reporting of all felony convictions."),
          ("Wait until the conviction is final before reporting", False, "Most states require reporting upon conviction.")]),

        (f"In {st}, which entity must give prior approval before an insurance producer can use advertising materials?",
         "multiple_choice", "standard",
         "The insurer must review and approve advertising materials used by its producers to ensure compliance with state regulations.",
         [("The insurer the producer represents", True, "Correct. The insurer must review and approve producer advertising materials."),
          ("The state insurance department must pre-approve all advertisements", False, "Pre-approval by the state department is not required for most lines."),
          ("A national advertising standards board", False, "There is no national advertising standards board for insurance."),
          ("No approval is needed — producers may advertise freely", False, "Insurance advertising is regulated; insurer approval is typically required.")]),

        (f"The {guaranty_name} covers claims when:",
         "multiple_choice", "standard",
         f"The guaranty association covers claims when a licensed (admitted) insurer becomes insolvent — not when unlicensed insurers fail.",
         [(f"A licensed admitted insurer is declared insolvent", True, f"Correct. The guaranty association covers claims when a licensed insurer becomes insolvent."),
          ("A claim is denied by any insurer for any reason", False, "The guaranty association only covers insolvency situations."),
          ("A policyholder cannot afford to pay their premium", False, "Premium affordability is not a triggering condition."),
          ("An unauthorized insurer fails to pay claims", False, "The guaranty association covers only licensed admitted insurer failures.")]),

        (f"Under {st} law, a producer who shares a commission with an unlicensed person:",
         "multiple_choice", "standard",
         "Sharing commissions with unlicensed individuals is prohibited and grounds for license discipline in all states.",
         [("Violates state insurance law and may have their license suspended or revoked", True, "Correct. Sharing commissions with unlicensed persons is prohibited."),
          ("Is permitted as long as the unlicensed person performed legitimate services", False, "Services performed do not authorize commission sharing with unlicensed persons."),
          ("Must report the sharing arrangement to the state insurance department", False, "The arrangement itself is prohibited; disclosure does not make it permissible."),
          ("Is only permitted if the unlicensed person is a family member", False, "Family relationships do not create an exception to this prohibition.")]),
    ]


def build_state_specific(state_abbr):
    specifics = {
        "IN": [
            ("In Indiana, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "Indiana's insurance regulator is the Commissioner of Insurance, appointed by the Governor. The Department of Insurance is the regulatory agency.",
             [("Commissioner of Insurance", True, "Correct. Indiana's insurance regulator is the Commissioner of Insurance."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not Indiana."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York, not Indiana."),
              ("Chief Financial Officer", False, "CFO is the title used in Florida's insurance regulatory structure, not Indiana.")]),
            ("The Indiana Life and Health Insurance Guaranty Association provides protection to Indiana policyholders when:",
             "multiple_choice", "standard",
             "The Indiana guaranty association protects policyholders when a licensed Indiana life, health, or annuity insurer becomes insolvent.",
             [("A licensed Indiana insurer is declared insolvent", True, "Correct. The Indiana guaranty association covers claims from licensed insurer insolvencies."),
              ("A producer fails to remit premiums to the insurer", False, "Premium mishandling is a compliance issue, not a guaranty association trigger."),
              ("A claim is denied as outside the policy's terms", False, "Coverage disputes are handled by the Commissioner and courts, not the guaranty association."),
              ("An insurer cancels a policy for non-payment of premium", False, "Policy cancellations for non-payment are not guaranty association situations.")]),
            ("Under Indiana insurance law, the Insurance Commissioner is:",
             "multiple_choice", "standard",
             "Indiana's Insurance Commissioner is appointed by the Governor, unlike some states where the regulator is elected.",
             [("Appointed by the Governor", True, "Correct. Indiana's Insurance Commissioner is appointed by the Governor, not elected by voters."),
              ("Elected by Indiana voters statewide", False, "Indiana's Commissioner is appointed, not elected. California is an example of a state with an elected Commissioner."),
              ("Selected by the Indiana state legislature", False, "The legislature does not select Indiana's Commissioner."),
              ("Appointed by the Indiana Supreme Court", False, "The Supreme Court has no role in selecting Indiana's Insurance Commissioner.")]),
            ("In Indiana, the Indiana Unfair Competition Law prohibits which of the following?",
             "multiple_choice", "standard",
             "Indiana's Unfair Competition Law prohibits a range of unfair trade practices including twisting, rebating, misrepresentation, defamation, and unfair discrimination.",
             [("Twisting, rebating, misrepresentation, defamation, and unfair discrimination", True, "Correct. Indiana's Unfair Competition Law prohibits all of these practices as unfair methods of competition."),
              ("Only rebating and twisting — other practices are permitted", False, "Indiana's law prohibits a broader range of unfair practices beyond just rebating and twisting."),
              ("Only practices involving life insurance policies", False, "Indiana's unfair competition law applies to all lines of insurance."),
              ("Only practices that result in consumer complaints", False, "Unfair practices are prohibited regardless of whether they generate complaints.")]),
            ("Under Indiana law, a producer must complete continuing education including:",
             "multiple_choice", "standard",
             "Indiana requires licensed producers to complete continuing education hours per renewal cycle, including required ethics training, as a condition of license renewal.",
             [("Ethics training as part of the required CE hours", True, "Correct. Indiana requires ethics training as a component of continuing education for license renewal."),
              ("A minimum of 100 hours of CE annually", False, "100 hours annually far exceeds Indiana's actual CE requirement."),
              ("CE only for producers who sell variable products", False, "CE is required for all Indiana producers, not just those selling variable products."),
              ("No CE — continuing education is voluntary in Indiana", False, "Continuing education is a mandatory requirement for Indiana license renewal.")]),
        ],
        "IA": [
            ("In Iowa, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Iowa uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Iowa uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Iowa insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Iowa insurance exams."),
              ("The Iowa Insurance Division directly", False, "Iowa contracts with Pearson VUE for exam administration.")]),
            ("In Iowa, the insurance regulatory official is called the:",
             "multiple_choice", "standard",
             "Iowa's insurance regulator holds the title of Commissioner of Insurance.",
             [("Commissioner of Insurance", True, "Correct. Iowa's insurance regulator is the Commissioner of Insurance."),
              ("Director of Insurance", False, "Director is used in Illinois and Idaho, not Iowa."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York, not Iowa."),
              ("Secretary of Financial Services", False, "This title is not used for Iowa's insurance regulator.")]),
            ("The Iowa Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Iowa Life and Health Insurance Guaranty Association protects Iowa policyholders when a licensed Iowa life, health, or annuity insurer becomes insolvent.",
             [("Protects Iowa policyholders when a licensed insurer becomes insolvent", True, "Correct. The Iowa guaranty association covers claims from insolvency of licensed Iowa insurers."),
              ("Provides free health insurance to low-income Iowans", False, "The guaranty association is an insolvency protection mechanism, not an affordability program."),
              ("Sets the rates charged by all Iowa insurance companies", False, "Rate setting is the function of the Commissioner, not the guaranty association."),
              ("Guarantees that all insurance claims will be paid in full without limits", False, "All guaranty associations have maximum coverage limits.")]),
            ("Under Iowa law, which Sircon platform function is commonly used by producers?",
             "multiple_choice", "standard",
             "Sircon is an online platform used in Iowa and other states for producer license management, including tracking continuing education credits and managing license information.",
             [("Tracking continuing education credits and managing license information", True, "Correct. Iowa uses Sircon for CE tracking and license management functions."),
              ("Filing insurance claims on behalf of policyholders", False, "Sircon is a licensing platform, not a claims management system."),
              ("Reporting fraud directly to the Iowa Insurance Fraud Bureau", False, "Fraud reporting uses a different process; Sircon is a licensing platform."),
              ("Calculating premium rates for insurance products", False, "Sircon manages licensing and CE — not pricing or premium calculations.")]),
            ("Iowa's viatical settlement regulations protect:",
             "multiple_choice", "standard",
             "Iowa regulates viatical settlements to protect terminally and chronically ill policyholders from being exploited when selling their life insurance policies for immediate cash.",
             [("Terminally or chronically ill policyholders who sell their life insurance policies", True, "Correct. Iowa's viatical settlement regulations protect vulnerable policyholders from exploitation in the sale of their life insurance policies."),
              ("Insurance companies that purchase policies in the secondary market", False, "The regulations protect policyholders (viators), not the companies purchasing policies."),
              ("Producers who broker viatical settlement transactions", False, "Regulations protect the viator (policyholder), though they also establish rules for brokers and providers."),
              ("Beneficiaries who challenge viatical settlement decisions", False, "Beneficiaries do not have a primary protected role in viatical settlement regulations.")]),
        ],
        "KS": [
            ("In Kansas, the Insurance Commissioner is:",
             "multiple_choice", "standard",
             "Kansas's Insurance Commissioner is elected by Kansas voters — one of the relatively few states where the insurance regulator is directly elected.",
             [("Elected by Kansas voters", True, "Correct. Kansas's Insurance Commissioner is elected by voters, not appointed by the Governor."),
              ("Appointed by the Governor with Senate confirmation", False, "Kansas's Commissioner is elected, not appointed."),
              ("Appointed by the Kansas state legislature", False, "The legislature does not appoint Kansas's Commissioner."),
              ("Selected by the Kansas Supreme Court", False, "The Kansas Supreme Court has no role in selecting the Insurance Commissioner.")]),
            ("The Kansas Life and Health Insurance Guaranty Association Act:",
             "multiple_choice", "standard",
             "The Kansas Life and Health Insurance Guaranty Association Act provides protection for Kansas policyholders when a licensed Kansas life, health, or annuity insurer becomes insolvent.",
             [("Provides protection for policyholders when a licensed Kansas insurer becomes insolvent", True, "Correct. The Kansas guaranty association covers claims from insolvency of licensed Kansas insurers."),
              ("Requires all Kansas insurers to carry reinsurance", False, "Reinsurance requirements are separate from the guaranty association."),
              ("Guarantees profit margins for Kansas insurance companies", False, "The guaranty association protects policyholders, not insurer profits."),
              ("Only applies to property and casualty insurance in Kansas", False, "The Kansas Life and Health Insurance Guaranty Association specifically covers life, health, and annuity products.")]),
            ("Under Kansas law, annuity suitability standards require producers to:",
             "multiple_choice", "standard",
             "Kansas has adopted annuity suitability standards requiring producers to obtain information about the client's financial situation, needs, and objectives before recommending an annuity.",
             [("Obtain information about the client's financial situation before recommending an annuity", True, "Correct. Kansas annuity suitability requires producers to gather client financial information to ensure recommendations are appropriate."),
              ("Recommend only indexed annuities to clients over age 60", False, "Suitability requires matching products to individual needs, not defaulting to indexed annuities."),
              ("Obtain approval from the Commissioner before completing each annuity sale", False, "Individual transaction approval is not required."),
              ("Guarantee the annuity will not lose value over any calendar year", False, "Guaranteeing performance beyond the product's actual terms would be misrepresentation.")]),
            ("Kansas insurance law prohibits which of the following advertising practices?",
             "multiple_choice", "standard",
             "Kansas, like all states, prohibits false or misleading advertising, which includes making false comparisons to competitor products, guaranteeing misleading returns, and other deceptive practices.",
             [("False or misleading statements in insurance advertisements", True, "Correct. Kansas prohibits false and misleading advertising — one of several unfair trade practices related to marketing."),
              ("Advertising insurance products on social media platforms", False, "Social media advertising is permitted as long as it is truthful and not misleading."),
              ("Using the word 'guaranteed' in any insurance advertisement", False, "Using 'guaranteed' is permitted when the statement is accurate and refers to an actual guarantee in the policy."),
              ("Listing premium rates in printed insurance advertisements", False, "Listing accurate premium rates in advertising is permitted.")]),
            ("In Kansas, a producer who engages in 'churning' of insurance policies is:",
             "multiple_choice", "standard",
             "Churning is the internal replacement of a client's policy primarily to generate new commissions rather than to benefit the client. It is a prohibited unfair trade practice.",
             [("Committing a prohibited unfair trade practice that may result in license discipline", True, "Correct. Churning is recommending replacement primarily for the producer's commission benefit — a prohibited unfair trade practice."),
              ("Following a recommended best practice for keeping policies current", False, "Churning is prohibited; it serves the producer's interests at the expense of the client."),
              ("Required to notify the Commissioner within 30 days", False, "Churning is illegal; it is not a reportable practice — it must simply not be done."),
              ("Permitted as long as the client signs a disclosure statement", False, "Disclosure does not make churning permissible; the practice itself is prohibited.")]),
        ],
        "KY": [
            ("In Kentucky, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Kentucky is one of two states (along with Alabama) that self-administer their insurance licensing exams. Kentucky's Department of Insurance directly administers the exam.",
             [("The Kentucky Department of Insurance directly", True, "Correct. Kentucky self-administers its insurance licensing exams through the Department of Insurance."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Kentucky's insurance exams. Kentucky self-administers."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Kentucky's insurance exams. Kentucky self-administers."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Kentucky's insurance exams. Kentucky self-administers.")]),
            ("Under KRS 304.9-020 through 304.9-051, Kentucky defines an insurance agent/producer as:",
             "multiple_choice", "standard",
             "Kentucky's insurance code (KRS 304.9) defines the requirements and qualifications for insurance agents and producers, including who must be licensed and the scope of their authority.",
             [("A person who solicits, negotiates, or sells insurance on behalf of an insurer", True, "Correct. Kentucky's code defines producers as those who solicit, negotiate, or sell insurance."),
              ("Only a person who sells life insurance with a face amount over $50,000", False, "The definition applies to all lines and face amounts."),
              ("Any employee of an insurance company regardless of their role", False, "Not all insurer employees are producers; producers specifically engage in selling and soliciting activities."),
              ("Only a person who has passed the Kentucky bar examination", False, "A law degree is not required to be an insurance producer.")]),
            ("Kentucky's license renewal procedures (KRS 304.9-260) require producers to:",
             "multiple_choice", "standard",
             "Kentucky requires producers to renew their licenses periodically and complete continuing education as a condition of renewal, as specified in KRS 304.9-260.",
             [("Complete continuing education and pay renewal fees within the renewal period", True, "Correct. Kentucky requires CE completion and fee payment for license renewal."),
              ("Retake the full licensing examination at each renewal", False, "Retaking the exam is not a Kentucky renewal requirement."),
              ("Submit to a criminal background check at each renewal", False, "Background checks are not required at each renewal in Kentucky."),
              ("Obtain insurer letters of recommendation for renewal", False, "Insurer recommendations are not required for Kentucky license renewal.")]),
            ("Under KRS 304.9-390, Kentucky insurance producers must retain business records for:",
             "multiple_choice", "standard",
             "Kentucky's record retention requirements (KRS 304.9-390) specify the minimum period producers must keep records of their insurance transactions, allowing the Commissioner to examine them.",
             [("At least the minimum period specified by state regulation, allowing for regulatory examination", True, "Correct. Kentucky's record retention rules require keeping records for the minimum period to allow regulatory examination."),
              ("No minimum period — records may be destroyed immediately after each transaction", False, "Records must be retained for a minimum period under Kentucky law."),
              ("Only while the related policies are still in force", False, "Records must be kept for the regulatory minimum period regardless of whether the policy is still in force."),
              ("One year from each transaction with no exceptions", False, "One year may be less than the required retention period under Kentucky law.")]),
            ("The Kentucky Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Kentucky Life and Health Insurance Guaranty Association provides protection for Kentucky residents holding life, health, and annuity policies when a licensed Kentucky insurer becomes insolvent.",
             [("Protects Kentucky policyholders when a licensed Kentucky insurer becomes insolvent", True, "Correct. The Kentucky guaranty association covers claims from licensed Kentucky insurer insolvencies."),
              ("Provides premium subsidies for low-income Kentucky residents", False, "The guaranty association is an insolvency protection mechanism, not a subsidy program."),
              ("Sets the standards for all Kentucky insurance policy forms", False, "Policy form standards are set by the Commissioner, not the guaranty association."),
              ("Requires all Kentucky insurers to maintain minimum surplus levels", False, "Surplus requirements are set by the Commissioner; the guaranty association provides policyholder protection.")]),
        ],
        "LA": [
            ("In Louisiana, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Louisiana uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Louisiana uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Louisiana insurance exams. Louisiana uses PSI."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Louisiana insurance exams. Louisiana uses PSI."),
              ("The Louisiana Department of Insurance directly", False, "Louisiana contracts with PSI for exam administration.")]),
            ("Under Louisiana law, a producer who violates the prohibition on using the Life and Health Guaranty Association in advertising:",
             "multiple_choice", "standard",
             "Louisiana, like all states, prohibits producers and insurers from using the existence of the guaranty association as a marketing or sales tool. This prevents misleading consumers into thinking all coverage is guaranteed by the state.",
             [("Commits an unfair trade practice that may result in license discipline", True, "Correct. Using the guaranty association's existence as a sales tool is a prohibited practice that can result in discipline."),
              ("Must pay a small administrative fine only", False, "Violations can result in license discipline, not just administrative fines."),
              ("Is encouraged since it helps consumers understand policyholder protections", False, "Using the guaranty association in advertising is specifically prohibited to prevent consumers from mistakenly believing all claims are state-guaranteed."),
              ("May advertise the association only in materials approved by the Commissioner", False, "Louisiana prohibits such advertising entirely, not just requiring pre-approval.")]),
            ("Louisiana insurance law requires producers to comply with replacement rules that include:",
             "multiple_choice", "standard",
             "Louisiana's replacement regulations require specific disclosures, comparison documents, and notification to the existing insurer when replacing life insurance or annuity policies.",
             [("Providing comparison disclosures and notifying the existing insurer", True, "Correct. Louisiana's replacement regulations require comparison disclosures to the client and notification to the existing insurer."),
              ("Obtaining the Commissioner's approval before completing any replacement", False, "Commissioner approval is not required for individual replacements."),
              ("Guaranteeing the new policy will cost less than the replaced policy", False, "Guaranteeing lower costs would be misrepresentation; replacement rules require disclosure, not guarantees."),
              ("Waiting 30 days after submitting the application before placing the new policy", False, "A 30-day delay is not a Louisiana replacement regulation requirement.")]),
            ("Under Louisiana law, the Insurance Commissioner's duties include:",
             "multiple_choice", "standard",
             "Louisiana's Insurance Commissioner has broad regulatory authority including licensing, rate review, market conduct examinations, and enforcement of the insurance code.",
             [("Licensing producers, examining insurer records, and enforcing the insurance code", True, "Correct. The Louisiana Commissioner has the full range of regulatory powers."),
              ("Setting premium rates for all insurance sold in Louisiana", False, "Insurers file rates; the Commissioner reviews for compliance but does not set rates unilaterally."),
              ("Defending producers in malpractice claims", False, "Defending producers in legal matters is not a regulatory function."),
              ("Approving all insurance claims before they are paid", False, "Individual claim approval is not a Commissioner function.")]),
            ("In Louisiana, which type of license allows a producer to place coverage with non-admitted insurers?",
             "multiple_choice", "standard",
             "A surplus lines license allows producers to place coverage with non-admitted (unauthorized) insurers when coverage is not available in the admitted market. It requires a separate license beyond the standard producer license.",
             [("A surplus lines producer license", True, "Correct. Louisiana requires a separate surplus lines license to place coverage with non-admitted insurers."),
              ("A general producer license covers all placements including non-admitted", False, "A general producer license does not automatically authorize surplus lines placements."),
              ("No special license is needed — any producer can use non-admitted insurers", False, "Surplus lines placements require a specific surplus lines license."),
              ("A managing general agent license authorizes surplus lines placements", False, "An MGA license does not specifically authorize surplus lines placements; a surplus lines license is required.")]),
        ],
        "ME": [
            ("In Maine, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Maine uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Maine uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Maine insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Maine insurance exams."),
              ("The Maine Bureau of Insurance directly", False, "Maine contracts with Pearson VUE for exam administration.")]),
            ("In Maine, the insurance regulatory official is called the:",
             "multiple_choice", "standard",
             "Maine's insurance regulator holds the title of Superintendent of Insurance — one of only a handful of states using this title.",
             [("Superintendent of Insurance", True, "Correct. Maine's insurance regulator is the Superintendent of Insurance — a title used in relatively few states."),
              ("Commissioner of Insurance", False, "Commissioner is used in most states but not Maine. Maine uses Superintendent."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not Maine."),
              ("Secretary of Insurance", False, "Secretary is not the title used for Maine's insurance regulator.")]),
            ("Under Maine insurance law, viatical settlement rules:",
             "multiple_choice", "standard",
             "Maine regulates viatical and life settlements to protect terminally and chronically ill policyholders from exploitation when they sell their life insurance policies.",
             [("Protect terminally or chronically ill policyholders who sell their life insurance policies", True, "Correct. Maine's viatical settlement regulations protect vulnerable policyholders in the sale of their life insurance policies."),
              ("Are not regulated — viatical settlements are purely private transactions in Maine", False, "Maine regulates viatical settlements to protect policyholders."),
              ("Require all viatical settlement proceeds to be held in escrow for 2 years", False, "Maine does not require proceeds to be held in escrow for 2 years."),
              ("Only apply to policies with face amounts over $500,000", False, "Maine's viatical settlement regulations apply regardless of face amount.")]),
            ("Maine's insurance AIDS testing rules require:",
             "multiple_choice", "standard",
             "Maine has specific regulations governing HIV/AIDS testing in the insurance context, including informed consent requirements and confidentiality protections for test results.",
             [("Informed consent from the applicant before HIV testing and confidentiality of results", True, "Correct. Maine requires informed consent for HIV testing and protects the confidentiality of test results in the insurance context."),
              ("All life insurance applicants over age 40 to be tested for HIV", False, "Maine does not require universal HIV testing for all applicants over 40."),
              ("Insurers to automatically decline coverage for HIV-positive applicants", False, "Using HIV status to automatically decline may be unfair discrimination; Maine has specific rules governing how test results may be used."),
              ("Producers to report all HIV test results to the Superintendent", False, "HIV test results are confidential and are not reported to the Superintendent by producers.")]),
            ("The Maine Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Maine Life and Health Insurance Guaranty Association provides protection for Maine policyholders when a licensed Maine life, health, or annuity insurer becomes insolvent.",
             [("Provides protection for Maine policyholders when a licensed insurer becomes insolvent", True, "Correct. The Maine guaranty association covers claims from insolvency of licensed Maine insurers."),
              ("Provides free life insurance to Maine residents over age 65", False, "The guaranty association is an insolvency protection mechanism, not an insurance provider."),
              ("Sets maximum rates for Maine insurance products", False, "Rate regulation is the Superintendent's function, not the guaranty association."),
              ("Covers claims from surplus lines insurers that become insolvent", False, "The guaranty association covers claims from licensed admitted insurers; surplus lines are generally not covered.")]),
        ],
        "MD": [
            ("In Maryland, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Maryland uses Prometric to administer its insurance licensing examinations.",
             [("Prometric at approved testing centers", True, "Correct. Maryland uses Prometric as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Maryland insurance exams. Maryland uses Prometric."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Maryland insurance exams. Maryland uses Prometric."),
              ("The Maryland Insurance Administration directly", False, "Maryland contracts with Prometric for exam administration.")]),
            ("In Maryland, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Maryland's insurance regulatory agency is the Maryland Insurance Administration (MIA), headed by the Insurance Commissioner.",
             [("Maryland Insurance Administration (MIA)", True, "Correct. Maryland's insurance regulatory agency is the MIA, which is headed by the Insurance Commissioner."),
              ("Maryland Department of Financial Services", False, "The Department of Financial Services is not Maryland's insurance regulator. That is Florida's structure."),
              ("Maryland Bureau of Insurance", False, "The Bureau of Insurance is not Maryland's insurance regulatory agency name."),
              ("Maryland Office of Insurance Regulation", False, "The Office of Insurance Regulation is part of Florida's regulatory structure, not Maryland's.")]),
            ("Maryland requires licensed insurance producers to complete how many hours of continuing education per renewal cycle?",
             "multiple_choice", "standard",
             "Maryland requires producers to complete 24 hours of continuing education per renewal cycle, including 3 hours of ethics training, as a condition of license renewal.",
             [("24 hours including 3 hours of ethics", True, "Correct. Maryland requires 24 CE hours per renewal cycle including 3 mandatory ethics hours."),
              ("12 hours with no ethics requirement", False, "Maryland requires 24 hours, not 12, and includes an ethics requirement."),
              ("40 hours with 10 hours of ethics", False, "40 hours is significantly more than Maryland's actual CE requirement."),
              ("CE is optional for producers with 5 or more years of experience", False, "CE is mandatory for all Maryland producers regardless of experience.")]),
            ("Under Maryland insurance law, a producer must notify the Maryland Insurance Administration of an address change within:",
             "multiple_choice", "standard",
             "Maryland requires producers to notify the MIA of address changes within 30 days, consistent with most states' requirements.",
             [("30 days of the address change", True, "Correct. Maryland requires producers to report address changes to the MIA within 30 days."),
              ("3 business days", False, "3 business days is shorter than Maryland's requirement."),
              ("90 days", False, "90 days exceeds Maryland's requirement."),
              ("Only at the next renewal", False, "Maryland requires timely notification, not just at renewal.")]),
            ("Maryland's elimination of mandatory prelicensing education (effective October 1, 2024) means:",
             "multiple_choice", "standard",
             "Effective October 1, 2024, Maryland eliminated its mandatory prelicensing education requirement for most lines. Candidates no longer need to complete a prelicensing course before taking the licensing exam.",
             [("Candidates no longer need to complete a prelicensing course before taking the exam for most lines", True, "Correct. Maryland eliminated mandatory prelicensing education for most producer license types effective October 1, 2024."),
              ("Candidates are exempt from taking the licensing exam entirely", False, "The licensing exam is still required; only the prelicensing education requirement was eliminated."),
              ("Continuing education hours were increased to compensate", False, "CE requirements were not automatically increased when prelicensing was eliminated."),
              ("Prelicensing is still required for life insurance but waived for P&C", False, "Maryland eliminated prelicensing for most lines; check the current Maryland Insurance Administration Bulletin 24-19 for specifics.")]),
        ],
        "MA": [
            ("In Massachusetts, the insurance licensing exam is transitioning to:",
             "multiple_choice", "standard",
             "Massachusetts has been transitioning its insurance exam administration from Prometric to Pearson VUE. Effective July 22, 2026, Pearson VUE becomes the official provider.",
             [("Pearson VUE, effective July 22, 2026 (previously administered by Prometric)", True, "Correct. Massachusetts is transitioning from Prometric to Pearson VUE as the exam administrator effective July 22, 2026."),
              ("PSI Services — Massachusetts has always used PSI", False, "Massachusetts used Prometric and is transitioning to Pearson VUE, not PSI."),
              ("The Massachusetts Division of Insurance directly", False, "Massachusetts uses third-party exam administrators."),
              ("Prometric — no change has occurred", False, "Massachusetts is transitioning from Prometric to Pearson VUE effective July 22, 2026.")]),
            ("Under Massachusetts law, the Division of Insurance regulates:",
             "multiple_choice", "standard",
             "The Massachusetts Division of Insurance, headed by the Commissioner of Insurance, regulates all lines of insurance including licensing, rates, forms, and market conduct.",
             [("All aspects of insurance in Massachusetts including licensing, rates, and market conduct", True, "Correct. The Massachusetts Commissioner and Division of Insurance have comprehensive regulatory authority."),
              ("Only life and health insurance — P&C is regulated by a separate agency", False, "The Division of Insurance regulates all lines, not just life and health."),
              ("Only insurance companies — producers are regulated by the Board of Registration", False, "The Division of Insurance regulates both insurers and producers."),
              ("Only nonprofit insurers — for-profit companies are federally regulated", False, "All insurance entities operating in Massachusetts are regulated by the Division of Insurance.")]),
            ("Massachusetts's Unfair Insurance Practices Act prohibits:",
             "multiple_choice", "standard",
             "Massachusetts's Unfair Insurance Practices Act prohibits a broad range of unfair practices including misrepresentation, false advertising, defamation, boycott, coercion, unfair claims settlement, and rebating.",
             [("Misrepresentation, false advertising, defamation, unfair claims settlement, and rebating", True, "Correct. Massachusetts's Unfair Insurance Practices Act prohibits all of these unfair practices."),
              ("Only advertising violations — other practices are covered by separate statutes", False, "The Massachusetts Act covers a broad range of unfair practices beyond just advertising."),
              ("Only practices involving health insurance policies", False, "The Act applies to all lines of insurance."),
              ("Only practices that cause financial harm exceeding $10,000", False, "The Act applies to unfair practices regardless of dollar amount.")]),
            ("In Massachusetts, a 'special broker' license allows a producer to:",
             "multiple_choice", "standard",
             "A special broker license in Massachusetts allows producers to place coverage with non-admitted (surplus lines) insurers when coverage is unavailable in the admitted market.",
             [("Place coverage with non-admitted insurers when admitted market coverage is unavailable", True, "Correct. Massachusetts's special broker license is its surplus lines license designation."),
              ("Sell all lines of insurance without taking individual line exams", False, "A special broker license is specifically for surplus lines placements, not a blanket authorization."),
              ("Practice law related to insurance claims on behalf of policyholders", False, "Practicing law requires a law license, not a special broker insurance license."),
              ("Represent multiple insurers simultaneously without disclosure", False, "Representation of multiple insurers requires proper disclosure regardless of license type.")]),
            ("The Massachusetts Life and Health Insurance Guaranty Fund:",
             "multiple_choice", "standard",
             "The Massachusetts Life and Health Insurance Guaranty Fund provides protection for Massachusetts policyholders when a licensed Massachusetts life, health, or annuity insurer becomes insolvent.",
             [("Protects Massachusetts policyholders when a licensed insurer becomes insolvent", True, "Correct. The Massachusetts Guaranty Fund covers claims from licensed insurer insolvencies."),
              ("Provides low-interest loans to Massachusetts insurance companies", False, "The Guaranty Fund is a policyholder protection mechanism, not a lending facility."),
              ("Sets minimum reserve requirements for Massachusetts insurers", False, "Reserve requirements are set by the Commissioner, not the Guaranty Fund."),
              ("Covers all insurance claims regardless of the insurer's financial condition", False, "The Guaranty Fund only responds to insolvency situations.")]),
        ],
        "MI": [
            ("In Michigan, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Michigan uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Michigan uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Michigan insurance exams. Michigan uses PSI."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Michigan insurance exams. Michigan uses PSI."),
              ("The Michigan Department of Insurance and Financial Services directly", False, "Michigan contracts with PSI for exam administration.")]),
            ("In Michigan, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Michigan's insurance regulatory agency is the Department of Insurance and Financial Services (DIFS), which also oversees banking, credit unions, and other financial services.",
             [("Department of Insurance and Financial Services (DIFS)", True, "Correct. Michigan's insurance regulator is DIFS — the Department of Insurance and Financial Services."),
              ("Department of Commerce and Insurance", False, "Missouri uses a Department of Commerce and Insurance structure, not Michigan."),
              ("Office of Insurance Regulation", False, "This is part of Florida's regulatory structure, not Michigan's."),
              ("Division of Insurance", False, "Michigan uses DIFS as the regulatory agency name, not a Division of Insurance.")]),
            ("Under Michigan's insurance fraud regulations, a producer who submits a false insurance application:",
             "multiple_choice", "standard",
             "Michigan's Insurance Fraud Regulation imposes both civil and criminal penalties for fraudulent insurance acts, including submitting false applications.",
             [("May face both civil and criminal penalties under Michigan's Insurance Fraud Regulation", True, "Correct. Michigan's Insurance Fraud Regulation imposes significant civil and criminal penalties for fraudulent acts."),
              ("Will only receive a written warning for a first offense", False, "Insurance fraud is a serious crime with significant penalties, not just a written warning."),
              ("Can only be prosecuted if the false application resulted in a paid claim", False, "Insurance fraud can be prosecuted regardless of whether a claim was paid."),
              ("Is subject only to license suspension, not criminal prosecution", False, "Michigan's fraud law provides for criminal prosecution in addition to license discipline.")]),
            ("The Michigan Life and Health Insurance Guaranty Association covers which of the following?",
             "multiple_choice", "standard",
             "The Michigan Life and Health Insurance Guaranty Association covers life insurance, health insurance, and annuity claims when a licensed Michigan insurer becomes insolvent.",
             [("Life insurance, health insurance, and annuity claims from insolvent licensed Michigan insurers", True, "Correct. The Michigan guaranty association covers all three types of claims from insolvent licensed insurers."),
              ("Only claims from Michigan state employees' insurance plans", False, "The guaranty association covers all policyholders, not just state employees."),
              ("Claims from all insurers regardless of admitted status", False, "The guaranty association covers only admitted (licensed) insurer insolvencies."),
              ("Only claims that are filed within 90 days of insolvency declaration", False, "There is no 90-day filing limitation for guaranty association coverage.")]),
            ("Michigan's Consumer Privacy Regulation in the insurance context requires:",
             "multiple_choice", "standard",
             "Michigan's consumer privacy regulations require insurers and producers to protect the personal financial information of consumers, consistent with the Gramm-Leach-Bliley Act requirements.",
             [("Protection of consumer personal financial information and provision of privacy notices", True, "Correct. Michigan's consumer privacy regulation requires protecting personal financial information and providing proper privacy disclosures."),
              ("All consumer conversations to be recorded and stored for 5 years", False, "Recording all conversations is not a privacy regulation requirement."),
              ("Consumer credit scores to be shared with competitors upon request", False, "Sharing consumer credit information with competitors would violate privacy regulations."),
              ("Policyholders to sign a waiver before any personal information is collected", False, "Waivers of privacy rights are not a standard requirement; privacy notices are required instead.")]),
        ],
        "MN": [
            ("In Minnesota, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Minnesota uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Minnesota uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Minnesota insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Minnesota insurance exams."),
              ("The Minnesota Department of Commerce directly", False, "Minnesota contracts with Pearson VUE for exam administration.")]),
            ("In Minnesota, auto insurance is regulated under the:",
             "multiple_choice", "standard",
             "Minnesota's auto insurance is governed by the No-Fault Act, which requires personal injury protection (PIP) coverage and governs how auto accident claims are handled in the state.",
             [("No-Fault Act, which requires personal injury protection (PIP) coverage", True, "Correct. Minnesota's No-Fault Act requires PIP coverage and governs auto accident claim handling."),
              ("Tort Reform Act, which prohibits lawsuits for auto accidents", False, "Minnesota's No-Fault Act restricts but does not prohibit lawsuits — it requires PIP coverage."),
              ("Minnesota Automobile Mandatory Insurance Plan only", False, "The MAIP is the assigned risk plan; the No-Fault Act governs auto insurance more broadly."),
              ("The federal Motor Vehicle Safety Act", False, "Federal motor vehicle safety law does not govern state auto insurance coverage requirements.")]),
            ("The Minnesota Automobile Insurance Plan (MAIP) is designed to:",
             "multiple_choice", "standard",
             "The Minnesota Automobile Insurance Plan (MAIP) is Minnesota's assigned risk plan, providing auto insurance to drivers who cannot obtain coverage in the voluntary market due to their driving record.",
             [("Provide auto insurance to high-risk drivers who cannot obtain coverage in the voluntary market", True, "Correct. The MAIP is Minnesota's assigned risk mechanism for drivers unable to get coverage in the standard market."),
              ("Replace all voluntary auto insurance with a state-run plan", False, "The MAIP is an assigned risk plan — the voluntary market remains the primary source of coverage."),
              ("Provide free auto insurance to low-income Minnesota drivers", False, "The MAIP provides coverage at standard rates plus any surcharges; it is not a free insurance program."),
              ("Regulate the rates charged by all Minnesota auto insurers", False, "Rate regulation is a function of the Commissioner; the MAIP is an assigned risk mechanism.")]),
            ("Minnesota's Standard Fire Policy:",
             "multiple_choice", "standard",
             "Minnesota, like several states, has a Standard Fire Policy that establishes minimum terms for fire insurance coverage. This form has been largely supplanted by modern homeowners and commercial property policies.",
             [("Establishes minimum coverage terms for fire insurance policies in Minnesota", True, "Correct. Minnesota's Standard Fire Policy sets minimum terms for fire insurance coverage in the state."),
              ("Provides free fire insurance to all Minnesota homeowners", False, "The Standard Fire Policy is a regulatory minimum form, not free government insurance."),
              ("Prohibits insurers from excluding any fire-related losses", False, "The Standard Fire Policy establishes minimum terms; insurers can still exclude certain causes."),
              ("Only applies to commercial property insurance", False, "The Standard Fire Policy applies to both residential and commercial fire insurance in Minnesota.")]),
            ("Minnesota's FAIR Plan provides:",
             "multiple_choice", "standard",
             "Minnesota's FAIR (Fair Access to Insurance Requirements) Plan provides basic property insurance to property owners who cannot obtain coverage in the voluntary market due to the property's location or condition.",
             [("Basic property insurance to owners who cannot obtain coverage in the voluntary market", True, "Correct. Minnesota's FAIR Plan provides basic property coverage as a last resort for those unable to obtain voluntary market coverage."),
              ("Full comprehensive coverage equivalent to HO-3 policies", False, "FAIR Plans typically provide more limited basic coverage, not comprehensive HO-3 equivalent coverage."),
              ("Auto insurance to high-risk drivers in Minnesota", False, "The FAIR Plan covers property insurance; the MAIP handles auto insurance for high-risk drivers."),
              ("Life insurance to Minnesota residents denied coverage elsewhere", False, "FAIR Plans are property insurance mechanisms; life insurance has different access programs.")]),
        ],
        "MS": [
            ("In Mississippi, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Mississippi uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Mississippi uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Mississippi insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Mississippi insurance exams."),
              ("The Mississippi Insurance Department directly", False, "Mississippi contracts with Pearson VUE for exam administration.")]),
            ("In Mississippi, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "Mississippi's insurance regulator is the Commissioner of Insurance, who is elected by Mississippi voters.",
             [("Commissioner of Insurance", True, "Correct. Mississippi's insurance regulator is the Commissioner of Insurance."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not Mississippi."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York, not Mississippi."),
              ("Secretary of Financial Services", False, "This is not the title for Mississippi's insurance regulator.")]),
            ("The Mississippi Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Mississippi Life and Health Insurance Guaranty Association protects Mississippi policyholders when a licensed Mississippi life, health, or annuity insurer becomes insolvent.",
             [("Protects Mississippi policyholders when a licensed insurer becomes insolvent", True, "Correct. The Mississippi guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides government-backed health insurance to uninsured Mississippians", False, "The guaranty association is an insolvency protection mechanism."),
              ("Regulates premium rates for all Mississippi health insurance plans", False, "Rate regulation is the Commissioner's function."),
              ("Covers claims from unlicensed insurers doing business in Mississippi", False, "The guaranty association covers only licensed admitted insurer insolvencies.")]),
            ("Under Mississippi insurance law, disclosure of producer compensation requires:",
             "multiple_choice", "standard",
             "Mississippi requires producers to disclose compensation they receive when it may create a conflict of interest, consistent with consumer protection principles.",
             [("Disclosure when compensation arrangements may create a conflict of interest", True, "Correct. Mississippi requires compensation disclosure when potential conflicts of interest exist."),
              ("Complete disclosure of every dollar of compensation on every transaction", False, "Full transaction-by-transaction disclosure is not the Mississippi standard; disclosure is required when conflicts exist."),
              ("No compensation disclosure — it is confidential business information", False, "Producer compensation is subject to disclosure requirements in Mississippi."),
              ("Disclosure only when the client specifically requests it", False, "Mississippi requires proactive disclosure when conflicts exist, not only on client request.")]),
            ("Mississippi's replacement regulations for life insurance require the producer to:",
             "multiple_choice", "standard",
             "Mississippi's replacement regulations require producers to provide disclosure documents and notify the existing insurer, protecting consumers from uninformed replacement decisions.",
             [("Provide required replacement disclosure documents and notify the existing insurer", True, "Correct. Mississippi's replacement regulations require disclosure documents and notification to the existing insurer."),
              ("Get approval from the Commissioner before completing any replacement", False, "Commissioner approval is not required for individual replacements."),
              ("Guarantee that the client will not pay more on the new policy", False, "Guaranteeing lower costs would be misrepresentation; replacement rules require disclosure, not guarantees."),
              ("Only proceed with replacement if the existing policy has been in force for 3+ years", False, "Mississippi replacement regulations apply regardless of how long the existing policy has been in force.")]),
        ],
        "MO": [
            ("In Missouri, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Missouri uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Missouri uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Missouri insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Missouri insurance exams."),
              ("The Missouri Department of Commerce and Insurance directly", False, "Missouri contracts with Pearson VUE for exam administration.")]),
            ("In Missouri, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Missouri's insurance regulatory agency is the Department of Commerce and Insurance (DCI), headed by the Director of Insurance.",
             [("Department of Commerce and Insurance (DCI)", True, "Correct. Missouri's insurance regulator is the DCI, headed by the Director of Insurance."),
              ("Department of Financial Services", False, "Department of Financial Services is Florida's structure, not Missouri's."),
              ("Division of Insurance", False, "Missouri uses the Department of Commerce and Insurance, not a Division of Insurance."),
              ("Office of Insurance Regulation", False, "OIR is part of Florida's regulatory structure, not Missouri's.")]),
            ("Missouri's suitability and best-interest standard for annuity sales requires:",
             "multiple_choice", "standard",
             "Missouri has adopted a best-interest standard for annuity transactions, requiring producers to place the client's interests ahead of their own when making annuity recommendations.",
             [("Producers to act in the client's best interest when recommending annuities", True, "Correct. Missouri's best-interest standard requires producers to prioritize client interests when making annuity recommendations."),
              ("Recommending only fixed annuities to Missouri residents", False, "The best-interest standard requires appropriate product matching, not defaulting to fixed annuities."),
              ("Filing all annuity recommendation documents with the DCI", False, "Filing individual recommendation documents with the DCI is not required."),
              ("Only recommending annuities to clients with investable assets over $250,000", False, "The best-interest standard applies to all annuity recommendations regardless of asset level.")]),
            ("The Missouri Property and Casualty Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Missouri Property and Casualty Insurance Guaranty Association provides protection for Missouri policyholders when a licensed Missouri P&C insurer becomes insolvent.",
             [("Protects Missouri P&C policyholders when a licensed insurer becomes insolvent", True, "Correct. The Missouri P&C guaranty association covers P&C claims from licensed insurer insolvencies."),
              ("Sets rate caps for Missouri property and casualty insurance", False, "Rate caps are set by regulation; the guaranty association provides insolvency protection."),
              ("Provides free renters insurance to low-income Missouri residents", False, "The guaranty association is an insolvency protection mechanism."),
              ("Covers claims from all P&C insurers regardless of admitted status", False, "The guaranty association only covers admitted (licensed) insurer insolvencies.")]),
            ("Missouri's Interstate Insurance Product Regulatory Commission (IIPRC) allows:",
             "multiple_choice", "standard",
             "The IIPRC is an interstate compact that allows insurers to file certain life insurance and annuity products with a single filing that is accepted by all member states, streamlining the product approval process.",
             [("Insurance companies to file life and annuity products in multiple member states through a single filing", True, "Correct. The IIPRC compact allows single filings accepted by member states, streamlining product approval."),
              ("Producers to hold a license in one IIPRC state that is valid in all member states", False, "The IIPRC governs product filings, not producer licensing."),
              ("Missouri to opt out of all federal insurance regulations", False, "The IIPRC addresses product filings; it does not affect federal regulatory requirements."),
              ("Automatic renewal of all insurance policies in IIPRC member states", False, "The IIPRC governs product approval processes, not policy renewal terms.")]),
        ],
        "MT": [
            ("In Montana, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Montana uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Montana uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Montana insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Montana insurance exams."),
              ("The Montana Commissioner of Securities and Insurance directly", False, "Montana contracts with Pearson VUE for exam administration.")]),
            ("In Montana, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "Montana uniquely combines securities and insurance regulation under a single official — the Commissioner of Securities and Insurance.",
             [("Commissioner of Securities and Insurance", True, "Correct. Montana's insurance and securities regulation is combined under the Commissioner of Securities and Insurance."),
              ("Commissioner of Insurance only", False, "Montana's commissioner also oversees securities, not just insurance."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not Montana."),
              ("Superintendent of Financial Services", False, "Superintendent of Financial Services is not Montana's regulatory title.")]),
            ("Montana's Insurance Fraud Protection Act provides for:",
             "multiple_choice", "standard",
             "Montana's Insurance Fraud Protection Act establishes civil and criminal penalties for insurance fraud and requires producers and insurers to cooperate in fraud investigations.",
             [("Civil and criminal penalties for insurance fraud committed by producers or policyholders", True, "Correct. Montana's Insurance Fraud Protection Act imposes both civil and criminal penalties for fraudulent insurance acts."),
              ("A fraud hotline managed by the Commissioner only", False, "While a fraud hotline may exist, the Act provides for civil and criminal penalties."),
              ("Only civil penalties — insurance fraud is not a criminal matter in Montana", False, "Insurance fraud can be both a civil and criminal matter in Montana."),
              ("Immunity from prosecution for producers who self-report fraud", False, "Self-reporting does not provide immunity from prosecution under Montana's Act.")]),
            ("The Montana Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Montana Life and Health Insurance Guaranty Association provides protection for Montana policyholders when a licensed Montana life, health, or annuity insurer becomes insolvent.",
             [("Protects Montana policyholders when a licensed Montana insurer becomes insolvent", True, "Correct. The Montana guaranty association covers claims from insolvent licensed Montana insurers."),
              ("Provides subsidized insurance to rural Montana residents", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets the maximum rates for Montana life insurance products", False, "Rate setting is the Commissioner's function."),
              ("Covers claims from non-admitted insurers operating illegally in Montana", False, "The guaranty association covers only licensed admitted insurer insolvencies.")]),
            ("In Montana, a principal producer is responsible for:",
             "multiple_choice", "standard",
             "A principal producer in Montana is the primary licensee responsible for the agency's compliance with state insurance laws. They have responsibilities for supervising other producers and ensuring proper conduct.",
             [("Supervising other producers and ensuring compliance with Montana insurance laws", True, "Correct. Principal producers have supervisory and compliance responsibilities for their agencies."),
              ("Setting insurance rates on behalf of their insurer clients", False, "Setting rates is an insurer and regulatory function, not a principal producer function."),
              ("Processing all claims for policies sold by their agency", False, "Claims processing is typically handled by the insurer, not the principal producer."),
              ("Maintaining the Commissioner's examination records", False, "Regulatory examination records are maintained by the Commissioner, not producers.")]),
        ],
    }
    return specifics.get(state_abbr, [
        (f"The insurance licensing exam in {state_abbr} tests candidates on:",
         "multiple_choice", "standard",
         "State insurance licensing exams test both national product knowledge and state-specific insurance laws.",
         [("Both national insurance concepts and state-specific laws and regulations", True, "Correct. All state exams have two portions: a national general knowledge section and a state law supplement."),
          ("Only national insurance concepts with no state-specific content", False, "All state exams include a state law supplement."),
          ("Only state laws with no national content", False, "All state exams include a national general knowledge portion."),
          ("Only mathematical calculations related to insurance pricing", False, "Insurance exams cover concepts, regulations, and policy provisions.")]),
    ] * 5)


STATES_PART2 = [
    ("IN", "Indiana", "Commissioner of Insurance",
     "Indiana Life and Health Insurance Guaranty Association", 24),
    ("IA", "Iowa", "Commissioner of Insurance",
     "Iowa Life and Health Insurance Guaranty Association", 24),
    ("KS", "Kansas", "Commissioner of Insurance",
     "Kansas Life and Health Insurance Guaranty Association", 24),
    ("KY", "Kentucky", "Commissioner of Insurance",
     "Kentucky Life and Health Insurance Guaranty Association", 24),
    ("LA", "Louisiana", "Commissioner of Insurance",
     "Louisiana Life and Health Insurance Guaranty Association", 24),
    ("ME", "Maine", "Superintendent of Insurance",
     "Maine Life and Health Insurance Guaranty Association", 24),
    ("MD", "Maryland", "Insurance Commissioner",
     "Maryland Life and Health Insurance Guaranty Corporation", 24),
    ("MA", "Massachusetts", "Commissioner of Insurance",
     "Massachusetts Life and Health Insurance Guaranty Fund", 24),
    ("MI", "Michigan", "Director of Insurance and Financial Services",
     "Michigan Life and Health Insurance Guaranty Association", 24),
    ("MN", "Minnesota", "Commissioner of Commerce",
     "Minnesota Life and Health Insurance Guaranty Association", 24),
    ("MS", "Mississippi", "Commissioner of Insurance",
     "Mississippi Life and Health Insurance Guaranty Association", 24),
    ("MO", "Missouri", "Director of Insurance",
     "Missouri Life and Health Insurance Guaranty Association", 24),
    ("MT", "Montana", "Commissioner of Securities and Insurance",
     "Montana Life and Health Insurance Guaranty Association", 24),
]

COURSES = [("pc", "P&C"), ("lh", "L&H")]


def seed():
    create_all()
    db = SessionLocal()
    try:
        total_mods = total_q = 0

        for (abbr, name, regulator, guaranty, ce_hours) in STATES_PART2:
            for (course_code, course_label) in COURSES:
                mod_slug = f"state-law-{abbr.lower()}-{course_code}"

                existing = db.scalar(
                    select(Module).where(Module.slug == mod_slug))
                if existing:
                    print(f"  SKIP (exists): {mod_slug}")
                    continue

                idx = STATES_PART2.index(
                    (abbr, name, regulator, guaranty, ce_hours))
                mod = Module(
                    slug=mod_slug,
                    title=f"{name} State Law — {course_label}",
                    description=(
                        f"State-specific insurance laws for the {name} "
                        f"{course_label} licensing exam. Covers the {regulator}, "
                        f"licensing, unfair trade practices, guaranty association, "
                        f"and state-specific rules."
                    ),
                    sort_order=630 + idx * 10 + (0 if course_code == "pc" else 1),
                    is_active=True,
                )
                db.add(mod)
                db.flush()
                db.execute(
                    text("UPDATE modules SET course=:c WHERE id=:id"),
                    {"c": course_code, "id": mod.id})
                total_mods += 1
                print(f"  MODULE: {mod.title}")

                all_questions = (
                    build_universal_questions(
                        name, regulator, guaranty, ce_hours, course_label) +
                    build_semi_universal(
                        name, regulator, guaranty, ce_hours, course_label) +
                    build_state_specific(abbr)
                )

                for (q_text, q_type, difficulty,
                     explanation, choices) in all_questions:
                    q = Question(
                        module_id=mod.id,
                        lesson_id=None,
                        question_text=q_text,
                        question_type=q_type,
                        difficulty=difficulty,
                        explanation=explanation,
                        is_active=True,
                    )
                    db.add(q)
                    db.flush()
                    for sort_i, (ct, correct, ce) in enumerate(choices, 1):
                        db.add(AnswerChoice(
                            question_id=q.id,
                            choice_text=ct,
                            is_correct=correct,
                            explanation=ce,
                            sort_order=sort_i,
                        ))
                    total_q += 1

        db.commit()
        print(f"\n=== Part 2 complete: {total_mods} modules, "
              f"{total_q} questions ===")
        print("States: IN IA KS KY LA ME MD MA MI MN MS MO MT")

    finally:
        db.close()


if __name__ == "__main__":
    seed()
