#!/usr/bin/env python3
"""
state_law_seed_part4.py — State Law Questions, Part 4
States: South Dakota, Tennessee, Texas, Utah, Vermont, Virginia,
        Washington, West Virginia, Wisconsin, Wyoming, District of Columbia
Both P&C (course='pc') and L&H (course='lh') modules per state.
25 questions per module (14 universal + 6 semi-universal + 5 state-specific).

Run from pc-license-prep-server-v2/:
    .venv/bin/python3 scripts/state_law_seed_part4.py
Safe to re-run — skips existing slugs.
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sqlalchemy import select, text
from app.database import SessionLocal, create_all
from app.models import Module, Lesson, Term, Question, AnswerChoice


def build_universal_questions(state_name, regulator_title, guaranty_name,
                               ce_hours, course_label):
    reg = regulator_title
    guar = guaranty_name
    st = state_name
    return [
        (f"Who is primarily responsible for regulating the insurance industry in {st}?",
         "multiple_choice", "standard",
         f"The {reg} is the chief insurance regulator in {st}, responsible for licensing producers, approving policy forms and rates, and enforcing state insurance laws.",
         [(f"The {reg}", True, f"Correct. The {reg} has broad authority to regulate all aspects of insurance in {st}."),
          ("The federal Department of Insurance", False, "There is no federal Department of Insurance. Insurance regulation is primarily a state function under the McCarran-Ferguson Act."),
          ("The National Association of Insurance Commissioners (NAIC)", False, "The NAIC is a standard-setting body without direct regulatory authority."),
          ("The state attorney general", False, "The attorney general handles legal matters but the insurance regulator has primary jurisdiction.")]),

        (f"Under {st} law, which of the following is misrepresentation by an insurance producer?",
         "multiple_choice", "standard",
         "Misrepresentation is an unfair trade practice that includes making false or misleading statements about policy terms, benefits, or conditions.",
         [("Telling a client a policy covers losses it does not actually cover", True, "Correct. Making false statements about coverage is misrepresentation — a prohibited unfair trade practice."),
          ("Explaining differences between two competing policies accurately", False, "Accurate explanations are legitimate sales practice, not misrepresentation."),
          ("Recommending a policy based on the client's stated financial needs", False, "Recommending suitable coverage is proper producer duty."),
          ("Delivering a policy within the time required by state law", False, "Timely delivery is an obligation, not a prohibited practice.")]),

        (f"In {st}, rebating is best defined as:",
         "multiple_choice", "standard",
         "Rebating is offering or giving any valuable consideration as an inducement to purchase insurance, which is prohibited because it undermines filed rate integrity.",
         [("Offering anything of value as an inducement to purchase insurance", True, "Correct. Rebating is giving valuable consideration to induce an insurance purchase."),
          ("Charging a client more than the filed premium rate", False, "Overcharging is not rebating."),
          ("Replacing one policy with another without the client's consent", False, "Replacement through misrepresentation is twisting."),
          ("Splitting a commission with another licensed producer", False, "Commission sharing between licensed producers is generally permitted.")]),

        (f"A {st} producer who uses misrepresentation to persuade a policyholder to cancel an existing policy and buy a new one is guilty of:",
         "multiple_choice", "standard",
         "Twisting is using misrepresentation to induce a policyholder to replace an existing policy — a prohibited unfair trade practice in all states.",
         [("Twisting", True, "Correct. Using misrepresentation to induce policy replacement is twisting."),
          ("Rebating", False, "Rebating involves giving value as an inducement, not misrepresentation to replace."),
          ("Defamation", False, "Defamation is making false statements about another insurer or producer."),
          ("Churning", False, "Churning is replacement within the same company primarily for commission.")]),

        (f"Under {st} insurance law, a producer's license may be suspended or revoked for:",
         "multiple_choice", "standard",
         "Misappropriation of client premiums is a serious fiduciary violation and grounds for license suspension or revocation.",
         [("Misappropriating client premium funds", True, "Correct. Misappropriating premiums is grounds for license action in every state."),
          ("Failing the licensing exam on the first attempt", False, "Failing an exam is not grounds for license discipline."),
          ("Selling only one type of insurance product", False, "Specializing is not a violation."),
          ("Recommending a competitor's product to a client", False, "Recommending a competitor's product is not prohibited.")]),

        (f"In {st}, when a licensed producer collects a premium payment from a client, those funds are:",
         "multiple_choice", "standard",
         "Premium funds collected by a producer are fiduciary property that must be held separately from the producer's own money.",
         [("Fiduciary funds that must be held separately from the producer's own money", True, "Correct. Collected premiums are fiduciary funds that must not be commingled."),
          ("The producer's personal income until transmitted to the insurer", False, "Premiums are never the producer's personal income."),
          ("Subject to a producer's lien until earned commissions are deducted", False, "Producers cannot retain premiums as a lien."),
          ("Unclaimed until the policy is formally issued", False, "Premiums must be held as fiduciary property immediately upon collection.")]),

        (f"The purpose of {st}'s insurance guaranty association is to:",
         "multiple_choice", "standard",
         f"The {guar} protects policyholders when a licensed insurer becomes insolvent, paying claims up to statutory limits.",
         [("Pay covered claims when a licensed insurer becomes insolvent", True, f"Correct. The {guar} pays covered claims when a licensed insurer is declared insolvent."),
          ("Regulate insurance rates to keep premiums affordable", False, "Rate regulation is the regulator's function, not the guaranty association's."),
          ("Provide reinsurance to small insurance companies", False, "Reinsurance is a private market function."),
          ("Manage the state's high-risk insurance pool", False, "High-risk pools are separate mechanisms from the guaranty association.")]),

        (f"Under {st} law, when a producer wants to replace a client's existing life policy with a new one, the producer must:",
         "multiple_choice", "standard",
         "Replacement regulations require written comparison disclosures and notification to the existing insurer.",
         [("Provide a written comparison disclosure and notify the existing insurer", True, "Correct. Replacement requires comparison disclosures to the client and notification to the existing insurer."),
          ("Obtain written approval from the state insurance department", False, "State approval is not required for individual replacements."),
          ("Cancel the existing policy before placing the new policy", False, "The new policy should be in place before cancelling the existing one to avoid a coverage gap."),
          ("Charge no commission on the replacement policy", False, "Commission restrictions are not a standard replacement requirement.")]),

        (f"In {st}, a nonresident producer licensed in another state generally:",
         "multiple_choice", "standard",
         "Most states grant nonresident licenses by reciprocity without a separate exam for producers in good standing in their home state.",
         [("May be issued a nonresident license without a state exam if their home state offers reciprocity", True, "Correct. Reciprocity allows nonresident producers to skip the exam if their home state is reciprocal."),
          ("Must take and pass the full state licensing exam regardless of home state license", False, "Most states waive the exam for reciprocal nonresident applicants."),
          ("Must establish a business office in the state before receiving a license", False, "Nonresident producers are not required to maintain a physical office."),
          ("Is exempt from all continuing education requirements in the nonresident state", False, "CE may still be required for nonresident producers.")]),

        (f"In {st}, which of the following constitutes coercion in the sale of insurance?",
         "multiple_choice", "standard",
         "Coercion is using threats, force, or economic pressure to compel someone to purchase insurance — a prohibited unfair trade practice.",
         [("Threatening to cancel a client's business contract unless they purchase insurance through you", True, "Correct. Economic threats to compel an insurance purchase is coercion."),
          ("Recommending a specific insurer based on financial strength ratings", False, "Recommending based on objective criteria is legitimate."),
          ("Explaining the penalties for driving without required auto insurance", False, "Explaining legal requirements is not coercion."),
          ("Offering a client a choice between two policy options", False, "Offering choices is standard sales practice.")]),

        (f"A {st} insurance producer's license must be renewed every:",
         "multiple_choice", "standard",
         "Most states require biennial license renewal with continuing education as a condition.",
         [("Two years, with continuing education requirements", True, f"Correct. Most states including {st} require biennial renewal with required CE."),
          ("One year, without any continuing education requirement", False, "Annual renewal without CE is not the standard."),
          ("Five years, with no exam required at renewal", False, "5-year renewal cycles are not standard."),
          ("There is no renewal requirement once a license is issued", False, "All state licenses require periodic renewal and CE.")]),

        (f"Under {st} law, a temporary insurance license may be issued to:",
         "multiple_choice", "standard",
         "Temporary licenses are most commonly issued to allow agency continuity after the licensed producer's death or incapacitation.",
         [("A surviving spouse or family member to continue an agency after the licensed producer's death", True, "Correct. Temporary licenses most commonly allow agency continuity after the licensed owner's death."),
          ("Any person who applies for a license while waiting for exam results", False, "Waiting for exam results does not qualify for a temporary license."),
          ("A person who failed the exam and needs time to retake it", False, "Exam failure does not qualify for a temporary license."),
          ("Any unlicensed employee of an insurance agency", False, "Being employed by an agency does not automatically qualify for a temporary license.")]),

        (f"In {st}, express authority of an insurance producer is best described as:",
         "multiple_choice", "standard",
         "Express authority is explicitly granted in writing through the agency agreement between the producer and the insurer.",
         [("Authority specifically granted in the written agency agreement", True, "Correct. Express authority is stated explicitly in the written contract."),
          ("Authority arising from the producer's position and normal business customs", False, "Authority from position and custom is implied authority."),
          ("Authority created when a third party reasonably believes the producer has authority based on the insurer's conduct", False, "This is apparent authority."),
          ("Authority the producer assumes without any written agreement", False, "Assumed authority without agreement is not a recognized type of authority.")]),

        (f"Under {st} insurance law, defamation by a producer is:",
         "multiple_choice", "standard",
         "Defamation is making false statements about another insurer or producer that injure their reputation. Truth is a complete defense.",
         [("Making false statements that injure the reputation of another insurer or producer", True, "Correct. Defamation requires false statements; truthful statements are not defamation."),
          ("Accurately reporting a competitor's financial difficulties to a client", False, "Truthful statements are not defamation."),
          ("Failing to disclose a material fact about a policy", False, "Failure to disclose is misrepresentation by omission, not defamation."),
          ("Using intimidation to prevent a client from shopping other insurers", False, "Intimidation is coercion, not defamation.")]),
    ]


def build_semi_universal(state_name, regulator_title, guaranty_name,
                          ce_hours, course_label):
    st = state_name
    reg = regulator_title
    return [
        (f"A {st} producer who moves must notify the {reg} within:",
         "multiple_choice", "standard",
         "Most states require producers to notify the regulator of address changes within 30 days.",
         [("30 days of the address change", True, "Correct. Most states require notification within 30 days."),
          ("5 business days", False, "Shorter than the standard requirement."),
          ("60 days", False, "Exceeds the typical requirement."),
          ("At the next license renewal", False, "Changes must be reported promptly, not deferred to renewal.")]),

        (f"In {st}, continuing education for licensed producers typically includes:",
         "multiple_choice", "standard",
         "Most states require CE hours per renewal cycle including a required ethics component.",
         [("A specified number of hours including an ethics component", True, "Correct. Most states require a minimum number of CE hours with a mandatory ethics component."),
          ("Only product knowledge courses with no ethics requirement", False, "Ethics is a required component in virtually all states."),
          ("CE is optional — only required if a complaint was filed", False, "CE is a mandatory renewal requirement for all producers."),
          ("A state exam retake every renewal cycle", False, "Retaking the exam is not a CE requirement.")]),

        (f"Under {st} law, a producer convicted of a felony must:",
         "multiple_choice", "standard",
         "Most states require producers to report felony convictions to the insurance regulator within a specified timeframe.",
         [("Report the conviction to the state insurance regulator within the required timeframe", True, "Correct. Most states require prompt reporting of felony convictions."),
          ("Immediately surrender their license without any hearing", False, "A conviction triggers reporting requirements and may lead to a hearing, not automatic surrender."),
          ("Only report if the conviction relates to financial crimes", False, "Most states require reporting all felony convictions."),
          ("Wait until the conviction is final before reporting", False, "Most states require reporting upon conviction.")]),

        (f"In {st}, which entity must approve advertising materials before a producer uses them?",
         "multiple_choice", "standard",
         "The insurer must review and approve advertising materials used by its producers to ensure compliance with state regulations.",
         [("The insurer the producer represents", True, "Correct. The insurer must approve producer advertising materials for regulatory compliance."),
          ("The state insurance department must pre-approve all advertisements", False, "Pre-approval by the state is not required for most lines."),
          ("A national advertising standards board", False, "No such national board exists for insurance."),
          ("No approval is needed", False, "Insurance advertising is regulated; insurer approval is typically required.")]),

        (f"The {guaranty_name} covers claims when:",
         "multiple_choice", "standard",
         "The guaranty association covers claims only from licensed admitted insurer insolvencies — not unlicensed insurer failures.",
         [("A licensed admitted insurer is declared insolvent", True, "Correct. The guaranty association covers claims from licensed insurer insolvencies."),
          ("A claim is denied by any insurer for any reason", False, "The guaranty association only covers insolvency situations."),
          ("A policyholder cannot afford to pay their premium", False, "Premium affordability is not a guaranty association trigger."),
          ("An unauthorized insurer fails to pay claims", False, "Only licensed admitted insurer failures are covered.")]),

        (f"Under {st} law, sharing a commission with an unlicensed person:",
         "multiple_choice", "standard",
         "Sharing commissions with unlicensed individuals is prohibited and grounds for license discipline in all states.",
         [("Violates state insurance law and may result in license suspension or revocation", True, "Correct. Sharing commissions with unlicensed persons is prohibited."),
          ("Is permitted if the unlicensed person performed legitimate services", False, "Services performed do not authorize commission sharing with unlicensed persons."),
          ("Must be reported to the state insurance department", False, "The arrangement is prohibited; disclosure does not make it permissible."),
          ("Is only permitted for family members", False, "Family relationships do not create an exception.")]),
    ]


def build_state_specific(state_abbr):
    specifics = {
        "SD": [
            ("In South Dakota, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "South Dakota uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. South Dakota uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer South Dakota insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer South Dakota insurance exams."),
              ("The South Dakota Division of Insurance directly", False, "South Dakota contracts with Pearson VUE for exam administration.")]),
            ("In South Dakota, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "South Dakota's insurance regulator holds the title of Director of Insurance.",
             [("Director of Insurance", True, "Correct. South Dakota's insurance regulator is the Director of Insurance."),
              ("Commissioner of Insurance", False, "Commissioner is used in many states but not South Dakota."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York and a few other states, not South Dakota."),
              ("Secretary of Insurance", False, "Secretary is not the title used in South Dakota.")]),
            ("Under South Dakota law, a producer who commingles client premiums with personal funds:",
             "multiple_choice", "standard",
             "Commingling premium funds with personal funds is a serious fiduciary violation and a prohibited act under South Dakota insurance law, subject to license discipline.",
             [("Commits a prohibited act subject to license discipline", True, "Correct. Commingling premium funds is a fiduciary violation that can result in license suspension or revocation."),
              ("Must simply repay the commingled funds with interest", False, "Repayment alone does not resolve a commingling violation; it is a disciplinary matter."),
              ("Is only subject to discipline if the client files a complaint", False, "The Department of Insurance can take action on examination findings; a complaint is not required."),
              ("Is permitted as long as the premiums are remitted within 30 days", False, "Commingling is prohibited regardless of how quickly premiums are ultimately remitted.")]),
            ("South Dakota's viatical settlement regulations protect:",
             "multiple_choice", "standard",
             "South Dakota regulates viatical settlements to protect terminally and chronically ill policyholders who sell their life insurance policies for immediate cash.",
             [("Terminally or chronically ill policyholders who sell their life insurance policies", True, "Correct. South Dakota's viatical settlement regulations protect vulnerable policyholders."),
              ("Insurance companies purchasing policies on the secondary market", False, "The regulations protect the viator (policyholder), not the purchasing companies."),
              ("Producers who broker viatical transactions", False, "Regulations primarily protect the viator, though they also establish rules for brokers and providers."),
              ("Beneficiaries who contest viatical decisions", False, "Beneficiaries are not the primary protected party in South Dakota's viatical regulations.")]),
            ("The South Dakota Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The South Dakota Life and Health Insurance Guaranty Association protects South Dakota policyholders when a licensed South Dakota life, health, or annuity insurer becomes insolvent.",
             [("Protects SD policyholders when a licensed SD insurer becomes insolvent", True, "Correct. The South Dakota guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides free insurance to South Dakota Native American tribal members", False, "The guaranty association is an insolvency protection mechanism, not an insurance provider."),
              ("Sets rate caps for South Dakota life insurance products", False, "Rate regulation is the Director's function."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
        ],
        "TN": [
            ("In Tennessee, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Tennessee uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Tennessee uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Tennessee insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Tennessee insurance exams."),
              ("The Tennessee Department of Commerce and Insurance directly", False, "Tennessee contracts with Pearson VUE for exam administration.")]),
            ("In Tennessee, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Tennessee's insurance regulatory agency is the Department of Commerce and Insurance (TDCI), headed by the Commissioner of Commerce and Insurance.",
             [("Department of Commerce and Insurance (TDCI)", True, "Correct. Tennessee's insurance regulator is the TDCI, headed by the Commissioner of Commerce and Insurance."),
              ("Department of Financial Services", False, "DFS is Florida's and New York's regulatory structure, not Tennessee's."),
              ("Division of Insurance", False, "Tennessee uses the TDCI, not a standalone Division of Insurance."),
              ("Bureau of Insurance", False, "Bureau of Insurance is Virginia's structure; Tennessee uses the TDCI.")]),
            ("Under Tennessee law, annuity suitability standards require producers to:",
             "multiple_choice", "standard",
             "Tennessee has adopted annuity suitability requirements requiring producers to obtain information about the client's financial situation before making annuity recommendations.",
             [("Gather client financial information before recommending any annuity", True, "Correct. Tennessee's suitability standards require collecting client financial data before annuity recommendations."),
              ("Recommend only fixed indexed annuities to Tennessee clients", False, "Suitability requires matching products to individual needs, not defaulting to a specific product type."),
              ("Obtain the Commissioner's approval before completing each annuity sale", False, "Individual transaction approval is not required."),
              ("Only recommend annuities to clients with pension income", False, "Suitability standards apply to all annuity recommendations regardless of income source.")]),
            ("The Tennessee Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Tennessee Life and Health Insurance Guaranty Association protects Tennessee policyholders when a licensed Tennessee life, health, or annuity insurer becomes insolvent.",
             [("Protects Tennessee policyholders when a licensed insurer becomes insolvent", True, "Correct. The Tennessee guaranty association covers claims from licensed insurer insolvencies."),
              ("Sets premium rates for all Tennessee insurance products", False, "Rate setting is the Commissioner's function."),
              ("Provides free life insurance to Tennessee state employees", False, "The guaranty association is an insolvency protection mechanism."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Under Tennessee insurance law, a producer who engages in unfair claims settlement practices:",
             "multiple_choice", "standard",
             "Tennessee's Unfair Trade Practices Act prohibits unfair claims settlement practices including misrepresenting policy provisions, failing to acknowledge claims promptly, and refusing to pay valid claims.",
             [("Violates the Unfair Trade Practices Act and may face license discipline", True, "Correct. Unfair claims settlement practices are prohibited under Tennessee's Unfair Trade Practices Act."),
              ("Is only subject to discipline if a court finds them liable", False, "The Department can take action based on examination findings; a court finding is not required."),
              ("Is exempt from discipline if the insurer authorized the practice", False, "Insurer authorization does not exempt a producer from discipline for unfair practices."),
              ("Faces only civil penalties — not license discipline", False, "License discipline is available in addition to civil penalties for unfair trade practices.")]),
        ],
        "TX": [
            ("In Texas, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Texas uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Texas uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Texas insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Texas insurance exams."),
              ("The Texas Department of Insurance directly", False, "Texas contracts with Pearson VUE for exam administration.")]),
            ("The Texas Windstorm Insurance Association (TWIA) provides:",
             "multiple_choice", "standard",
             "TWIA is Texas's insurer of last resort for windstorm and hail coverage for properties in designated coastal counties that cannot obtain coverage in the voluntary market. It is a key Texas-specific topic.",
             [("Windstorm and hail coverage for coastal Texas properties unable to obtain voluntary market coverage", True, "Correct. TWIA is the insurer of last resort for windstorm coverage in designated Texas coastal counties."),
              ("Auto insurance for all Texas coastal residents", False, "TWIA covers windstorm and hail on property, not auto insurance."),
              ("Free flood insurance for all Texas property owners", False, "TWIA covers windstorm and hail; flood coverage is provided through the NFIP."),
              ("Life insurance for Texas emergency responders", False, "TWIA provides windstorm and hail property coverage, not life insurance.")]),
            ("Under Texas insurance law, the Texas Department of Insurance (TDI) is headed by the:",
             "multiple_choice", "standard",
             "The Texas Department of Insurance is headed by the Commissioner of Insurance, who is appointed by the Governor — not elected.",
             [("Commissioner of Insurance, appointed by the Governor", True, "Correct. Texas's insurance regulator is the Commissioner of Insurance, appointed by the Governor."),
              ("Commissioner of Insurance, elected by Texas voters", False, "Texas's Commissioner is appointed, not elected. California is the main example of an elected Commissioner."),
              ("Director of Insurance", False, "Texas uses Commissioner, not Director."),
              ("Superintendent of Insurance", False, "Texas uses Commissioner, not Superintendent.")]),
            ("Texas's best-interest standard for life insurance and annuity recommendations requires producers to:",
             "multiple_choice", "standard",
             "Texas has adopted a best-interest standard for life insurance and annuity recommendations, requiring producers to prioritize the client's interests over their own financial interests when making recommendations.",
             [("Put the client's interests first when recommending any life insurance or annuity product", True, "Correct. Texas's best-interest standard requires producers to prioritize client interests in life and annuity recommendations."),
              ("Only recommend products from the top five Texas insurers by market share", False, "Best interest requires recommending the most suitable product for the client, not limiting recommendations by market share."),
              ("Obtain TDI approval before completing each life insurance sale", False, "Individual TDI approval is not required for individual sales."),
              ("Recommend only whole life insurance — term policies do not meet the best-interest standard", False, "Best interest requires the product that best meets the client's specific needs; term insurance can meet the best-interest standard.")]),
            ("The Texas Life, Accident, Health, and Hospital Service Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Texas guaranty association for life, health, and annuity products protects Texas policyholders when a licensed Texas insurer becomes insolvent, paying claims up to statutory limits.",
             [("Protects Texas life and health policyholders when a licensed insurer becomes insolvent", True, "Correct. The Texas L&H guaranty association covers claims from licensed insurer insolvencies up to statutory limits."),
              ("Provides free health insurance to uninsured Texans", False, "The guaranty association is an insolvency protection mechanism, not an insurance provider."),
              ("Sets premium rates for all Texas life and health insurance products", False, "Rate regulation is the TDI's function."),
              ("Only covers claims from Texas-domiciled insurance companies", False, "The guaranty association covers claims from any licensed admitted Texas insurer.")]),
        ],
        "UT": [
            ("In Utah, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Utah uses Prometric to administer its insurance licensing examinations.",
             [("Prometric at approved testing centers", True, "Correct. Utah uses Prometric as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Utah insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Utah insurance exams."),
              ("The Utah Insurance Department directly", False, "Utah contracts with Prometric for exam administration.")]),
            ("In Utah, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "Utah's insurance regulator holds the title of Commissioner of Insurance.",
             [("Commissioner of Insurance", True, "Correct. Utah's insurance regulator is the Commissioner of Insurance."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not Utah."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York, not Utah."),
              ("Secretary of Insurance", False, "Secretary is not the title used in Utah.")]),
            ("Under Utah law, which of the following requires a producer to have a specific license endorsement?",
             "multiple_choice", "standard",
             "Utah requires specific licensing for certain activities including adjuster licensing, title insurance, and other specialized lines beyond the standard producer license.",
             [("Adjusting property and casualty insurance claims requires an adjuster license", True, "Correct. Utah requires a separate adjuster license for claims adjusting activities."),
              ("Explaining policy terms to clients requires a consultant endorsement", False, "Explaining policy terms is a standard producer activity, not requiring a separate endorsement."),
              ("Accepting premium payments requires a separate premium finance license", False, "Accepting premiums is a standard producer activity included in the regular license."),
              ("Recommending any insurance product requires a financial advisor license", False, "A financial advisor license is not required to recommend insurance products.")]),
            ("Utah's adjuster licensing qualifications require candidates to:",
             "multiple_choice", "standard",
             "Utah requires adjusters to meet specific qualifications including passing an exam, completing required education, and meeting background requirements. Utah specifically tests adjuster licensing rules.",
             [("Pass the adjuster examination and meet background and education requirements", True, "Correct. Utah requires adjusters to pass the exam and meet background and education requirements."),
              ("Hold a current attorney's license in addition to the adjuster exam", False, "An attorney's license is not required for adjusters in Utah."),
              ("Complete at least 5 years of claims experience before licensing", False, "5 years of prior experience is not a Utah adjuster licensing prerequisite."),
              ("Be employed by an insurance company — independent adjusters cannot be licensed", False, "Both staff adjusters (employed by insurers) and independent adjusters can be licensed in Utah.")]),
            ("The Utah Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Utah Life and Health Insurance Guaranty Association protects Utah policyholders when a licensed Utah life, health, or annuity insurer becomes insolvent.",
             [("Protects Utah policyholders when a licensed Utah insurer becomes insolvent", True, "Correct. The Utah guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides free health insurance to low-income Utah residents", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets rate maximums for Utah life insurance products", False, "Rate regulation is the Commissioner's function."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
        ],
        "VT": [
            ("In Vermont, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Vermont uses Prometric to administer its insurance licensing examinations.",
             [("Prometric at approved testing centers", True, "Correct. Vermont uses Prometric as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Vermont insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Vermont insurance exams."),
              ("The Vermont Department of Financial Regulation directly", False, "Vermont contracts with Prometric for exam administration.")]),
            ("In Vermont, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Vermont's insurance is regulated by the Department of Financial Regulation (DFR), which also oversees banking and securities.",
             [("Department of Financial Regulation (DFR)", True, "Correct. Vermont's insurance, banking, and securities are regulated by the DFR."),
              ("Department of Commerce and Insurance", False, "This is Tennessee's structure, not Vermont's."),
              ("Division of Insurance", False, "Vermont uses the DFR, not a standalone Division of Insurance."),
              ("Office of the Insurance Commissioner", False, "Vermont uses the DFR structure rather than a standalone Commissioner's office.")]),
            ("Vermont's FAIR Plan provides:",
             "multiple_choice", "standard",
             "Vermont's FAIR (Fair Access to Insurance Requirements) Plan provides basic property insurance to property owners who cannot obtain coverage in the voluntary market.",
             [("Basic property insurance to owners who cannot obtain voluntary market coverage", True, "Correct. Vermont's FAIR Plan provides basic property coverage as a last resort."),
              ("Comprehensive auto insurance to high-risk Vermont drivers", False, "FAIR Plans cover property insurance; auto has separate assigned risk mechanisms."),
              ("Free renters insurance to low-income Vermont residents", False, "FAIR Plans are not free insurance programs."),
              ("Full HO-3 equivalent coverage for all Vermont homeowners", False, "FAIR Plans provide more limited basic coverage, not comprehensive homeowners policies.")]),
            ("The Vermont Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Vermont Life and Health Insurance Guaranty Association protects Vermont policyholders when a licensed Vermont life, health, or annuity insurer becomes insolvent.",
             [("Protects Vermont policyholders when a licensed Vermont insurer becomes insolvent", True, "Correct. The Vermont guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides subsidized health insurance to Vermont small business owners", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets maximum premium rates for Vermont health insurance", False, "Rate regulation is the DFR's function."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Under Vermont insurance law, a producer must comply with federal statute 18 USC 1033, which:",
             "multiple_choice", "standard",
             "18 USC 1033 is the federal insurance fraud statute that prohibits persons convicted of crimes involving dishonesty or breach of trust from engaging in the insurance business without written regulatory consent.",
             [("Prohibits persons convicted of felonies involving dishonesty from engaging in insurance without regulatory consent", True, "Correct. 18 USC 1033 prohibits certain convicted persons from the insurance business without written consent from the state regulator."),
              ("Requires all insurance policies to include a federal disclosure statement", False, "18 USC 1033 is the federal insurance fraud statute, not a policy disclosure requirement."),
              ("Mandates that all insurance advertising be reviewed by federal regulators", False, "18 USC 1033 addresses insurance fraud; advertising review is a state function."),
              ("Sets minimum coverage requirements for all Vermont insurance policies", False, "18 USC 1033 is a criminal statute addressing insurance fraud; it does not set coverage minimums.")]),
        ],
        "VA": [
            ("In Virginia, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Virginia uses Prometric to administer its insurance licensing examinations.",
             [("Prometric at approved testing centers", True, "Correct. Virginia uses Prometric as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Virginia insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Virginia insurance exams."),
              ("The Virginia Bureau of Insurance directly", False, "Virginia contracts with Prometric for exam administration.")]),
            ("In Virginia, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Virginia's insurance is regulated by the Bureau of Insurance, which is part of the State Corporation Commission (SCC).",
             [("Bureau of Insurance, part of the State Corporation Commission (SCC)", True, "Correct. Virginia's Bureau of Insurance is part of the SCC, a unique regulatory structure."),
              ("Department of Insurance and Financial Services", False, "This is Michigan's structure, not Virginia's."),
              ("Division of Insurance", False, "Virginia uses the Bureau of Insurance within the SCC."),
              ("Office of Insurance Regulation", False, "OIR is part of Florida's structure; Virginia uses the Bureau of Insurance within the SCC.")]),
            ("Virginia's insurance producers can hold which of the following license types?",
             "multiple_choice", "standard",
             "Virginia's insurance code recognizes several types of licensees including agents, brokers, consultants, and viatical settlement brokers — each with specific licensing requirements.",
             [("Agent, broker, consultant, and viatical settlement broker licenses", True, "Correct. Virginia recognizes multiple producer license types including agents, brokers, consultants, and viatical settlement brokers."),
              ("Only one type — a universal producer license covering all roles", False, "Virginia has distinct license types for different producer roles."),
              ("Only agent and broker licenses — consultants are not licensed in Virginia", False, "Virginia does license insurance consultants as a distinct category."),
              ("Federal licenses that supersede Virginia state licensing requirements", False, "Virginia requires state licensure; there are no federal insurance producer licenses.")]),
            ("The Virginia Life, Accident and Sickness Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Virginia Life, Accident and Sickness Insurance Guaranty Association protects Virginia policyholders when a licensed Virginia life, health, or annuity insurer becomes insolvent.",
             [("Protects Virginia policyholders when a licensed Virginia insurer becomes insolvent", True, "Correct. The Virginia guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides free life insurance to Virginia military veterans", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets maximum rates for Virginia life insurance products", False, "Rate regulation is the Bureau of Insurance's function."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Under Virginia law, an insurance consultant is defined as a person who:",
             "multiple_choice", "standard",
             "A Virginia insurance consultant is licensed to provide advice and counsel about insurance for a fee, as distinguished from agents or brokers who sell insurance. Consultants must hold a separate consultant license.",
             [("Provides advice and counsel about insurance for compensation but does not sell insurance", True, "Correct. Virginia insurance consultants provide fee-based advice and do not sell insurance — they hold a distinct license from agents and brokers."),
              ("Can sell all lines of insurance plus provide advice for a fee", False, "A consultant provides advice only; selling requires an agent or broker license."),
              ("Only advises commercial clients about risk management programs", False, "Virginia consultants can advise any type of client."),
              ("Holds a combination agent-consultant license issued by the SCC", False, "Consultant is a distinct license type, not a combination with an agent license.")]),
        ],
        "WA": [
            ("In Washington, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Washington uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Washington uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Washington insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Washington insurance exams."),
              ("The Washington Office of the Insurance Commissioner directly", False, "Washington contracts with PSI for exam administration.")]),
            ("In Washington, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "Washington's insurance regulator is the Insurance Commissioner, who is elected by Washington voters.",
             [("Insurance Commissioner, elected by Washington voters", True, "Correct. Washington's Insurance Commissioner is elected by voters."),
              ("Insurance Commissioner, appointed by the Governor", False, "Washington's Commissioner is elected, not appointed."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not Washington."),
              ("Superintendent of Financial Services", False, "Superintendent of Financial Services is New York's title; Washington uses Commissioner.")]),
            ("Washington's disclosure of compensation rules require producers to:",
             "multiple_choice", "standard",
             "Washington requires producers to disclose compensation arrangements that may create conflicts of interest, ensuring clients understand how producers are paid.",
             [("Disclose compensation arrangements that may create a conflict of interest", True, "Correct. Washington requires compensation disclosure when potential conflicts exist."),
              ("Disclose every dollar of compensation on every transaction regardless of conflict", False, "Washington's requirement focuses on conflicts of interest, not universal transaction-by-transaction disclosure."),
              ("Keep compensation arrangements strictly confidential", False, "Washington requires disclosure when conflicts exist; compensation is not confidential."),
              ("Only disclose compensation if the client specifically asks", False, "Washington requires proactive disclosure when conflicts exist, not only on client request.")]),
            ("The Washington Life and Disability Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Washington Life and Disability Insurance Guaranty Association protects Washington policyholders when a licensed Washington life, health, or annuity insurer becomes insolvent.",
             [("Protects Washington policyholders when a licensed WA insurer becomes insolvent", True, "Correct. The Washington guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides subsidized insurance to Washington small businesses", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets rate caps for Washington health insurance products", False, "Rate regulation is the Commissioner's function."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Under Washington law, replacement rules for annuities require producers to:",
             "multiple_choice", "standard",
             "Washington's replacement rules for annuities require specific disclosures and notifications when an existing annuity is being replaced, protecting consumers from uninformed replacement decisions.",
             [("Provide comparison disclosures and notify the existing insurer when replacing an annuity", True, "Correct. Washington's replacement rules require comparison disclosures and notification for annuity replacements."),
              ("Obtain the client's attorney's approval before completing an annuity replacement", False, "Attorney approval is not a replacement regulation requirement."),
              ("Only complete annuity replacements during open enrollment periods", False, "Annuity replacements are not limited to open enrollment periods."),
              ("Guarantee that the new annuity will outperform the replaced contract", False, "Guaranteeing performance would be misrepresentation; replacement rules require disclosure, not guarantees.")]),
        ],
        "WV": [
            ("In West Virginia, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "West Virginia uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. West Virginia uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer West Virginia insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer West Virginia insurance exams."),
              ("The West Virginia Offices of the Insurance Commissioner directly", False, "West Virginia contracts with Pearson VUE for exam administration.")]),
            ("In West Virginia, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "West Virginia's insurance regulator holds the title of Insurance Commissioner.",
             [("Insurance Commissioner", True, "Correct. West Virginia's insurance regulator is the Insurance Commissioner."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not West Virginia."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York and other states, not West Virginia."),
              ("Secretary of Financial Services", False, "This is not the title for West Virginia's insurance regulator.")]),
            ("Under West Virginia insurance law, unfair trade practices include all of the following EXCEPT:",
             "multiple_choice", "standard",
             "West Virginia's Unfair Trade Practices Act prohibits misrepresentation, rebating, twisting, defamation, and unfair discrimination. Recommending a competitor's product based on superior terms is not a prohibited practice.",
             [("Recommending a competitor's product because it offers genuinely better terms", True, "Correct. Recommending a competitor's product for legitimate reasons is not an unfair trade practice — it can reflect proper suitability analysis."),
              ("Misrepresenting the terms and benefits of a policy", False, "Misrepresentation IS an unfair trade practice prohibited in West Virginia."),
              ("Rebating by giving clients gifts as inducements to purchase insurance", False, "Rebating IS an unfair trade practice prohibited in West Virginia."),
              ("Using intimidation to prevent a client from shopping other insurers", False, "Coercion and intimidation ARE unfair trade practices prohibited in West Virginia.")]),
            ("The West Virginia Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The West Virginia Life and Health Insurance Guaranty Association protects West Virginia policyholders when a licensed West Virginia life, health, or annuity insurer becomes insolvent.",
             [("Protects WV policyholders when a licensed WV insurer becomes insolvent", True, "Correct. The West Virginia guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides free insurance to West Virginia coal miners", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets maximum rates for West Virginia health insurance", False, "Rate regulation is the Commissioner's function."),
              ("Covers claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("West Virginia's disclosure requirements for annuity suitability require producers to:",
             "multiple_choice", "standard",
             "West Virginia has adopted annuity suitability standards requiring producers to gather client financial information and act in the client's best interest when recommending annuities.",
             [("Gather client financial information and act in the client's best interest when recommending annuities", True, "Correct. West Virginia's suitability standards require financial information gathering and best-interest conduct."),
              ("Recommend only fixed annuities to West Virginia residents", False, "Suitability requires appropriate product matching, not defaulting to fixed annuities."),
              ("Obtain the Insurance Commissioner's approval for each annuity recommendation", False, "Individual Commissioner approval is not required."),
              ("Only recommend annuities to clients with household income over $75,000", False, "Suitability standards apply to all recommendations regardless of income level.")]),
        ],
        "WI": [
            ("In Wisconsin, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Wisconsin uses Prometric to administer its insurance licensing examinations.",
             [("Prometric at approved testing centers", True, "Correct. Wisconsin uses Prometric as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Wisconsin insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Wisconsin insurance exams."),
              ("The Wisconsin Office of the Commissioner of Insurance directly", False, "Wisconsin contracts with Prometric for exam administration.")]),
            ("The Wisconsin Insurance Security Fund protects policyholders by:",
             "multiple_choice", "standard",
             "The Wisconsin Insurance Security Fund protects Wisconsin policyholders when a licensed Wisconsin insurer becomes insolvent, covering both property/casualty and life/health claims through separate accounts.",
             [("Paying claims when a licensed Wisconsin insurer becomes insolvent", True, "Correct. The Wisconsin Insurance Security Fund covers claims from licensed insurer insolvencies."),
              ("Providing premium subsidies to Wisconsin small businesses", False, "The Security Fund is an insolvency protection mechanism."),
              ("Setting rate caps for all Wisconsin insurance products", False, "Rate regulation is the Commissioner's function."),
              ("Covering claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Under Wisconsin insurance law, producer regulation includes requirements for:",
             "multiple_choice", "standard",
             "Wisconsin regulates producers through licensing requirements, continuing education, and market conduct rules including prohibitions on rebating, twisting, misrepresentation, and defamation.",
             [("Licensing, continuing education, and compliance with market conduct rules", True, "Correct. Wisconsin regulates producers through licensing, CE, and market conduct requirements."),
              ("Only licensing — CE and market conduct are voluntary in Wisconsin", False, "CE and market conduct compliance are mandatory in Wisconsin."),
              ("Federal licensing that supersedes Wisconsin state requirements", False, "Wisconsin requires state licensure; there are no federal insurance producer licenses that supersede state requirements."),
              ("Membership in the Wisconsin Insurance Association as a condition of licensure", False, "Association membership is not a Wisconsin licensing requirement.")]),
            ("Wisconsin's unfair claims practices act prohibits:",
             "multiple_choice", "standard",
             "Wisconsin's unfair claims practices act prohibits a range of unfair claims handling behaviors including misrepresenting policy provisions, failing to acknowledge claims, and refusing to pay valid claims.",
             [("Misrepresenting policy provisions relevant to a claim and refusing to pay valid claims", True, "Correct. Wisconsin's unfair claims practices act prohibits these and other unfair claims handling behaviors."),
              ("Paying claims faster than 30 days after they are filed", False, "Prompt payment is not prohibited; the Act prohibits unfair delays and denials."),
              ("Using independent adjusters to evaluate claims", False, "Using independent adjusters is a standard industry practice, not prohibited."),
              ("Requiring itemized proof of loss documentation from claimants", False, "Requiring proof of loss is standard and permissible; the Act prohibits unreasonable documentation requirements.")]),
            ("Wisconsin's continuing education requirements for licensed producers include:",
             "multiple_choice", "standard",
             "Wisconsin requires licensed producers to complete continuing education hours each renewal cycle, including a required ethics component, as a condition of license renewal.",
             [("A specified number of hours per renewal cycle including an ethics component", True, "Correct. Wisconsin requires CE hours per renewal cycle with a mandatory ethics component."),
              ("Only technical product training — ethics CE is optional in Wisconsin", False, "Ethics is a mandatory component of Wisconsin CE requirements."),
              ("CE only for producers who had complaints filed against them", False, "CE is mandatory for all Wisconsin producers regardless of complaint history."),
              ("100 hours of CE annually for all licensed producers", False, "100 hours annually is far above Wisconsin's actual CE requirement.")]),
        ],
        "WY": [
            ("In Wyoming, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Wyoming uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Wyoming uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Wyoming insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Wyoming insurance exams."),
              ("The Wyoming Insurance Department directly", False, "Wyoming contracts with Pearson VUE for exam administration.")]),
            ("In Wyoming, the insurance Commissioner is:",
             "multiple_choice", "standard",
             "Wyoming's Insurance Commissioner is appointed by the Governor.",
             [("Appointed by the Governor", True, "Correct. Wyoming's Insurance Commissioner is appointed by the Governor."),
              ("Elected by Wyoming voters statewide", False, "Wyoming's Commissioner is appointed, not elected."),
              ("Selected by the Wyoming state legislature", False, "The legislature does not select Wyoming's Commissioner."),
              ("Appointed by the Wyoming Supreme Court", False, "The Supreme Court has no role in selecting Wyoming's Commissioner.")]),
            ("The Wyoming Insurance Guaranty Association and Wyoming Life and Health Insurance Guaranty Association together:",
             "multiple_choice", "standard",
             "Wyoming has separate guaranty associations for P&C and life/health, providing protection for Wyoming policyholders when a licensed Wyoming insurer becomes insolvent.",
             [("Protect Wyoming policyholders from both P&C and life/health insurer insolvencies", True, "Correct. Wyoming's two guaranty associations cover both P&C and life/health insolvency protection."),
              ("Provide free insurance to Wyoming ranchers and farmers", False, "The guaranty associations are insolvency protection mechanisms."),
              ("Set premium rates for all Wyoming insurance products", False, "Rate regulation is the Commissioner's function."),
              ("Cover claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Wyoming's FAIR Plan provides:",
             "multiple_choice", "standard",
             "Wyoming's FAIR (Fair Access to Insurance Requirements) Plan provides basic property insurance to property owners unable to obtain coverage in the voluntary market.",
             [("Basic property insurance to owners unable to obtain voluntary market coverage", True, "Correct. Wyoming's FAIR Plan is the last-resort insurer for basic property coverage."),
              ("Comprehensive auto insurance to high-risk Wyoming drivers", False, "FAIR Plans cover property insurance; auto has separate assigned risk mechanisms."),
              ("Free homeowners insurance to Wyoming ranches and farms", False, "FAIR Plans are not free insurance programs."),
              ("Full replacement cost coverage for all Wyoming homeowners", False, "FAIR Plans provide basic coverage, not full replacement cost coverage.")]),
            ("Under Wyoming law, a producer's license will lapse if the producer:",
             "multiple_choice", "standard",
             "Wyoming insurance licenses lapse if producers fail to meet renewal requirements including paying renewal fees and completing required continuing education hours within the renewal period.",
             [("Fails to complete required CE hours or pay renewal fees by the renewal deadline", True, "Correct. Wyoming licenses lapse for failure to meet CE or fee payment requirements by the renewal deadline."),
              ("Fails to write a minimum amount of new business each year", False, "Minimum production requirements are not a Wyoming licensing condition."),
              ("Changes their primary insurer appointment", False, "Changing insurer appointments does not cause a license to lapse."),
              ("Moves their office to a different Wyoming county", False, "Moving within Wyoming does not cause a license to lapse; address notification is required.")]),
        ],
        "DC": [
            ("In the District of Columbia, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "The District of Columbia uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. The District of Columbia uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer DC insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer DC insurance exams."),
              ("The DC Department of Insurance, Securities and Banking directly", False, "DC contracts with Pearson VUE for exam administration.")]),
            ("The DC Department of Insurance, Securities and Banking (DISB) regulates:",
             "multiple_choice", "standard",
             "DC's DISB is a combined regulatory agency that oversees insurance, securities, and banking within the District — a broader mandate than most state insurance departments.",
             [("Insurance, securities, and banking within the District of Columbia", True, "Correct. DC's DISB has a combined mandate covering insurance, securities, and banking."),
              ("Only insurance — securities and banking are federally regulated in DC", False, "DISB regulates all three: insurance, securities, and banking."),
              ("Only life and health insurance — P&C is regulated by a separate agency", False, "DISB regulates all lines of insurance in the District."),
              ("Only insurance companies — producers are regulated by a separate DC agency", False, "DISB regulates both insurance companies and producers.")]),
            ("Under DC law, an insurance producer's fiduciary duties include:",
             "multiple_choice", "standard",
             "DC insurance producers owe fiduciary duties to their clients including holding premiums separately, acting in the client's best interest, and maintaining loyalty and candor in their dealings.",
             [("Holding premiums separately, acting in the client's best interest, and maintaining candor", True, "Correct. DC producers have fiduciary duties including premium handling, client advocacy, and honest dealings."),
              ("Only following insurer instructions regardless of client impact", False, "Fiduciary duty requires prioritizing the client's interests, not just following insurer instructions."),
              ("No fiduciary duties — producers represent the insurer only", False, "DC producers owe duties to both their clients and their insurers."),
              ("Maximizing commissions earned on every transaction", False, "Maximizing commission at the expense of client interests would violate fiduciary duty.")]),
            ("DC's prohibition on AIDS/HIV discrimination in insurance means:",
             "multiple_choice", "standard",
             "DC has strong anti-discrimination protections for HIV/AIDS status in insurance. Insurers cannot use HIV status alone as a basis for denying coverage or charging discriminatory rates.",
             [("Insurers cannot use HIV status alone as a basis for denying coverage or discriminatory rating", True, "Correct. DC's HIV anti-discrimination rules restrict insurers from discriminating based solely on HIV status."),
              ("All DC insurance applicants must disclose their HIV status on every application", False, "DC restricts how HIV information can be used; mandatory disclosure rules are separate."),
              ("HIV-positive applicants are automatically approved for all lines of coverage", False, "Anti-discrimination rules restrict discriminatory use of HIV status; they do not require automatic approval."),
              ("Producers must personally counsel all applicants about HIV testing", False, "Producers are not required to provide health counseling to insurance applicants.")]),
            ("The DC Life and Health Insurance Guaranty Association covers claims when:",
             "multiple_choice", "standard",
             "The DC Life and Health Insurance Guaranty Association protects DC policyholders when a licensed DC insurer becomes insolvent, paying covered claims up to statutory limits.",
             [("A licensed DC insurer is declared insolvent", True, "Correct. The DC guaranty association covers claims from licensed insurer insolvencies."),
              ("A claim is denied by any insurer operating in DC", False, "The guaranty association only covers insolvency situations."),
              ("A policyholder moves out of DC while the policy is in force", False, "Moving out of DC does not trigger guaranty association coverage."),
              ("A producer fails to remit premiums to the insurer", False, "Producer misconduct is addressed through DISB enforcement, not the guaranty association.")]),
        ],
    }
    return specifics.get(state_abbr, [
        (f"The insurance licensing exam in {state_abbr} tests candidates on:",
         "multiple_choice", "standard",
         "State insurance licensing exams test both national product knowledge and state-specific insurance laws.",
         [("Both national insurance concepts and state-specific laws and regulations", True, "Correct. All state exams include both a national general knowledge section and a state law supplement."),
          ("Only national concepts with no state-specific content", False, "All state exams include a state law supplement."),
          ("Only state laws with no national content", False, "All state exams include a national general knowledge portion."),
          ("Only mathematical calculations related to insurance pricing", False, "Insurance exams cover concepts, regulations, and policy provisions.")]),
    ] * 5)


STATES_PART4 = [
    ("SD", "South Dakota", "Director of Insurance",
     "South Dakota Life and Health Insurance Guaranty Association", 24),
    ("TN", "Tennessee", "Commissioner of Commerce and Insurance",
     "Tennessee Life and Health Insurance Guaranty Association", 24),
    ("TX", "Texas", "Commissioner of Insurance",
     "Texas Life, Accident, Health and Hospital Service Insurance Guaranty Association", 24),
    ("UT", "Utah", "Commissioner of Insurance",
     "Utah Life and Health Insurance Guaranty Association", 24),
    ("VT", "Vermont", "Commissioner of Financial Regulation",
     "Vermont Life and Health Insurance Guaranty Association", 24),
    ("VA", "Virginia", "Commissioner of Insurance",
     "Virginia Life, Accident and Sickness Insurance Guaranty Association", 24),
    ("WA", "Washington", "Insurance Commissioner",
     "Washington Life and Disability Insurance Guaranty Association", 24),
    ("WV", "West Virginia", "Insurance Commissioner",
     "West Virginia Life and Health Insurance Guaranty Association", 24),
    ("WI", "Wisconsin", "Commissioner of Insurance",
     "Wisconsin Insurance Security Fund", 24),
    ("WY", "Wyoming", "Insurance Commissioner",
     "Wyoming Life and Health Insurance Guaranty Association", 24),
    ("DC", "District of Columbia", "Commissioner of the Department of Insurance Securities and Banking",
     "DC Life and Health Insurance Guaranty Association", 24),
]

COURSES = [("pc", "P&C"), ("lh", "L&H")]


def seed():
    create_all()
    db = SessionLocal()
    try:
        total_mods = total_q = 0

        for (abbr, name, regulator, guaranty, ce_hours) in STATES_PART4:
            for (course_code, course_label) in COURSES:
                mod_slug = f"state-law-{abbr.lower()}-{course_code}"

                existing = db.scalar(
                    select(Module).where(Module.slug == mod_slug))
                if existing:
                    print(f"  SKIP (exists): {mod_slug}")
                    continue

                idx = STATES_PART4.index(
                    (abbr, name, regulator, guaranty, ce_hours))
                mod = Module(
                    slug=mod_slug,
                    title=f"{name} State Law — {course_label}",
                    description=(
                        f"State-specific insurance laws for the {name} "
                        f"{course_label} licensing exam. Covers the {regulator}, "
                        f"licensing, unfair trade practices, guaranty association, "
                        f"and state-specific rules."
                    ),
                    sort_order=900 + idx * 10 + (0 if course_code == "pc" else 1),
                    is_active=True,
                )
                db.add(mod)
                db.flush()
                db.execute(
                    text("UPDATE modules SET course=:c WHERE id=:id"),
                    {"c": course_code, "id": mod.id})
                total_mods += 1
                print(f"  MODULE: {mod.title}")

                all_questions = (
                    build_universal_questions(
                        name, regulator, guaranty, ce_hours, course_label) +
                    build_semi_universal(
                        name, regulator, guaranty, ce_hours, course_label) +
                    build_state_specific(abbr)
                )

                for (q_text, q_type, difficulty,
                     explanation, choices) in all_questions:
                    q = Question(
                        module_id=mod.id,
                        lesson_id=None,
                        question_text=q_text,
                        question_type=q_type,
                        difficulty=difficulty,
                        explanation=explanation,
                        is_active=True,
                    )
                    db.add(q)
                    db.flush()
                    for sort_i, (ct, correct, ce) in enumerate(choices, 1):
                        db.add(AnswerChoice(
                            question_id=q.id,
                            choice_text=ct,
                            is_correct=correct,
                            explanation=ce,
                            sort_order=sort_i,
                        ))
                    total_q += 1

        db.commit()
        print(f"\n=== Part 4 complete: {total_mods} modules, "
              f"{total_q} questions ===")
        print("States: SD TN TX UT VT VA WA WV WI WY DC")
        print("All 51 jurisdictions now seeded across Parts 1-4.")
        print(f"Grand total: 102 modules, ~2550 questions")

    finally:
        db.close()


if __name__ == "__main__":
    seed()
