#!/usr/bin/env python3
"""
state_law_seed_part3.py — State Law Questions, Part 3
States: Nebraska, Nevada, New Hampshire, New Jersey, New Mexico,
        New York, North Carolina, North Dakota, Ohio, Oklahoma,
        Oregon, Pennsylvania, Rhode Island, South Carolina
Both P&C (course='pc') and L&H (course='lh') modules per state.
25 questions per module (14 universal + 6 semi-universal + 5 state-specific).

Run from pc-license-prep-server-v2/:
    .venv/bin/python3 scripts/state_law_seed_part3.py
"""
import sys, os
sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from sqlalchemy import select, text
from app.database import SessionLocal, create_all
from app.models import Module, Lesson, Term, Question, AnswerChoice


def build_universal_questions(state_name, regulator_title, guaranty_name,
                               ce_hours, course_label):
    reg = regulator_title
    guar = guaranty_name
    st = state_name
    return [
        (f"Who is primarily responsible for regulating the insurance industry in {st}?",
         "multiple_choice", "standard",
         f"The {reg} is the chief insurance regulator in {st}.",
         [(f"The {reg}", True, f"Correct. The {reg} has broad authority to regulate insurance in {st}."),
          ("The federal Department of Insurance", False, "There is no federal Department of Insurance."),
          ("The NAIC", False, "The NAIC is a standard-setting body without direct regulatory authority."),
          ("The state attorney general", False, "The insurance regulator has primary jurisdiction over insurance.")]),

        (f"Under {st} law, which of the following is misrepresentation by an insurance producer?",
         "multiple_choice", "standard",
         "Misrepresentation includes making false or misleading statements about policy terms or benefits.",
         [("Telling a client a policy covers losses it does not cover", True, "Correct. Making false statements about coverage is misrepresentation."),
          ("Explaining differences between two competing policies accurately", False, "Accurate explanations are legitimate sales practice."),
          ("Recommending a policy based on the client's financial needs", False, "Recommending suitable coverage is proper producer duty."),
          ("Delivering a policy within the time required by state law", False, "Timely delivery is an obligation, not a prohibited practice.")]),

        (f"In {st}, rebating is best defined as:",
         "multiple_choice", "standard",
         "Rebating is offering or giving any valuable consideration as an inducement to purchase insurance.",
         [("Offering anything of value as an inducement to purchase insurance", True, "Correct. Rebating is giving valuable consideration to induce an insurance purchase."),
          ("Charging more than the filed premium rate", False, "Overcharging is not rebating."),
          ("Replacing one policy with another without the client's consent", False, "Replacement through misrepresentation is twisting."),
          ("Splitting commissions with another licensed producer", False, "Commission sharing between licensed producers is generally permitted.")]),

        (f"A producer in {st} who uses misrepresentation to induce a policyholder to cancel an existing policy and buy a new one is guilty of:",
         "multiple_choice", "standard",
         "Twisting is using misrepresentation to induce a policyholder to replace an existing policy.",
         [("Twisting", True, "Correct. Using misrepresentation to induce policy replacement is twisting."),
          ("Rebating", False, "Rebating involves giving value as an inducement, not misrepresentation to replace."),
          ("Defamation", False, "Defamation is making false statements about another insurer or producer."),
          ("Churning", False, "Churning is replacement within the same company primarily for commission.")]),

        (f"Under {st} insurance law, a producer's license may be suspended or revoked for:",
         "multiple_choice", "standard",
         "Misappropriation of client premiums is grounds for license suspension or revocation.",
         [("Misappropriating client premium funds", True, "Correct. Misappropriating premiums is a serious fiduciary violation and grounds for license action."),
          ("Failing the licensing exam on the first attempt", False, "Failing an exam is not grounds for license discipline."),
          ("Selling only one type of insurance product", False, "Specializing is not a violation."),
          ("Recommending a competitor's product to a client", False, "Recommending competitors is not prohibited.")]),

        (f"In {st}, when a licensed producer collects a premium payment from a client, those funds are:",
         "multiple_choice", "standard",
         "Premium funds are fiduciary property that must be held separately from the producer's own money.",
         [("Fiduciary funds that must be held separately from the producer's own money", True, "Correct. Collected premiums are fiduciary funds that must not be commingled."),
          ("The producer's personal income until transmitted to the insurer", False, "Premiums are never the producer's personal income."),
          ("Subject to a producer's lien until commissions are deducted", False, "Producers cannot retain premiums as a lien."),
          ("Unclaimed until the policy is formally issued", False, "Premiums must be held as fiduciary property immediately upon collection.")]),

        (f"The purpose of {st}'s insurance guaranty association is to:",
         "multiple_choice", "standard",
         f"The {guar} protects policyholders when a licensed insurer becomes insolvent.",
         [("Pay covered claims when a licensed insurer becomes insolvent", True, f"Correct. The {guar} pays covered claims when a licensed insurer is insolvent."),
          ("Regulate insurance rates to keep premiums affordable", False, "Rate regulation is the regulator's function."),
          ("Provide reinsurance to small insurance companies", False, "Reinsurance is a private market function."),
          ("Manage the state's high-risk insurance pool", False, "High-risk pools are separate mechanisms.")]),

        (f"Under {st} law, when a producer wants to replace a client's existing life policy with a new one, the producer must:",
         "multiple_choice", "standard",
         "Replacement regulations require written comparison disclosures and notification to the existing insurer.",
         [("Provide a written comparison disclosure and notify the existing insurer", True, "Correct. Replacement requires comparison disclosures and notification to the existing insurer."),
          ("Obtain written approval from the state insurance department", False, "State approval is not required for individual replacements."),
          ("Cancel the existing policy before placing the new policy", False, "The new policy should be in place before cancelling the existing one."),
          ("Charge no commission on the replacement policy", False, "Commission restrictions are not a standard replacement requirement.")]),

        (f"In {st}, a nonresident producer licensed in another state generally:",
         "multiple_choice", "standard",
         "Most states grant nonresident licenses by reciprocity without a separate exam requirement.",
         [("May be issued a nonresident license without a state exam if their home state offers reciprocity", True, "Correct. Reciprocity allows nonresident producers to skip the exam if their home state is reciprocal."),
          ("Must take and pass the full state licensing exam regardless of home state license", False, "Most states waive the exam for reciprocal nonresident applicants."),
          ("Must establish a business office in the state before receiving a license", False, "Nonresident producers are not required to maintain a physical office."),
          ("Is exempt from all continuing education requirements in the nonresident state", False, "CE may still be required for nonresident producers.")]),

        (f"In {st}, which of the following constitutes coercion in the sale of insurance?",
         "multiple_choice", "standard",
         "Coercion is using threats or economic pressure to compel someone to purchase insurance.",
         [("Threatening to cancel a client's business contract unless they purchase insurance through you", True, "Correct. Economic threats to compel an insurance purchase is coercion — a prohibited unfair trade practice."),
          ("Recommending a specific insurer based on financial strength ratings", False, "Recommending based on objective criteria is legitimate."),
          ("Explaining the penalties for driving without required auto insurance", False, "Explaining legal requirements is not coercion."),
          ("Offering a client a choice between two policy options", False, "Offering choices is standard sales practice.")]),

        (f"A {st} insurance producer's license must be renewed every:",
         "multiple_choice", "standard",
         "Most states require license renewal every two years with continuing education.",
         [("Two years, with continuing education requirements", True, f"Correct. Most states including {st} require biennial renewal with CE."),
          ("One year, without any continuing education requirement", False, "Annual renewal without CE is not the standard."),
          ("Five years, with no exam required at renewal", False, "5-year renewal cycles are not standard."),
          ("There is no renewal requirement once a license is issued", False, "All state licenses require periodic renewal.")]),

        (f"Under {st} law, a temporary insurance license may be issued to:",
         "multiple_choice", "standard",
         "Temporary licenses are most commonly issued for agency continuity after a producer's death or incapacitation.",
         [("A surviving spouse or family member to continue an agency after the licensed producer's death", True, "Correct. Temporary licenses most commonly allow agency continuity after the licensed owner's death."),
          ("Any person waiting for exam results", False, "Waiting for exam results does not qualify for a temporary license."),
          ("A person who failed the exam and needs time to retake it", False, "Exam failure does not qualify for a temporary license."),
          ("Any unlicensed employee of an insurance agency", False, "Being employed by an agency does not automatically qualify for a temporary license.")]),

        (f"In {st}, express authority of an insurance producer is best described as:",
         "multiple_choice", "standard",
         "Express authority is explicitly granted in the written agency agreement.",
         [("Authority specifically granted in the written agency agreement", True, "Correct. Express authority is stated explicitly in the written contract."),
          ("Authority arising from the producer's position and normal business customs", False, "Authority from position and custom is implied authority."),
          ("Authority created when a third party reasonably believes the producer has authority based on the insurer's conduct", False, "This is apparent authority."),
          ("Authority the producer assumes without any written agreement", False, "Assumed authority without agreement is not recognized.")]),

        (f"Under {st} insurance law, defamation by a producer is:",
         "multiple_choice", "standard",
         "Defamation is making false statements about another insurer or producer. Truth is a complete defense.",
         [("Making false statements that injure the reputation of another insurer or producer", True, "Correct. Defamation requires false statements; truthful statements are not defamation."),
          ("Accurately reporting a competitor's financial difficulties to a client", False, "Truthful statements are not defamation."),
          ("Failing to disclose a material fact about a policy", False, "Failure to disclose is misrepresentation by omission, not defamation."),
          ("Using intimidation to prevent a client from shopping other insurers", False, "Intimidation is coercion, not defamation.")]),
    ]


def build_semi_universal(state_name, regulator_title, guaranty_name,
                          ce_hours, course_label):
    st = state_name
    reg = regulator_title
    return [
        (f"A {st} producer who moves must notify the {reg} within:",
         "multiple_choice", "standard",
         "Most states require notification of address changes within 30 days.",
         [("30 days of the address change", True, "Correct. Most states require notification within 30 days."),
          ("5 business days", False, "Shorter than the standard requirement."),
          ("60 days", False, "Exceeds the typical requirement."),
          ("At the next license renewal", False, "Changes must be reported promptly.")]),

        (f"In {st}, continuing education for licensed producers typically includes:",
         "multiple_choice", "standard",
         "Most states require CE hours per renewal cycle including a required ethics component.",
         [("A specified number of hours including an ethics component", True, "Correct. Most states require CE hours with a mandatory ethics component."),
          ("Only product knowledge courses with no ethics requirement", False, "Ethics is required in virtually all states."),
          ("CE is optional — only required if a complaint was filed", False, "CE is mandatory for all producers."),
          ("A state exam retake every renewal cycle", False, "Retaking the exam is not a CE requirement.")]),

        (f"Under {st} law, a producer convicted of a felony must:",
         "multiple_choice", "standard",
         "Most states require producers to report felony convictions to the insurance regulator.",
         [("Report the conviction to the state insurance regulator within the required timeframe", True, "Correct. Most states require prompt reporting of felony convictions."),
          ("Immediately surrender their license without any hearing", False, "A conviction triggers reporting requirements and may lead to a hearing."),
          ("Only report if the conviction relates to financial crimes", False, "Most states require reporting all felony convictions."),
          ("Wait until the conviction is final before reporting", False, "Most states require reporting upon conviction.")]),

        (f"In {st}, which entity must approve advertising materials before a producer uses them?",
         "multiple_choice", "standard",
         "The insurer must review and approve producer advertising materials.",
         [("The insurer the producer represents", True, "Correct. The insurer must approve producer advertising for regulatory compliance."),
          ("The state insurance department must pre-approve all advertisements", False, "Pre-approval by the state is not required for most lines."),
          ("A national advertising standards board", False, "No such board exists for insurance."),
          ("No approval is needed", False, "Insurance advertising is regulated; insurer approval is typically required.")]),

        (f"The {guaranty_name} covers claims when:",
         "multiple_choice", "standard",
         "The guaranty association covers claims only when a licensed admitted insurer becomes insolvent.",
         [("A licensed admitted insurer is declared insolvent", True, "Correct. The guaranty association covers claims from licensed insurer insolvencies."),
          ("A claim is denied for any reason", False, "The guaranty association only covers insolvency situations."),
          ("A policyholder cannot afford to pay their premium", False, "Premium affordability is not a guaranty association trigger."),
          ("An unauthorized insurer fails to pay claims", False, "The guaranty association covers only licensed admitted insurer failures.")]),

        (f"Under {st} law, sharing a commission with an unlicensed person:",
         "multiple_choice", "standard",
         "Sharing commissions with unlicensed individuals is prohibited and grounds for license discipline.",
         [("Violates state insurance law and may result in license suspension or revocation", True, "Correct. Sharing commissions with unlicensed persons is prohibited."),
          ("Is permitted if the unlicensed person performed legitimate services", False, "Services performed do not authorize commission sharing with unlicensed persons."),
          ("Must be reported to the state insurance department", False, "The arrangement itself is prohibited; disclosure does not make it permissible."),
          ("Is only permitted for family members", False, "Family relationships do not create an exception to this prohibition.")]),
    ]


def build_state_specific(state_abbr):
    specifics = {
        "NE": [
            ("In Nebraska, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Nebraska uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Nebraska uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Nebraska insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Nebraska insurance exams."),
              ("The Nebraska Department of Insurance directly", False, "Nebraska contracts with PSI for exam administration.")]),
            ("In Nebraska, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "Nebraska's insurance regulator is the Director of Insurance.",
             [("Director of Insurance", True, "Correct. Nebraska's insurance regulator is the Director of Insurance."),
              ("Commissioner of Insurance", False, "Commissioner is used in many states but not Nebraska."),
              ("Superintendent of Insurance", False, "Superintendent is used in New York, not Nebraska."),
              ("Secretary of Insurance", False, "Secretary is not the title used in Nebraska.")]),
            ("Nebraska's Insurance Fraud Act prohibits:",
             "multiple_choice", "standard",
             "Nebraska's Insurance Fraud Act prohibits a range of fraudulent acts including filing false claims, misrepresenting material facts on applications, and other fraudulent insurance activities.",
             [("Filing false insurance claims and misrepresenting material facts on applications", True, "Correct. Nebraska's Insurance Fraud Act prohibits false claims, material misrepresentations, and other fraudulent acts."),
              ("Only fraudulent acts by insurance companies — not by producers", False, "The Act applies to all participants in insurance transactions including producers and policyholders."),
              ("Only fraud involving more than $10,000", False, "Nebraska's fraud law applies regardless of dollar amount."),
              ("Only fraud committed outside Nebraska", False, "The Act applies to insurance fraud occurring within Nebraska.")]),
            ("Under Nebraska insurance law, an 'admitted' insurer is:",
             "multiple_choice", "standard",
             "An admitted (authorized) insurer has received a certificate of authority from the state to transact insurance business. Non-admitted (unauthorized) insurers have not received this authorization.",
             [("An insurer that has received a certificate of authority to transact insurance in Nebraska", True, "Correct. An admitted insurer is one that has been licensed (received a certificate of authority) by the Nebraska Director of Insurance."),
              ("Any insurer that has operated in Nebraska for more than 5 years", False, "Longevity of operation does not determine admitted status; a certificate of authority is required."),
              ("An insurer with more than $1 billion in assets", False, "Asset size does not determine admitted status."),
              ("An insurer approved by the federal government to sell insurance", False, "Insurance licensure is a state function; federal approval does not determine admitted status.")]),
            ("Nebraska's privacy of insurance consumer information regulations require insurers to:",
             "multiple_choice", "standard",
             "Nebraska's insurance privacy regulations require insurers to provide privacy notices to consumers and protect personal financial information from unauthorized disclosure, consistent with GLBA requirements.",
             [("Provide privacy notices and protect consumer financial information from unauthorized disclosure", True, "Correct. Nebraska requires privacy notices and protection of consumer financial information."),
              ("Report all consumer financial data to the Nebraska Director of Insurance annually", False, "Reporting consumer data to the Director is not required under privacy regulations."),
              ("Delete all consumer records after policy cancellation", False, "Records must be retained; they cannot simply be deleted after cancellation."),
              ("Share consumer information freely with law enforcement upon request", False, "Law enforcement access requires proper legal process; privacy protections generally apply.")]),
        ],
        "NV": [
            ("In Nevada, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Nevada uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Nevada uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Nevada insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Nevada insurance exams."),
              ("The Nevada Division of Insurance directly", False, "Nevada contracts with Pearson VUE for exam administration.")]),
            ("In Nevada, prepaid funeral contract agents require:",
             "multiple_choice", "standard",
             "Nevada requires a separate limited license for agents selling prepaid funeral contracts — an insurance-adjacent product regulated by the Division of Insurance.",
             [("A separate limited license to sell prepaid funeral contracts", True, "Correct. Prepaid funeral contract agents require a separate limited license in Nevada."),
              ("Only a standard life insurance producer license", False, "A standard life license alone does not authorize selling prepaid funeral contracts in Nevada."),
              ("No license — funeral home employees are exempt from licensing", False, "Prepaid funeral contract agents must be licensed in Nevada."),
              ("A property and casualty license with a funeral endorsement", False, "Prepaid funeral contracts are not a P&C product; a separate limited license is required.")]),
            ("The Nevada Life and Health Insurance Guaranty Association covers claims from:",
             "multiple_choice", "standard",
             "The Nevada Life and Health Insurance Guaranty Association covers life, health, and annuity claims when a licensed Nevada insurer becomes insolvent.",
             [("Insolvent licensed Nevada life, health, and annuity insurers", True, "Correct. The Nevada guaranty association covers claims from licensed insurer insolvencies."),
              ("Any claim denied by any Nevada insurer", False, "The guaranty association only covers insolvency situations."),
              ("Claims from non-admitted insurers operating in Nevada", False, "The guaranty association covers only licensed admitted insurer insolvencies."),
              ("Only claims filed by Nevada state employees", False, "The guaranty association covers all eligible Nevada policyholders.")]),
            ("In Nevada, credit life insurance is regulated to ensure:",
             "multiple_choice", "standard",
             "Nevada regulates credit life insurance to protect borrowers, including requiring that premiums be reasonable, coverage be appropriate to the debt, and disclosure requirements be met.",
             [("Premiums are reasonable and coverage is appropriate to the underlying debt", True, "Correct. Nevada regulates credit life to ensure premiums and coverage amounts are proportional and reasonable."),
              ("All credit life policies automatically renew each year", False, "Credit life policies are tied to debt obligations and do not simply auto-renew."),
              ("Credit life is mandatory for all Nevada borrowers", False, "Credit life insurance is optional, not mandatory."),
              ("Credit life proceeds are paid to the state rather than the borrower's estate", False, "Credit life proceeds are paid to the creditor to satisfy the debt, not to the state.")]),
            ("Nevada's insurance advertising regulations prohibit:",
             "multiple_choice", "standard",
             "Nevada prohibits false and misleading advertising including any statements that misrepresent policy benefits, terms, or conditions. Advertising must be truthful and not create false impressions.",
             [("False or misleading statements about policy benefits or terms", True, "Correct. Nevada's advertising regulations prohibit false or misleading statements in insurance advertising."),
              ("Advertising insurance products online or through social media", False, "Online and social media advertising is permitted in Nevada as long as it complies with advertising rules."),
              ("Including premium rates in insurance advertisements", False, "Including accurate premium rates in advertising is permitted."),
              ("Using customer testimonials in insurance advertisements", False, "Customer testimonials are permitted if truthful and not misleading.")]),
        ],
        "NH": [
            ("In New Hampshire, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "New Hampshire uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. New Hampshire uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer New Hampshire insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric previously administered New Hampshire's exams but is no longer the provider."),
              ("The New Hampshire Insurance Department directly", False, "New Hampshire contracts with PSI for exam administration.")]),
            ("New Hampshire auto insurance law includes provisions for:",
             "multiple_choice", "standard",
             "New Hampshire has specific auto insurance laws including provisions for collision deductible waivers and cancellation/non-renewal rules that are state-specific.",
             [("Collision deductible waivers and specific cancellation/non-renewal rules", True, "Correct. New Hampshire has state-specific auto insurance provisions including deductible waivers and cancellation rules."),
              ("Mandatory no-fault personal injury protection for all drivers", False, "New Hampshire is one of the few states that does not require mandatory auto insurance (though this may be changing)."),
              ("A state-operated auto insurance fund for all NH residents", False, "New Hampshire does not operate a state auto insurance fund."),
              ("Mandatory uninsured motorist coverage equal to liability limits", False, "New Hampshire's uninsured motorist requirements have specific state rules that do not require matching liability limits.")]),
            ("The New Hampshire Insurance Guaranty Fund protects policyholders by:",
             "multiple_choice", "standard",
             "New Hampshire's Insurance Guaranty Fund protects policyholders when a licensed New Hampshire insurer becomes insolvent.",
             [("Paying claims when a licensed New Hampshire insurer becomes insolvent", True, "Correct. The New Hampshire Guaranty Fund covers claims from licensed insurer insolvencies."),
              ("Providing free insurance to uninsured New Hampshire residents", False, "The Guaranty Fund is an insolvency protection mechanism."),
              ("Setting maximum premium rates for NH insurance products", False, "Rate regulation is the Commissioner's function."),
              ("Covering claims from surplus lines insurers", False, "The Guaranty Fund covers only licensed admitted insurer insolvencies.")]),
            ("Under New Hampshire insurance law, a producer acting without authorization from an insurer:",
             "multiple_choice", "standard",
             "Acting outside the scope of authority granted by the insurer (ultra vires acts) can create personal liability for the producer and does not bind the insurer.",
             [("May create personal liability for the producer and does not bind the insurer", True, "Correct. Acts beyond the scope of authority create personal producer liability and generally do not bind the insurer."),
              ("Is covered by the insurer's general liability policy", False, "The insurer's liability policy does not cover unauthorized producer acts."),
              ("Results in the policy being automatically void", False, "The policy may be voidable but is not automatically void."),
              ("Is permitted as long as the client was not harmed", False, "Acting without authorization is improper regardless of whether harm resulted.")]),
            ("New Hampshire's federal law compliance requirements for producers include:",
             "multiple_choice", "standard",
             "New Hampshire producers must comply with several federal laws including the Fair Credit Reporting Act, 18 USC 1033/1034 (federal insurance fraud statute), and the National Flood Insurance Program requirements.",
             [("Compliance with the FCRA, federal fraud statutes (18 USC 1033/1034), and NFIP requirements", True, "Correct. New Hampshire producers must comply with these federal statutes in addition to state insurance laws."),
              ("Compliance only with federal laws that have been adopted by New Hampshire statute", False, "Federal laws apply in New Hampshire regardless of state adoption."),
              ("Reporting all client transactions to federal agencies", False, "Routine transaction reporting to federal agencies is not required."),
              ("Obtaining separate federal approval to sell insurance in New Hampshire", False, "Federal approval for insurance sales is not required; state licensure is the standard.")]),
        ],
        "NJ": [
            ("In New Jersey, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "New Jersey uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. New Jersey uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer New Jersey insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer New Jersey insurance exams."),
              ("The New Jersey Department of Banking and Insurance directly", False, "New Jersey contracts with PSI for exam administration.")]),
            ("In New Jersey, the insurance and banking regulatory agency is the:",
             "multiple_choice", "standard",
             "New Jersey uniquely combines insurance and banking regulation under a single agency — the Department of Banking and Insurance (DOBI).",
             [("Department of Banking and Insurance (DOBI)", True, "Correct. New Jersey combines insurance and banking regulation in the DOBI."),
              ("Department of Financial Services", False, "DFS is New York's combined financial regulatory agency, not New Jersey's."),
              ("Office of the Insurance Commissioner", False, "New Jersey uses the DOBI structure, not a standalone insurance commissioner office."),
              ("Division of Insurance", False, "New Jersey uses DOBI as the agency name.")]),
            ("Under New Jersey's Regulation 187, the best-interest standard for life insurance and annuities requires producers to:",
             "multiple_choice", "standard",
             "New Jersey's Regulation 187 established a best-interest standard for life insurance and annuity transactions, requiring producers to prioritize the customer's interests over their own financial interests.",
             [("Prioritize the customer's financial interests when recommending life insurance or annuities", True, "Correct. NJ Regulation 187 requires producers to act in the customer's best interest when recommending life insurance and annuities."),
              ("Recommend only the least expensive products available", False, "Best interest means matching the right product to the client's needs, not always recommending the cheapest."),
              ("Obtain written approval from DOBI before each life insurance sale", False, "Individual transaction approval from DOBI is not required."),
              ("Recommend life insurance only to clients with verifiable insurable interest", False, "Insurable interest is always required; the best-interest standard addresses recommendation suitability.")]),
            ("New Jersey's tort threshold options for auto insurance allow policyholders to:",
             "multiple_choice", "standard",
             "New Jersey is a unique no-fault state that allows policyholders to choose between a 'lawsuit threshold' (verbal threshold) or 'zero threshold' (full right to sue) option, affecting how auto accident claims can proceed.",
             [("Choose between limited right to sue (lawsuit threshold) and full right to sue options", True, "Correct. New Jersey allows policyholders to select their lawsuit threshold option, affecting their ability to sue for pain and suffering."),
              ("Opt out of all auto insurance requirements", False, "New Jersey requires auto insurance; opting out entirely is not permitted."),
              ("Choose government-funded auto insurance instead of private coverage", False, "New Jersey does not offer government-funded personal auto insurance."),
              ("Set their own premium rates based on self-assessed driving risk", False, "Premium rates are set by insurers based on filed rate schedules, not self-assessment.")]),
            ("The New Jersey Life and Health Insurance Guaranty Association covers claims involving:",
             "multiple_choice", "standard",
             "The New Jersey Life and Health Insurance Guaranty Association covers life insurance, health insurance, and annuity claims when a licensed New Jersey insurer becomes insolvent.",
             [("Life insurance, health insurance, and annuities from insolvent licensed New Jersey insurers", True, "Correct. The NJ guaranty association covers these product types from insolvent licensed insurers."),
              ("Only term life insurance — permanent life is excluded", False, "All types of life insurance are covered by the guaranty association."),
              ("Claims from all insurers regardless of admitted status", False, "Only licensed admitted insurer insolvencies are covered."),
              ("Only policies with face amounts over $100,000", False, "Coverage is available regardless of face amount, subject to statutory limits.")]),
        ],
        "NM": [
            ("In New Mexico, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "New Mexico uses Prometric to administer its insurance licensing examinations.",
             [("Prometric at approved testing centers", True, "Correct. New Mexico uses Prometric as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer New Mexico insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer New Mexico insurance exams."),
              ("The New Mexico Office of Superintendent of Insurance directly", False, "New Mexico contracts with Prometric for exam administration.")]),
            ("In New Mexico, the insurance regulatory official is the:",
             "multiple_choice", "standard",
             "New Mexico's insurance regulator holds the title of Superintendent of Insurance, heading the Office of Superintendent of Insurance (OSI).",
             [("Superintendent of Insurance", True, "Correct. New Mexico's insurance regulator is the Superintendent of Insurance."),
              ("Commissioner of Insurance", False, "Commissioner is used in most states but not New Mexico."),
              ("Director of Insurance", False, "Director is used in states like Illinois and Idaho, not New Mexico."),
              ("Secretary of Insurance", False, "Secretary is not the title used in New Mexico.")]),
            ("New Mexico's Consumer Information Privacy Act requires insurers to:",
             "multiple_choice", "standard",
             "New Mexico's Consumer Information Privacy Act requires insurers to protect consumer personal information and provide privacy notices, consistent with GLBA requirements.",
             [("Protect consumer personal information and provide privacy notices", True, "Correct. New Mexico's privacy act requires protection of consumer information and privacy disclosures."),
              ("Report all consumer financial data to the Superintendent annually", False, "Reporting consumer data to the Superintendent is not a privacy requirement."),
              ("Delete all consumer records when a policy expires", False, "Records must be retained for minimum periods; they cannot be deleted at policy expiration."),
              ("Share consumer information with all licensed New Mexico insurers", False, "Sharing consumer information with other insurers is restricted, not required.")]),
            ("The New Mexico Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The New Mexico Life and Health Insurance Guaranty Association provides protection for New Mexico policyholders when a licensed New Mexico insurer becomes insolvent.",
             [("Protects New Mexico policyholders when a licensed insurer becomes insolvent", True, "Correct. The New Mexico guaranty association covers claims from insolvent licensed insurers."),
              ("Provides free health insurance to low-income New Mexico residents", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets maximum rates for New Mexico insurance products", False, "Rate regulation is the Superintendent's function."),
              ("Covers claims from unlicensed insurers doing business in New Mexico", False, "The guaranty association covers only licensed admitted insurer insolvencies.")]),
            ("Under New Mexico insurance law, a fraternal benefit society is:",
             "multiple_choice", "standard",
             "A fraternal benefit society is a nonprofit organization with a representative form of government that provides insurance benefits to its members. They are regulated differently from traditional insurance companies.",
             [("A nonprofit organization that provides insurance benefits to its members through a representative form of government", True, "Correct. Fraternal benefit societies are member-owned nonprofits providing insurance to members."),
              ("A government agency that provides insurance to state employees", False, "Fraternal benefit societies are private nonprofit organizations, not government agencies."),
              ("A for-profit insurance company that uses sales agents called 'fraternals'", False, "Fraternal benefit societies are nonprofit and member-owned, not for-profit corporations."),
              ("Any insurance company with fewer than 100 policyholders", False, "Size is not the defining characteristic of a fraternal benefit society; organizational structure is.")]),
        ],
        "NY": [
            ("In New York, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "New York uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. New York uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer New York insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer New York insurance exams."),
              ("The New York Department of Financial Services directly", False, "New York contracts with PSI for exam administration.")]),
            ("In New York, Regulation 60 governs:",
             "multiple_choice", "standard",
             "New York's Regulation 60 governs the replacement of life insurance and annuity contracts, establishing extensive disclosure and comparison requirements designed to protect consumers from uninformed replacements.",
             [("The replacement of life insurance and annuity contracts in New York", True, "Correct. NY Regulation 60 establishes comprehensive replacement disclosure requirements for life insurance and annuities."),
              ("The licensing and continuing education requirements for life producers", False, "Licensing requirements are governed by New York Insurance Law, not Regulation 60."),
              ("The advertising standards for all insurance products sold in New York", False, "Advertising standards are governed by different regulations; Regulation 60 specifically addresses replacement."),
              ("The rate filing requirements for New York life insurers", False, "Rate filings are a separate regulatory matter; Regulation 60 governs replacement.")]),
            ("New York's Department of Financial Services (DFS) is unique because it:",
             "multiple_choice", "standard",
             "New York's DFS is unique in combining regulation of banking, insurance, and financial services under a single Superintendent of Financial Services — one of the most comprehensive state financial regulatory structures.",
             [("Combines regulation of insurance, banking, and other financial services under one Superintendent", True, "Correct. New York's DFS uniquely combines insurance, banking, and other financial services regulation under one agency."),
              ("Reports directly to the federal SEC for regulatory guidance", False, "DFS is a state agency that does not report to the SEC."),
              ("Was established by a federal law requiring combined state financial regulation", False, "DFS was established by New York state law, not federal mandate."),
              ("Only regulates insurance — banking is handled by a separate agency", False, "DFS combines insurance, banking, and other financial services regulation.")]),
            ("New York's Valued Policy Law applies to:",
             "multiple_choice", "standard",
             "New York's Valued Policy Law requires insurers to pay the full policy face amount for a total loss of insured property, even if the actual cash value is less — the policy value is the agreed value for total losses.",
             [("Property insurance policies, requiring payment of the full face amount on total losses", True, "Correct. New York's Valued Policy Law requires payment of the full policy face amount for total property losses."),
              ("Life insurance policies where the insured's death occurs in New York", False, "The Valued Policy Law applies to property insurance, not life insurance."),
              ("Health insurance policies for hospitalization in New York facilities", False, "The Valued Policy Law applies to property insurance, not health insurance."),
              ("All insurance policies issued by New York licensed insurers", False, "The Valued Policy Law is specific to property insurance policies.")]),
            ("The New York Life and Health Insurance Guaranty Corporation:",
             "multiple_choice", "standard",
             "New York uses the term 'Guaranty Corporation' rather than 'Guaranty Association' for its life and health insolvency protection mechanism, which covers claims from licensed New York insurer insolvencies.",
             [("Provides protection for New York life and health policyholders when a licensed insurer becomes insolvent", True, "Correct. The NY Guaranty Corporation protects policyholders from licensed insurer insolvencies."),
              ("Provides free life insurance to all New York residents", False, "The Guaranty Corporation is an insolvency protection mechanism."),
              ("Regulates premium rates for New York life insurance products", False, "Rate regulation is the DFS's function."),
              ("Only covers policies issued by mutual insurance companies", False, "The Guaranty Corporation covers policyholders of any licensed insurer, regardless of company structure.")]),
        ],
        "NC": [
            ("In North Carolina, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "North Carolina uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. North Carolina uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer North Carolina insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer North Carolina insurance exams."),
              ("The North Carolina Department of Insurance directly", False, "North Carolina contracts with Pearson VUE for exam administration.")]),
            ("North Carolina's Unfair Trade Practices Act (Article 63) prohibits:",
             "multiple_choice", "standard",
             "North Carolina's Unfair Trade Practices Act (Article 63 of the Insurance Laws) prohibits a broad range of unfair practices including misrepresentation, defamation, rebating, and unfair claims settlement.",
             [("Misrepresentation, defamation, rebating, unfair discrimination, and unfair claims settlement", True, "Correct. Article 63 prohibits all of these unfair trade practices."),
              ("Only practices involving auto insurance policies", False, "Article 63 applies to all lines of insurance."),
              ("Only practices that result in verified financial harm to consumers", False, "The Act prohibits the practices themselves regardless of harm."),
              ("Only practices by insurance companies — not by individual producers", False, "Article 63 applies to all participants in insurance transactions.")]),
            ("The North Carolina Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The North Carolina Life and Health Insurance Guaranty Association protects North Carolina policyholders when a licensed North Carolina life, health, or annuity insurer becomes insolvent.",
             [("Protects NC policyholders when a licensed NC insurer becomes insolvent", True, "Correct. The NC guaranty association covers claims from licensed insurer insolvencies."),
              ("Sets rates for all North Carolina insurance products", False, "Rate setting is the Commissioner's function."),
              ("Provides free homeowners insurance to NC coastal property owners", False, "The guaranty association is an insolvency protection mechanism."),
              ("Covers all claims regardless of the insurer's admitted status", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("North Carolina's coastal property insurance issues are addressed by:",
             "multiple_choice", "standard",
             "North Carolina has specific mechanisms for coastal property insurance including wind and hail coverage for properties in beach and coastal areas that cannot obtain standard coverage.",
             [("The North Carolina Insurance Underwriting Association (beach plan) for coastal properties", True, "Correct. The NC beach plan provides wind and hail coverage for coastal properties unable to obtain standard market coverage."),
              ("A federal government program that covers all coastal NC properties", False, "Coastal property insurance in NC is primarily addressed through state mechanisms, not federal programs."),
              ("A mandatory surcharge on all NC property insurance policies", False, "While assessments fund certain mechanisms, coastal insurance is not simply a surcharge."),
              ("A complete prohibition on new construction in coastal areas", False, "Insurance mechanisms address coverage availability, not construction prohibitions.")]),
            ("In North Carolina, solicitation rules for life insurance (Article 60) govern:",
             "multiple_choice", "standard",
             "North Carolina's Article 60 establishes specific requirements for life insurance solicitation including buyer's guides, policy summaries, and other disclosure requirements.",
             [("Disclosure requirements including buyer's guides and policy summaries for life insurance sales", True, "Correct. NC Article 60 requires specific disclosures during life insurance solicitation including buyer's guides and policy summaries."),
              ("Only the solicitation of group life insurance policies", False, "Article 60 covers individual life insurance solicitation; group rules are separate."),
              ("The advertising standards for all insurance lines sold in NC", False, "Advertising standards are broader; Article 60 specifically addresses life insurance solicitation."),
              ("The minimum premium requirements for NC life insurance policies", False, "Minimum premiums are not the subject of Article 60; it addresses solicitation disclosures.")]),
        ],
        "ND": [
            ("In North Dakota, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "North Dakota uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. North Dakota uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer North Dakota insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer North Dakota insurance exams."),
              ("The North Dakota Insurance Department directly", False, "North Dakota contracts with PSI for exam administration.")]),
            ("North Dakota's mandatory accident and health policy provisions include all of the following EXCEPT:",
             "multiple_choice", "standard",
             "North Dakota requires specific standard provisions in A&H policies including grace period, reinstatement, notice of claim, and pre-existing condition rules. A guaranteed no-price-increase clause is not a standard mandatory provision.",
             [("A guaranteed no-price-increase clause for the life of the policy", True, "Correct. A guaranteed no-price-increase clause is NOT a mandatory provision in ND accident and health policies."),
              ("Grace period provision", False, "Grace period IS a mandatory provision in North Dakota A&H policies."),
              ("Reinstatement provision", False, "Reinstatement IS a mandatory provision in North Dakota A&H policies."),
              ("Notice of claim provision", False, "Notice of claim IS a mandatory provision in North Dakota A&H policies.")]),
            ("North Dakota's mandated health benefits include coverage for:",
             "multiple_choice", "standard",
             "North Dakota has mandated specific health insurance benefits including newborn and adopted child coverage, dependent coverage, prescription drug coverage, and chiropractic care.",
             [("Newborn and adopted children, dependent coverage, prescription drugs, and chiropractic care", True, "Correct. North Dakota mandates these specific health insurance benefits."),
              ("Only maternity care for covered employees", False, "North Dakota's mandated benefits are broader than just maternity care."),
              ("Free preventive care with no cost sharing for all ND residents", False, "While the ACA requires preventive care coverage, North Dakota's mandated benefits are state-specific requirements."),
              ("Dental and vision coverage for all insured employees", False, "Dental and vision are typically separate from North Dakota's health insurance mandates.")]),
            ("The North Dakota Life and Health Guaranty Association:",
             "multiple_choice", "standard",
             "The North Dakota Life and Health Guaranty Association provides protection for North Dakota policyholders when a licensed North Dakota life, health, or annuity insurer becomes insolvent.",
             [("Protects North Dakota policyholders when a licensed insurer becomes insolvent", True, "Correct. The ND guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides free life insurance to ND military veterans", False, "The guaranty association is an insolvency protection mechanism."),
              ("Regulates rates for North Dakota health insurers", False, "Rate regulation is the Commissioner's function."),
              ("Only covers claims from ND-domiciled insurance companies", False, "The guaranty association covers claims from licensed admitted insurers regardless of state of domicile.")]),
            ("North Dakota's legislation affecting short-term limited-duration health plans:",
             "multiple_choice", "standard",
             "North Dakota has enacted legislation governing short-term limited-duration health insurance plans, including requirements for disclosure and limitations on plan terms, consistent with both state and federal regulatory approaches.",
             [("Establishes disclosure requirements and term limitations for short-term health plans", True, "Correct. North Dakota has legislation addressing short-term health plan disclosures and term limitations."),
              ("Completely prohibits the sale of short-term health plans in North Dakota", False, "North Dakota regulates rather than prohibits short-term health plans."),
              ("Requires all short-term plans to include ACA essential health benefits", False, "Short-term plans are exempt from ACA essential health benefit requirements; state disclosure rules apply."),
              ("Limits short-term health plans to government employees only", False, "Short-term plans are available to the general public, not just government employees.")]),
        ],
        "OH": [
            ("In Ohio, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Ohio uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Ohio uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Ohio insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Ohio insurance exams."),
              ("The Ohio Department of Insurance directly", False, "Ohio contracts with PSI for exam administration.")]),
            ("Ohio's Valued Policy Law requires property insurers to:",
             "multiple_choice", "standard",
             "Ohio's Valued Policy Law requires property insurers to pay the full policy face amount in the event of a total loss, even if the actual cash value is less than the policy amount.",
             [("Pay the full face amount of the policy on a total loss regardless of actual cash value", True, "Correct. Ohio's Valued Policy Law requires payment of the full policy value on total losses."),
              ("Always pay actual cash value rather than replacement cost on losses", False, "Ohio's Valued Policy Law requires payment of face value on total losses, which may exceed ACV."),
              ("Provide free coverage for earthquake damage in all Ohio counties", False, "The Valued Policy Law addresses payment on total losses, not specific perils."),
              ("Issue refunds when actual losses are less than the policy premium paid", False, "The Valued Policy Law addresses claim payments, not premium refunds.")]),
            ("Ohio's workers' compensation system is notable because it is:",
             "multiple_choice", "standard",
             "Ohio operates a state-fund workers' compensation system (a monopoly state fund). Most employers in Ohio are required to obtain workers' compensation coverage through the state fund rather than private insurers.",
             [("A state-fund monopoly requiring most employers to obtain coverage through the state", True, "Correct. Ohio operates a monopoly state workers' compensation fund; most employers cannot use private insurers."),
              ("A competitive private market where any licensed insurer can write workers' comp", False, "Ohio requires most employers to use the state fund, not private insurers."),
              ("A voluntary program where employers choose whether to provide workers' comp", False, "Workers' compensation is mandatory for most Ohio employers."),
              ("Administered by the federal Department of Labor directly", False, "Ohio's workers' compensation is a state-administered system, not federal.")]),
            ("The Ohio Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Ohio Insurance Guaranty Association covers property and casualty claims when a licensed Ohio P&C insurer becomes insolvent. Life and health claims are covered by a separate guaranty association.",
             [("Covers property and casualty claims when a licensed Ohio P&C insurer becomes insolvent", True, "Correct. Ohio's P&C guaranty association covers P&C claims from insolvent licensed insurers."),
              ("Covers all insurance lines including life and health", False, "Ohio has separate guaranty associations for P&C and life/health."),
              ("Provides supplemental coverage to policyholders with high-risk properties", False, "The guaranty association covers insolvency situations, not supplemental coverage."),
              ("Is funded by federal government appropriations", False, "Guaranty associations are funded by assessments on licensed insurers, not federal appropriations.")]),
            ("Ohio's mine-subsidence coverage requirement applies to:",
             "multiple_choice", "standard",
             "Ohio has areas with underground mining activity where surface subsidence is a risk. Ohio requires insurers to offer mine-subsidence coverage as a required endorsement option in affected areas.",
             [("Property in areas of Ohio subject to underground mine subsidence risk", True, "Correct. Ohio requires insurers to offer mine-subsidence coverage in areas with underground mining activity."),
              ("All Ohio property insurance policies regardless of location", False, "Mine-subsidence requirements apply in areas with actual subsidence risk, not statewide."),
              ("Only commercial property policies in Ohio mining counties", False, "Mine-subsidence requirements can apply to residential as well as commercial properties."),
              ("Automobile policies for vehicles driven in mining areas", False, "Mine-subsidence coverage is a property insurance concept, not an auto insurance concept.")]),
        ],
        "OK": [
            ("In Oklahoma, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Oklahoma uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Oklahoma uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Oklahoma insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Oklahoma insurance exams."),
              ("The Oklahoma Insurance Department directly", False, "Oklahoma contracts with PSI for exam administration.")]),
            ("In Oklahoma, the Insurance Commissioner has the authority to:",
             "multiple_choice", "standard",
             "Oklahoma's Insurance Commissioner has broad regulatory powers including examining insurer records, enforcing licensing statutes, and maintaining records of all regulated entities.",
             [("Examine insurer records, enforce licensing statutes, and maintain regulatory records", True, "Correct. Oklahoma's Commissioner has the full range of regulatory powers."),
              ("Set premium rates for all lines of insurance without insurer input", False, "Insurers file rates for Commissioner review; the Commissioner does not unilaterally set rates."),
              ("Defend policyholders in coverage disputes with insurers", False, "The Commissioner regulates the industry but does not provide legal defense for policyholders."),
              ("Approve individual insurance claims before they are paid", False, "Individual claim approval is not a Commissioner function.")]),
            ("Oklahoma's Oklahoma Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Oklahoma Insurance Guaranty Association covers property and casualty claims when a licensed Oklahoma P&C insurer becomes insolvent.",
             [("Covers P&C claims when a licensed Oklahoma insurer becomes insolvent", True, "Correct. The Oklahoma P&C guaranty association covers claims from insolvent licensed insurers."),
              ("Provides free tornado insurance to all Oklahoma homeowners", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets maximum rates for Oklahoma P&C insurance", False, "Rate regulation is the Commissioner's function."),
              ("Only applies to earthquake and tornado damage claims", False, "The guaranty association covers all covered P&C claims from insolvent insurers.")]),
            ("Oklahoma's surplus lines regulation requires producers to:",
             "multiple_choice", "standard",
             "Oklahoma's surplus lines regulation requires that surplus lines placements be made only when coverage is unavailable from admitted insurers, and that surplus lines brokers comply with tax and regulatory reporting requirements.",
             [("Show that coverage is unavailable from admitted insurers before placing surplus lines", True, "Correct. Surplus lines placements require evidence that the admitted market could not provide the coverage."),
              ("Pay a higher commission rate on all surplus lines placements", False, "Higher commission rates are not required; the requirement is demonstrating admitted market unavailability."),
              ("Obtain the Commissioner's approval before each surplus lines placement", False, "Individual Commissioner approval is not required; diligent search of the admitted market must be documented."),
              ("Only use surplus lines for commercial policies — personal lines cannot use surplus lines", False, "Surplus lines can be used for both commercial and personal lines when admitted market coverage is unavailable.")]),
            ("In Oklahoma, a producer who countersigns a policy on behalf of an insurer:",
             "multiple_choice", "standard",
             "Some states including Oklahoma have countersignature laws that require policies to be countersigned by a licensed resident producer. This ensures local market participation and regulatory oversight.",
             [("May be fulfilling a countersignature requirement under Oklahoma law", True, "Correct. Oklahoma has countersignature requirements where a licensed resident producer must sign certain policies."),
              ("Is acting as an insurer and must be separately licensed as a company", False, "Countersigning is a producer activity, not an insurer activity."),
              ("Is violating Oklahoma law unless they are the originating producer", False, "Countersignature is a legally required activity under Oklahoma's countersignature laws."),
              ("Has no legal significance in the modern insurance market", False, "Countersignature laws still exist in some states including Oklahoma and have legal significance.")]),
        ],
        "OR": [
            ("In Oregon, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Oregon uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Oregon uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Oregon insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Oregon insurance exams."),
              ("The Oregon Division of Financial Regulation directly", False, "Oregon contracts with Pearson VUE for exam administration.")]),
            ("In Oregon, the insurance regulatory agency is the:",
             "multiple_choice", "standard",
             "Oregon's insurance regulatory agency is the Division of Financial Regulation (DFR), which is part of the Department of Consumer and Business Services (DCBS).",
             [("Division of Financial Regulation within the Department of Consumer and Business Services", True, "Correct. Oregon's insurance is regulated by the DFR within DCBS."),
              ("Oregon Insurance Commission", False, "Oregon does not have a standalone Insurance Commission; regulation is through the DFR/DCBS."),
              ("Bureau of Insurance and Financial Services", False, "This is not the name of Oregon's insurance regulatory agency."),
              ("Oregon Department of Insurance", False, "Oregon does not have a standalone Department of Insurance; regulation is through the DFR/DCBS.")]),
            ("The Oregon Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Oregon Insurance Guaranty Association covers property and casualty claims when a licensed Oregon P&C insurer becomes insolvent.",
             [("Covers P&C claims when a licensed Oregon P&C insurer becomes insolvent", True, "Correct. Oregon's P&C guaranty association covers claims from insolvent licensed insurers."),
              ("Provides subsidized insurance to Oregon farmers", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets rates for all Oregon property insurance", False, "Rate setting is the regulator's function."),
              ("Covers claims from non-admitted insurers", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Oregon's FAIR Plan provides:",
             "multiple_choice", "standard",
             "Oregon's FAIR (Fair Access to Insurance Requirements) Plan provides basic property insurance to property owners who cannot obtain coverage in the voluntary market.",
             [("Basic property insurance to owners unable to obtain voluntary market coverage", True, "Correct. Oregon's FAIR Plan is the insurer of last resort for basic property coverage."),
              ("Comprehensive auto insurance to high-risk Oregon drivers", False, "FAIR Plans cover property insurance; auto insurance has separate assigned risk mechanisms."),
              ("Free renters insurance to low-income Oregon residents", False, "FAIR Plans are not free insurance programs; they provide coverage at market rates."),
              ("Full HO-3 equivalent coverage for all Oregon homeowners", False, "FAIR Plans provide more limited basic coverage, not comprehensive homeowners policies.")]),
            ("Under Oregon's Insurance Fraud Prevention Act, which of the following is prohibited?",
             "multiple_choice", "standard",
             "Oregon's Insurance Fraud Prevention Act prohibits a range of fraudulent acts including filing false claims, misrepresenting facts on applications, and other deceptive insurance practices.",
             [("Filing false insurance claims or misrepresenting facts on insurance applications", True, "Correct. Oregon's Act prohibits false claims and application misrepresentations."),
              ("Changing insurance companies at renewal", False, "Shopping for insurance at renewal is legal; the Act prohibits fraudulent acts."),
              ("Using an insurance broker instead of an agent", False, "Using brokers or agents is legal; the Act prohibits fraud."),
              ("Purchasing more than one insurance policy", False, "Multiple insurance policies are legal; the Act prohibits fraudulent acts.")]),
        ],
        "PA": [
            ("In Pennsylvania, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Pennsylvania uses PSI Services to administer its insurance licensing examinations.",
             [("PSI Services at approved testing centers", True, "Correct. Pennsylvania uses PSI as its insurance examination provider."),
              ("Pearson VUE at approved testing centers", False, "Pearson VUE does not administer Pennsylvania insurance exams."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Pennsylvania insurance exams."),
              ("The Pennsylvania Insurance Department directly", False, "Pennsylvania contracts with PSI for exam administration.")]),
            ("Pennsylvania's Motor Vehicle Financial Responsibility Law (MVFRL) requires:",
             "multiple_choice", "standard",
             "Pennsylvania's MVFRL requires registered vehicle owners to maintain minimum liability insurance and also governs no-fault benefits, tort threshold options, and other aspects of auto insurance in Pennsylvania.",
             [("Vehicle owners to maintain minimum liability insurance and governs no-fault auto benefits", True, "Correct. Pennsylvania's MVFRL requires minimum liability coverage and establishes the no-fault and tort threshold system."),
              ("All Pennsylvania drivers to purchase state-provided auto insurance", False, "Pennsylvania uses the private insurance market; there is no state-provided auto insurance."),
              ("Insurers to cover all accidents regardless of fault with no deductible", False, "MVFRL governs minimum coverage requirements; it does not eliminate fault-based liability."),
              ("Auto insurance companies to pay all medical claims within 24 hours", False, "Pennsylvania has claims handling requirements but not a universal 24-hour payment mandate.")]),
            ("The Pennsylvania Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Pennsylvania Life and Health Insurance Guaranty Association protects Pennsylvania policyholders when a licensed Pennsylvania life, health, or annuity insurer becomes insolvent.",
             [("Protects Pennsylvania policyholders when a licensed insurer becomes insolvent", True, "Correct. The PA guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides low-cost health insurance to small Pennsylvania employers", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets the minimum standards for PA life insurance policies", False, "Policy standards are set by the Insurance Department, not the guaranty association."),
              ("Only covers claims from Pennsylvania-domiciled insurers", False, "The guaranty association covers claims from licensed admitted insurers regardless of domicile.")]),
            ("Pennsylvania's Insurance Fraud Regulation imposes:",
             "multiple_choice", "standard",
             "Pennsylvania's Insurance Fraud Regulation imposes civil and criminal penalties for fraudulent insurance acts, including misrepresentation on applications and filing false claims.",
             [("Civil and criminal penalties for fraudulent insurance acts including false applications and claims", True, "Correct. Pennsylvania's fraud regulation provides for both civil and criminal penalties."),
              ("Only a $500 fine for first-time offenders", False, "Pennsylvania insurance fraud penalties are far more significant than a $500 fine."),
              ("No penalties for insurance fraud — it is handled exclusively by federal law", False, "Pennsylvania has its own insurance fraud regulation with its own penalties."),
              ("Only civil penalties — insurance fraud is not a criminal matter in Pennsylvania", False, "Insurance fraud can be both a civil and criminal matter in Pennsylvania.")]),
            ("Under Pennsylvania's Insurance Department regulations, a producer who acts as a 'manager' is:",
             "multiple_choice", "standard",
             "Pennsylvania recognizes a manager designation for producers who manage insurance agencies or operations, with specific licensing requirements that differ from standard producer licensing.",
             [("A producer with specific licensing for managing an insurance agency or operation", True, "Correct. Pennsylvania recognizes managers as a distinct licensing category with specific requirements."),
              ("Any producer who manages their own book of business", False, "The manager designation is a specific license category, not just any producer who manages their own business."),
              ("An insurer employee who manages the claims department", False, "Manager licensing in Pennsylvania applies to agency management, not internal insurer operations."),
              ("Exempt from continuing education requirements", False, "Managers are subject to continuing education requirements like other licensees.")]),
        ],
        "RI": [
            ("In Rhode Island, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "Rhode Island uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. Rhode Island uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer Rhode Island insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer Rhode Island insurance exams."),
              ("The Rhode Island Insurance Division directly", False, "Rhode Island contracts with Pearson VUE for exam administration.")]),
            ("The Rhode Island Life and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The Rhode Island Life and Health Insurance Guaranty Association protects Rhode Island policyholders when a licensed Rhode Island life, health, or annuity insurer becomes insolvent.",
             [("Protects Rhode Island policyholders when a licensed insurer becomes insolvent", True, "Correct. The RI guaranty association covers claims from insolvent licensed insurers."),
              ("Provides subsidized insurance to low-income Rhode Island residents", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets rate caps for Rhode Island health insurance products", False, "Rate regulation is the Insurance Commissioner's function."),
              ("Covers claims from both admitted and non-admitted insurers", False, "Only licensed admitted insurer insolvencies are covered.")]),
            ("Rhode Island's AIDS/HIV testing rules in insurance require:",
             "multiple_choice", "standard",
             "Rhode Island has specific rules governing the use of HIV testing in insurance underwriting, including informed consent requirements and limitations on how test results may be used.",
             [("Informed consent before HIV testing and limitations on how results may be used in underwriting", True, "Correct. Rhode Island requires informed consent for HIV testing and restricts how results may be used."),
              ("All life insurance applicants over age 30 to be tested for HIV", False, "Rhode Island does not require universal HIV testing for all applicants."),
              ("Automatic denial of all coverage for HIV-positive applicants", False, "Automatic denial based on HIV status may be unfair discrimination; Rhode Island has specific rules."),
              ("HIV test results to be reported to the Rhode Island Insurance Division", False, "HIV test results are confidential; they are not reported to regulators.")]),
            ("In Rhode Island, annuity suitability requirements include:",
             "multiple_choice", "standard",
             "Rhode Island has adopted annuity suitability requirements including gathering client financial information before making annuity recommendations, consistent with NAIC model regulations.",
             [("Gathering the client's financial information before recommending an annuity", True, "Correct. Rhode Island requires producers to obtain client financial information to ensure annuity suitability."),
              ("Recommending only immediate annuities to clients over age 65", False, "Suitability requires matching products to individual needs, not defaulting to immediate annuities."),
              ("Obtaining the Insurance Commissioner's approval before each annuity sale", False, "Individual Commissioner approval is not required."),
              ("Limiting annuity recommendations to clients with pension income", False, "Suitability applies to all annuity recommendations regardless of income source.")]),
            ("Rhode Island's consumer privacy rules in insurance require:",
             "multiple_choice", "standard",
             "Rhode Island's insurance privacy rules require insurers and producers to protect consumer personal financial information and provide privacy notices, consistent with GLBA standards.",
             [("Protection of consumer personal financial information and provision of privacy notices", True, "Correct. Rhode Island requires protection of consumer information and privacy disclosures."),
              ("All consumer data to be shared with the Insurance Division annually", False, "Sharing consumer data with the Division is not a privacy regulation requirement."),
              ("Consumer consent before any insurance application information is collected", False, "Application information collection is standard practice; the privacy rules govern use and disclosure."),
              ("Deletion of all consumer records after 3 years", False, "Records must be retained for minimum periods; they cannot simply be deleted after 3 years.")]),
        ],
        "SC": [
            ("In South Carolina, the insurance licensing exam is administered by:",
             "multiple_choice", "standard",
             "South Carolina uses Pearson VUE to administer its insurance licensing examinations.",
             [("Pearson VUE at approved testing centers", True, "Correct. South Carolina uses Pearson VUE as its insurance examination provider."),
              ("Prometric at approved testing centers", False, "Prometric does not administer South Carolina insurance exams."),
              ("PSI Services at approved testing centers", False, "PSI does not administer South Carolina insurance exams."),
              ("The South Carolina Department of Insurance directly", False, "South Carolina contracts with Pearson VUE for exam administration.")]),
            ("The South Carolina Life and Accident and Health Insurance Guaranty Association:",
             "multiple_choice", "standard",
             "The South Carolina Life and Accident and Health Insurance Guaranty Association protects South Carolina policyholders when a licensed South Carolina life, health, or annuity insurer becomes insolvent.",
             [("Protects SC policyholders when a licensed SC insurer becomes insolvent", True, "Correct. The SC guaranty association covers claims from licensed insurer insolvencies."),
              ("Provides free life insurance to South Carolina veterans", False, "The guaranty association is an insolvency protection mechanism."),
              ("Sets premium rates for South Carolina life insurance products", False, "Rate regulation is the Director's function."),
              ("Only covers claims from companies domiciled in South Carolina", False, "The guaranty association covers claims from all licensed admitted insurers.")]),
            ("South Carolina's auto insurance laws include provisions for:",
             "multiple_choice", "standard",
             "South Carolina has specific auto insurance laws including an assigned risk plan for high-risk drivers and specific cancellation and non-renewal requirements.",
             [("An assigned risk plan for drivers unable to obtain coverage in the voluntary market", True, "Correct. South Carolina maintains an assigned risk plan for high-risk drivers unable to obtain standard market coverage."),
              ("A state-operated no-fault auto insurance system", False, "South Carolina is not a no-fault auto insurance state."),
              ("Mandatory comprehensive and collision coverage for all registered vehicles", False, "South Carolina requires liability insurance but not comprehensive or collision."),
              ("Free auto insurance for low-income South Carolina residents", False, "South Carolina's assigned risk plan provides coverage at standard rates; it is not free insurance.")]),
            ("Under South Carolina's Unfair Trade Practices Act, churning is:",
             "multiple_choice", "standard",
             "South Carolina's Unfair Trade Practices Act specifically prohibits churning — recommending policy replacements within the same company primarily to generate new commissions rather than benefit the client.",
             [("Prohibited as an unfair trade practice that may result in license discipline", True, "Correct. Churning is a prohibited unfair trade practice under South Carolina's law."),
              ("Permitted as long as the new policy has better terms than the old one", False, "Churning is prohibited regardless of the relative terms of the policies."),
              ("Only prohibited if it involves a policy increase of more than 10%", False, "There is no 10% threshold; churning is prohibited regardless of the premium difference."),
              ("Subject only to a written warning for a first offense", False, "Churning can result in license discipline, not just a written warning.")]),
            ("South Carolina's required provisions for life insurance policies include:",
             "multiple_choice", "standard",
             "South Carolina requires standard provisions in all life insurance policies including grace periods, free look periods, and non-forfeiture options to protect policyholders.",
             [("Grace period, free look period, and non-forfeiture options", True, "Correct. South Carolina requires these standard provisions in all life insurance policies."),
              ("A guaranteed dividend payment each policy year", False, "Dividends on participating policies are not guaranteed; guaranteeing them would be misrepresentation."),
              ("Automatic waiver of all premiums after age 65", False, "Automatic waiver of premiums after age 65 is not a required provision."),
              ("Coverage for all causes of death with no exclusions permitted", False, "South Carolina permits standard exclusions including the suicide exclusion in life insurance policies.")]),
        ],
    }
    return specifics.get(state_abbr, [
        (f"The insurance licensing exam in {state_abbr} tests candidates on:",
         "multiple_choice", "standard",
         "State insurance licensing exams test both national product knowledge and state-specific insurance laws.",
         [("Both national insurance concepts and state-specific laws and regulations", True, "Correct. All state exams have two portions: a national general knowledge section and a state law supplement."),
          ("Only national insurance concepts with no state-specific content", False, "All state exams include a state law supplement."),
          ("Only state laws with no national content", False, "All state exams include a national general knowledge portion."),
          ("Only mathematical calculations related to insurance pricing", False, "Insurance exams cover concepts, regulations, and policy provisions.")]),
    ] * 5)


STATES_PART3 = [
    ("NE", "Nebraska", "Director of Insurance",
     "Nebraska Life and Health Insurance Guaranty Association", 24),
    ("NV", "Nevada", "Commissioner of Insurance",
     "Nevada Life and Health Insurance Guaranty Association", 24),
    ("NH", "New Hampshire", "Insurance Commissioner",
     "New Hampshire Insurance Guaranty Fund", 24),
    ("NJ", "New Jersey", "Commissioner of Banking and Insurance",
     "New Jersey Life and Health Insurance Guaranty Association", 24),
    ("NM", "New Mexico", "Superintendent of Insurance",
     "New Mexico Life and Health Insurance Guaranty Association", 24),
    ("NY", "New York", "Superintendent of Financial Services",
     "New York Life and Health Insurance Guaranty Corporation", 24),
    ("NC", "North Carolina", "Commissioner of Insurance",
     "North Carolina Life and Health Insurance Guaranty Association", 24),
    ("ND", "North Dakota", "Insurance Commissioner",
     "North Dakota Life and Health Guaranty Association", 24),
    ("OH", "Ohio", "Director of Insurance",
     "Ohio Life and Health Insurance Guaranty Association", 24),
    ("OK", "Oklahoma", "Insurance Commissioner",
     "Oklahoma Insurance Guaranty Association", 24),
    ("OR", "Oregon", "Insurance Administrator",
     "Oregon Insurance Guaranty Association", 24),
    ("PA", "Pennsylvania", "Insurance Commissioner",
     "Pennsylvania Life and Health Insurance Guaranty Association", 24),
    ("RI", "Rhode Island", "Insurance Commissioner",
     "Rhode Island Life and Health Insurance Guaranty Association", 24),
    ("SC", "South Carolina", "Director of Insurance",
     "South Carolina Life and Accident and Health Insurance Guaranty Association", 24),
]

COURSES = [("pc", "P&C"), ("lh", "L&H")]


def seed():
    create_all()
    db = SessionLocal()
    try:
        total_mods = total_q = 0

        for (abbr, name, regulator, guaranty, ce_hours) in STATES_PART3:
            for (course_code, course_label) in COURSES:
                mod_slug = f"state-law-{abbr.lower()}-{course_code}"

                existing = db.scalar(
                    select(Module).where(Module.slug == mod_slug))
                if existing:
                    print(f"  SKIP (exists): {mod_slug}")
                    continue

                idx = STATES_PART3.index(
                    (abbr, name, regulator, guaranty, ce_hours))
                mod = Module(
                    slug=mod_slug,
                    title=f"{name} State Law — {course_label}",
                    description=(
                        f"State-specific insurance laws for the {name} "
                        f"{course_label} licensing exam. Covers the {regulator}, "
                        f"licensing, unfair trade practices, guaranty association, "
                        f"and state-specific rules."
                    ),
                    sort_order=760 + idx * 10 + (0 if course_code == "pc" else 1),
                    is_active=True,
                )
                db.add(mod)
                db.flush()
                db.execute(
                    text("UPDATE modules SET course=:c WHERE id=:id"),
                    {"c": course_code, "id": mod.id})
                total_mods += 1
                print(f"  MODULE: {mod.title}")

                all_questions = (
                    build_universal_questions(
                        name, regulator, guaranty, ce_hours, course_label) +
                    build_semi_universal(
                        name, regulator, guaranty, ce_hours, course_label) +
                    build_state_specific(abbr)
                )

                for (q_text, q_type, difficulty,
                     explanation, choices) in all_questions:
                    q = Question(
                        module_id=mod.id,
                        lesson_id=None,
                        question_text=q_text,
                        question_type=q_type,
                        difficulty=difficulty,
                        explanation=explanation,
                        is_active=True,
                    )
                    db.add(q)
                    db.flush()
                    for sort_i, (ct, correct, ce) in enumerate(choices, 1):
                        db.add(AnswerChoice(
                            question_id=q.id,
                            choice_text=ct,
                            is_correct=correct,
                            explanation=ce,
                            sort_order=sort_i,
                        ))
                    total_q += 1

        db.commit()
        print(f"\n=== Part 3 complete: {total_mods} modules, "
              f"{total_q} questions ===")
        print("States: NE NV NH NJ NM NY NC ND OH OK OR PA RI SC")

    finally:
        db.close()


if __name__ == "__main__":
    seed()
