const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
let me=null;let modules=[];let currentQuestions=[];let answers={};
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
async function api(path,opts={}){const res=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!res.ok){throw new Error(await res.text())}return res.json()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function boot(){const m=await api('/api/me');me=m.user;if(!me){return loginScreen()}modules=await api('/api/modules');route('dashboard')}
async function loginScreen(){const p=await api('/auth/providers');app.innerHTML=`<section class="login card"><div class="eyebrow">Free public access</div><h1>Sign in to save your progress</h1><p class="muted">Use Google, Microsoft, or Facebook. Local development can use the demo login.</p>${p.providers.map(x=>`<a class="provider" href="/auth/login/${x.id}"><button class="primary provider" ${x.configured?'':'disabled'}>Continue with ${esc(x.name)}${x.configured?'':' — not configured'}</button></a>`).join('')}${p.dev_login_enabled?'<a class="provider" href="/auth/dev-login"><button class="ghost provider">Development Login</button></a>':''}</section>`}
async function route(name,arg){try{if(!me)return loginScreen();if(name==='dashboard')return dashboard();if(name==='modules')return showModules();if(name==='module')return showModule(arg);if(name==='lesson')return showLesson(arg);if(name==='terms')return terms();if(name==='quiz')return quiz(arg)}catch(e){app.innerHTML=`<div class="card"><h2>Something went wrong</h2><p>${esc(e.message)}</p></div>`}}
async function dashboard(){const p=await api('/api/progress');app.innerHTML=`<section class="hero"><div class="card"><div class="eyebrow">Welcome, ${esc(me.name)}</div><h1>Study P&C insurance for free.</h1><p class="muted">This version saves progress to your signed-in account and serves course content from the database.</p><div class="toolbar"><button class="primary" onclick="route('modules')">Start Studying</button><button onclick="route('quiz')">Question Drill</button><button onclick="route('terms')">Glossary</button></div></div><div class="card"><div class="eyebrow">Progress</div><div class="stat">${p.percent_complete}%</div><div class="progress"><div class="bar" style="width:${p.percent_complete}%"></div></div><p>${p.completed_lessons}/${p.total_lessons} lessons complete</p><p class="muted">Mistake bank: ${p.mistake_count}</p></div></section><div class="grid" style="margin-top:1rem">${modules.map(m=>`<div class="card"><div class="eyebrow">${m.lesson_count} lessons</div><h2>${esc(m.title)}</h2><p class="muted">${esc(m.description)}</p><button onclick="route('module','${m.slug}')">Open</button><button onclick="route('quiz','${m.slug}')">Quiz</button></div>`).join('')}</div>`}
async function showModules(){app.innerHTML=`<div class="card"><h1>Modules</h1><div class="grid">${modules.map(m=>`<div class="card"><div class="eyebrow">${m.lesson_count} lessons</div><h2>${esc(m.title)}</h2><p class="muted">${esc(m.description)}</p><button onclick="route('module','${m.slug}')">Open Module</button></div>`).join('')}</div></div>`}
async function showModule(slug){const m=await api('/api/modules/'+slug);app.innerHTML=`<div class="card"><button onclick="route('modules')">← Modules</button><h1>${esc(m.title)}</h1><p class="muted">${esc(m.description)}</p><div class="list">${m.lessons.map(l=>`<div class="row"><div><strong>${esc(l.title)}</strong><br><span class="muted">${esc(l.summary)}</span></div><button onclick="route('lesson','${l.slug}')">Study</button></div>`).join('')}</div><div class="toolbar"><button onclick="route('quiz','${m.slug}')">Quiz This Module</button></div></div>`}
async function showLesson(slug){const l=await api('/api/lessons/'+slug);app.innerHTML=`<article class="lesson card"><button onclick="route('modules')">← Modules</button><h1>${esc(l.title)}</h1><p class="muted">${esc(l.summary)}</p><p>${esc(l.body)}</p>${l.example?`<h3>Example</h3><p>${esc(l.example)}</p>`:''}${l.memory_tip?`<h3>Memory tip</h3><p>${esc(l.memory_tip)}</p>`:''}<h3>Key terms</h3><p>${l.terms.map(t=>`<span class="term" title="${esc(t.plain_english_definition)}">${esc(t.term)}</span>`).join('')||'<span class="muted">No terms yet.</span>'}</p><label>Confidence</label><select id="confidence"><option value="1">Need review</option><option value="2">Getting it</option><option value="3">Strong</option></select><label>Notes</label><textarea id="notes" placeholder="Study notes..."></textarea><div class="toolbar"><button class="primary" onclick="saveProgress(${l.id})">Mark Complete</button><button onclick="speak('${esc((l.audio_script||l.body).replace(/`/g,''))}')">Listen</button></div></article>`}
async function saveProgress(id){await api('/api/lessons/'+id+'/progress',{method:'POST',body:JSON.stringify({completed:true,confidence:Number(document.getElementById('confidence').value),notes:document.getElementById('notes').value,saved_for_review:false})});toast('Progress saved')}
function speak(text){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(text))}
async function terms(){const rows=await api('/api/terms');app.innerHTML=`<div class="card"><h1>Glossary</h1><div class="list">${rows.map(t=>`<div class="card"><span class="pill">${esc(t.term)}</span><p><strong>Plain English:</strong> ${esc(t.plain_english_definition)}</p><p><strong>Exam:</strong> ${esc(t.exam_definition)}</p>${t.example?`<p class="muted"><strong>Example:</strong> ${esc(t.example)}</p>`:''}</div>`).join('')}</div></div>`}
async function quiz(moduleSlug){answers={};currentQuestions=await api('/api/questions?limit=10'+(moduleSlug?'&module_slug='+encodeURIComponent(moduleSlug):''));renderQuiz()}
function renderQuiz(results=null){app.innerHTML=`<div class="card"><h1>Question Drill</h1>${currentQuestions.map((q,i)=>`<div class="card"><div class="eyebrow">Question ${i+1}</div><h3>${esc(q.question_text)}</h3><div class="choices">${q.choices.map(c=>{let cls='choice';const r=results&&results.find(x=>x.question.id===q.id);if(answers[q.id]===c.id)cls+=' selected';if(r&&c.is_correct)cls+=' correct';if(r&&answers[q.id]===c.id&&!r.is_correct)cls+=' wrong';return `<div class="${cls}" onclick="answers[${q.id}]=${c.id};renderQuiz(${results?'lastResults':'null'})">${esc(c.choice_text)}</div>`}).join('')}</div>${results?`<p>${esc((results.find(x=>x.question.id===q.id)||{}).question?.explanation||'')}</p>`:''}</div>`).join('')}<div class="toolbar"><button class="primary" onclick="submitQuiz()">Submit</button><button onclick="quiz()">New Quiz</button></div></div>`}
let lastResults=null;
async function submitQuiz(){const out=await api('/api/quiz/submit',{method:'POST',body:JSON.stringify({mode:'practice',answers})});lastResults=out.results;renderQuiz(lastResults);toast('Score: '+out.score+'%')}
async function logout(){await api('/auth/logout',{method:'POST'});location.reload()}
boot();