const app=document.getElementById('app');
const toastEl=document.getElementById('toast');
let me=null, modules=[], chat=[], activeModuleSlug='';
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');setTimeout(()=>toastEl.classList.remove('show'),2200)}
async function api(path,opts={}){const r=await fetch(path,{headers:{'Content-Type':'application/json'},...opts});if(!r.ok)throw new Error(await r.text());return r.json()}
function esc(s=''){return String(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
async function boot(){const m=await api('/api/me');me=m.user;if(!me)return login();modules=await api('/api/modules');activeModuleSlug=modules[0]?.slug||'';workspace()}
async function login(){const p=await api('/auth/providers');app.innerHTML=`<section class="login card"><h1>P&C License Prep Academy</h1><p class="muted">Sign in to save your progress.</p>${p.providers.map(x=>`<a class="provider" href="/auth/login/${x.id}"><button class="primary provider" ${x.configured?'':'disabled'}>Continue with ${esc(x.name)}${x.configured?'':' — not configured'}</button></a>`).join('')}${p.dev_login_enabled?'<a class="provider" href="/auth/dev-login"><button class="ghost provider">Development Login</button></a>':''}</section>`}
function sources(){return `<aside class="pane"><div class="pane-head"><h2>Sources</h2><button class="icon-btn">▣</button></div><div class="pane-body"><button class="ghost add-source" onclick="showModules()">＋ Add sources</button><div class="source-search"><input placeholder="Search course sources"><div class="source-actions"><button>General P&C</button><button>Fast Study</button><button class="icon-btn search-btn">⌕</button></div></div><div class="empty-state"><div><div class="big">▧</div><strong>Saved sources will appear here</strong><p>Use Add sources to open built-in P&C modules, lessons, terms, and question banks.</p></div></div></div></aside>`}
function chatPane(){const intro=`<div class="message assistant intro"><p>Welcome to <strong>P&C License Prep Academy</strong>.</p><p>I am <strong>Coverage Coach</strong>, your study tutor. Ask me to explain a concept, quiz you, review weak areas, or create a study guide.</p><p>Use the <strong>Sources</strong> panel for course modules and the <strong>Studio</strong> panel for quiz, flashcards, reports, and study tools.</p></div>`;return `<section class="pane center"><div class="pane-head"><h2>Chat</h2><div><span id="coachDot" class="ollama-dot"></span><button class="icon-btn">⋮</button></div></div><div class="pane-body chat-body"><div class="messages" id="messages">${intro}${chat.map(m=>`<div class="message ${m.role}">${esc(m.text)}</div>`).join('')}</div><div class="suggestions"><button onclick="askQuick('What is the difference between a peril and a hazard?')">What is the difference between a peril and a hazard?</button><button onclick="askQuick('Quiz me on homeowners coverages A through F.')">Quiz me on homeowners coverages</button><button onclick="askQuick('Explain CGL Coverage A, B, and C.')">How do CGL Coverage A, B, and C differ?</button></div><div class="composer"><textarea id="q" placeholder="Ask a question or create something"></textarea><span class="composer-meta">0 sources</span><button class="send-btn" onclick="ask()">➜</button></div></div></section>`}
function studio(){return `<aside class="pane"><div class="pane-head"><h2>Studio</h2><button class="icon-btn">▣</button></div><div class="pane-body"><div class="studio-grid"><button class="studio-tile tile-audio" onclick="studioAction('study_guide')"><span>▥<br>Audio Overview</span><b>›</b></button><button class="studio-tile tile-deck" onclick="studioAction('study_guide')"><span>▤<br>Slide Deck</span><b>›</b></button><button class="studio-tile tile-video" onclick="studioAction('study_guide')"><span>▣<br>Video Overview</span><b>›</b></button><button class="studio-tile tile-map" onclick="studioAction('concept_map')"><span>⌘<br>Mind Map</span><b>›</b></button><button class="studio-tile tile-report" onclick="studioAction('study_guide')"><span>⇱<br>Reports</span><b>›</b></button><button class="studio-tile tile-flash" onclick="showTerms()"><span>▧<br>Flashcards</span><b>›</b></button><button class="studio-tile tile-quiz" onclick="studioAction('practice_quiz')"><span>▢<br>Quiz</span><b>›</b></button><button class="studio-tile tile-info" onclick="studioAction('concept_map')"><span>▥<br>Infographic</span><b>›</b></button><button class="studio-tile tile-data" onclick="studioAction('cram_sheet')"><span>▦<br>Data Table</span><b>›</b></button></div><div class="studio-output" id="studioOutput"><div><div class="spark">✦</div><strong>Studio output will be saved here.</strong><p>After adding sources, click to add Audio Overview, Study Guide, Mind Map, and more.</p><button class="primary" onclick="studioAction('study_guide')">Add note</button></div></div></div></aside>`}
function workspace(){app.innerHTML=`<div class="workspace">${sources()}${chatPane()}${studio()}</div>`;checkStatus();setTimeout(()=>{let el=document.getElementById('messages');if(el)el.scrollTop=el.scrollHeight},50)}
async function checkStatus(){try{const h=await api('/api/coach/health');const d=document.getElementById('coachDot');if(d)d.className='ollama-dot '+(h.ollama&&h.ollama.online?'online':'offline')}catch(e){}}
function askQuick(t){let q=document.getElementById('q');if(q){q.value=t;ask()}else{chat.push({role:'user',text:t});workspace();askText(t)}}
async function ask(){const q=document.getElementById('q');const t=(q?.value||'').trim();if(!t)return toast('Ask a question first');q.value='';await askText(t)}
async function askText(t){chat.push({role:'user',text:t});workspace();chat.push({role:'assistant',text:'Coverage Coach is thinking...'});workspace();const out=await api('/api/tutor/ask',{method:'POST',body:JSON.stringify({message:t})});chat.pop();chat.push({role:'assistant',text:out.answer});workspace()}
function renderStudio(data){if(data.terms){return `<div class="studio-doc"><div class="studio-doc-header"><span class="studio-tag">Cram Sheet</span><span>${esc(data.module||'')}</span></div><table class="cram-table"><tbody>${data.terms.map(t=>`<tr><td>${esc(t.term)}</td><td>${esc(t.exam_definition||'')}<br><small>${esc(t.example||'')}</small></td></tr>`).join('')}</tbody></table></div>`}if(data.questions){return `<div class="studio-doc"><div class="studio-doc-header"><span class="studio-tag">Practice Quiz</span><span>${esc(data.module||'')}</span></div>${data.questions.map((q,i)=>`<div class="quiz-card"><strong>${i+1}. ${esc(q.q||q.question||'Question')}</strong><ol>${(q.choices||[]).map(c=>`<li>${esc(c)}</li>`).join('')}</ol><p class="muted">${esc(q.explanation||'')}</p></div>`).join('')}</div>`}return `<div class="studio-doc"><div class="studio-doc-header"><span class="studio-tag">Studio</span><span>${esc(data.module||'')}</span></div><p style="white-space:pre-wrap">${esc(data.content||data.error||JSON.stringify(data,null,2))}</p></div>`}
async function studioAction(action){let out=document.getElementById('studioOutput');if(!out)return;out.innerHTML='<div><div class="spark">✦</div><strong>Generating...</strong><p>This may take a moment.</p></div>';try{const data=await api('/api/studio/generate',{method:'POST',body:JSON.stringify({action,module_slug:activeModuleSlug})});out.innerHTML=renderStudio(data)}catch(e){out.innerHTML=`<div><div class="spark">✦</div><strong>Studio fallback</strong><p>${esc(e.message)}</p></div>`}}
async function showModules(){app.innerHTML=`<div class="page-wrap"><div class="card"><button onclick="workspace()">← Workspace</button><h1>Course Sources</h1><div class="grid">${modules.map(m=>`<div class="card"><h2>${esc(m.title)}</h2><p>${esc(m.description)}</p><button onclick="openModule('${m.slug}')">Open</button></div>`).join('')}</div></div></div>`}
async function openModule(slug){activeModuleSlug=slug;const m=await api('/api/modules/'+slug);app.innerHTML=`<div class="page-wrap"><div class="card"><button onclick="workspace()">← Workspace</button><h1>${esc(m.title)}</h1>${m.lessons.map(l=>`<div class="row"><div><strong>${esc(l.title)}</strong><br><span class="muted">${esc(l.summary)}</span></div><button onclick="openLesson('${l.slug}')">Study</button></div>`).join('')}</div></div>`}
async function openLesson(slug){const l=await api('/api/lessons/'+slug);app.innerHTML=`<div class="page-wrap"><article class="lesson card"><button onclick="workspace()">← Workspace</button><h1>${esc(l.title)}</h1><p>${esc(l.body)}</p><p>${(l.terms||[]).map(t=>`<span class="term">${esc(t.term)}</span>`).join('')}</p><button class="primary" onclick="api('/api/lessons/${l.id}/progress',{method:'POST',body:JSON.stringify({completed:true,confidence:2,notes:'',saved_for_review:false})}).then(()=>toast('Progress saved'))">Mark Complete</button></article></div>`}
async function showTerms(){const rows=await api('/api/terms');app.innerHTML=`<div class="page-wrap"><div class="card"><button onclick="workspace()">← Workspace</button><h1>Flashcards</h1>${rows.map(t=>`<div class="card"><span class="pill">${esc(t.term)}</span><p>${esc(t.exam_definition||t.plain_english_definition)}</p></div>`).join('')}</div></div>`}
async function showQuiz(){const qs=await api('/api/questions?limit=10');app.innerHTML=`<div class="page-wrap"><div class="card"><button onclick="workspace()">← Workspace</button><h1>Quiz</h1>${qs.map(q=>`<div class="card"><h3>${esc(q.question_text)}</h3>${q.choices.map(c=>`<div class="choice">${esc(c.choice_text)}</div>`).join('')}</div>`).join('')}</div></div>`}
async function logout(){await api('/auth/logout',{method:'POST'});location.reload()}
boot();
