from __future__ import annotations

# Expanded general Property & Casualty study content.
# State-neutral and designed for a free public licensing prep platform.
#
# Shape generated at import:
# DEFAULT_COURSE = {"modules": [{slug,title,description,sort_order,lessons,terms,questions}]}

RAW_MODULES = [('insurance-basics',
  'Insurance Basics',
  'Core language and concepts every P&C candidate needs first.',
  [('what-is-insurance',
    'What Is Insurance?',
    'Insurance transfers financial risk from an insured to an insurer. The insured pays premium and the insurer pays covered losses according to the policy. The goal is indemnity: restoring the insured financially after a covered loss.'),
   ('risk-peril-hazard',
    'Risk, Peril, and Hazard',
    'Risk is the chance of loss. A peril is the cause of loss, such as fire or theft. A hazard is a condition that increases the chance or severity of loss, such as faulty wiring.')],
  [('Risk',
    'The chance that a loss could happen.',
    'The uncertainty or possibility of financial loss.',
    'A home could burn or a car could crash.'),
   ('Peril',
    'The cause of loss.',
    'A cause of loss such as fire, theft, wind, hail, or collision.',
    'Lightning damages a home; lightning is the peril.'),
   ('Hazard',
    'Something that makes loss more likely or severe.',
    'A condition that increases the chance, frequency, or severity of loss.',
    'Faulty wiring increases the chance of fire.')]),
 ('insurance-contracts',
  'Insurance Contracts',
  'How insurance policies are structured and interpreted.',
  [('policy-sections',
    'Main Policy Sections',
    'Policies usually include declarations, definitions, insuring agreement, conditions, exclusions, and endorsements. Declarations summarize. The insuring agreement promises. Conditions set rules. Exclusions remove coverage. Endorsements change the policy.'),
   ('contract-characteristics',
    'Contract Characteristics',
    'Insurance contracts are usually adhesion, aleatory, conditional, unilateral, and personal contracts. These characteristics are commonly tested on licensing exams.')],
  [('Declarations',
    'The policy snapshot page.',
    'The section that lists the insured, policy period, limits, premium, and covered property or exposures.',
    'A declarations page lists a dwelling limit.'),
   ('Exclusion',
    'Something the policy does not cover.',
    'Policy language that removes coverage for certain causes, property, people, or situations.',
    'A flood exclusion removes flood coverage.'),
   ('Endorsement',
    'A form that changes the policy.',
    'A written form attached to a policy that adds, removes, or modifies coverage.',
    'A jewelry endorsement schedules a ring.')]),
 ('property-fundamentals',
  'Property Insurance Fundamentals',
  'First-party property concepts and valuation.',
  [('direct-vs-indirect-loss',
    'Direct vs Indirect Loss',
    'A direct loss is physical damage to covered property. An indirect loss is a financial result of direct damage, such as loss of use, fair rental value, or business income.'),
   ('replacement-cost-vs-acv',
    'Replacement Cost vs Actual Cash Value',
    'Replacement cost pays the cost to replace with like kind and quality without depreciation, subject to terms. Actual cash value is commonly replacement cost minus depreciation.')],
  [('Direct Loss',
    'Physical damage to property.',
    'Physical damage to covered property caused by a covered peril.',
    'Fire damages a kitchen wall.'),
   ('Indirect Loss',
    'A financial loss resulting from direct damage.',
    'A consequential financial loss caused by direct physical damage.',
    'Hotel costs after a covered house fire.'),
   ('Actual Cash Value',
    'Replacement cost minus depreciation.',
    'A valuation method commonly calculated as replacement cost less depreciation.',
    'A ten-year-old roof is valued with depreciation.')]),
 ('casualty-fundamentals',
  'Casualty Insurance Fundamentals',
  'Liability, negligence, damages, and third-party claims.',
  [('liability-basics',
    'Liability Basics',
    'Liability coverage is third-party coverage. It may pay damages an insured is legally responsible for and may provide defense for covered claims.'),
   ('negligence',
    'Negligence',
    'Negligence is failure to use reasonable care. A claimant generally must show duty, breach of duty, damages, and a connection between the breach and damages.')],
  [('Bodily Injury',
    'Physical injury to a person.',
    'Physical injury, sickness, disease, or death.',
    'A customer breaks an arm in a fall.'),
   ('Property Damage',
    'Damage to tangible property.',
    'Physical injury to tangible property or loss of use of tangible property.',
    'A contractor damages a customer fence.'),
   ('Negligence',
    'Failure to use reasonable care.',
    'Failure to act as a reasonable person would under similar circumstances.',
    'A driver runs a red light.')]),
 ('personal-auto',
  'Personal Auto Insurance',
  'Core personal auto coverages and distinctions.',
  [('auto-liability',
    'Auto Liability',
    'Auto liability pays others for bodily injury or property damage the insured is legally responsible for because of an auto accident.'),
   ('collision-and-other-than-collision',
    'Collision and Other Than Collision',
    'Collision covers upset or impact with another object. Other than collision, often called comprehensive, covers many non-collision losses such as theft, fire, hail, vandalism, or contact with an animal.')],
  [('Liability Coverage',
    'Coverage for injury or damage caused to others.',
    'Third-party coverage for bodily injury or property damage for which the insured is legally responsible.',
    'The insured damages another driver car.'),
   ('Collision',
    'Upset or impact with another object.',
    'Physical damage coverage for collision with another vehicle or object or vehicle upset.',
    'The insured hits a pole.'),
   ('Other Than Collision',
    'Many non-collision vehicle losses.',
    'Physical damage coverage for losses such as theft, fire, hail, or contact with an animal.',
    'A deer strikes the covered auto.')]),
 ('homeowners',
  'Homeowners Insurance',
  'Homeowners property and liability coverage parts.',
  [('homeowners-coverage-parts',
    'Homeowners Coverage Parts',
    'Homeowners policies commonly include Coverage A dwelling, Coverage B other structures, Coverage C personal property, Coverage D loss of use, Coverage E personal liability, and Coverage F medical payments to others.'),
   ('homeowners-liability',
    'Homeowners Liability',
    'Coverage E personal liability may cover damages for bodily injury or property damage for which an insured is legally responsible. Coverage F medical payments can pay small medical expenses regardless of fault.')],
  [('Coverage A',
    'Dwelling coverage.',
    'Coverage for the residence dwelling and attached structures.',
    'The main house is Coverage A.'),
   ('Coverage B',
    'Other structures coverage.',
    'Coverage for detached structures on the residence premises.',
    'A detached garage is Coverage B.'),
   ('Coverage C',
    'Personal property coverage.',
    'Coverage for personal belongings owned or used by an insured.',
    'Furniture and clothing are Coverage C.')]),
 ('dwelling-policies',
  'Dwelling Policies',
  'DP forms and rental-property property coverage.',
  [('dwelling-policy-purpose',
    'Purpose of Dwelling Policies',
    'Dwelling policies are often used for rental, seasonal, vacant, or older dwellings. They are primarily property policies and do not automatically provide the same package as homeowners insurance.'),
   ('dp-forms',
    'DP-1, DP-2, and DP-3',
    'DP-1 is basic, DP-2 is broad, and DP-3 is special. DP-3 generally provides open perils for the dwelling and named perils for personal property, subject to policy terms.')],
  [('DP-1',
    'Basic dwelling form.',
    'A dwelling form generally covering basic named perils.',
    'Fire may be a basic peril.'),
   ('DP-2',
    'Broad dwelling form.',
    'A dwelling form that adds broader named perils.',
    'Falling objects may be included on broad forms.'),
   ('DP-3',
    'Special dwelling form.',
    'A dwelling form that generally provides open perils on the dwelling.',
    'A landlord chooses DP-3 for broader dwelling protection.')]),
 ('commercial-property',
  'Commercial Property Insurance',
  'Business property, income, causes of loss, and valuation.',
  [('building-and-business-personal-property',
    'Building and Business Personal Property',
    'Commercial property may cover the building, business personal property, and property of others in the insured care, custody, or control.'),
   ('business-income-extra-expense',
    'Business Income and Extra Expense',
    'Business income can replace lost income when operations are suspended due to covered property damage. Extra expense can pay extra costs to continue operations or reduce the shutdown.')],
  [('Business Personal Property',
    'Business-owned movable property.',
    'Property such as furniture, fixtures, equipment, inventory, and supplies.',
    'A store shelves and inventory.'),
   ('Business Income',
    'Lost income after covered damage.',
    'Coverage for income loss due to necessary suspension of operations caused by covered property damage.',
    'A closed bakery loses income after a fire.'),
   ('Extra Expense',
    'Extra costs to reduce a shutdown.',
    'Coverage for additional costs to continue operations after covered property damage.',
    'Renting temporary office space.')]),
 ('commercial-general-liability',
  'Commercial General Liability',
  'CGL coverage parts, limits, and aggregates.',
  [('cgl-coverage-a',
    'CGL Coverage A',
    'Coverage A addresses bodily injury and property damage liability caused by an occurrence, subject to exclusions and conditions.'),
   ('cgl-coverage-b-c',
    'CGL Coverage B and C',
    'Coverage B handles personal and advertising injury. Coverage C provides medical payments for certain injuries regardless of legal liability, subject to limits and exclusions.')],
  [('Coverage A',
    'BI and PD liability.',
    'CGL bodily injury and property damage liability coverage.',
    'A customer injury claim.'),
   ('Coverage B',
    'Personal and advertising injury.',
    'CGL coverage for listed offenses such as libel, slander, and certain advertising injury.',
    'A covered advertising injury allegation.'),
   ('Coverage C',
    'Medical payments.',
    'CGL coverage for certain medical expenses regardless of legal liability.',
    'A visitor minor medical bill.')]),
 ('business-auto',
  'Business Auto Insurance',
  'Commercial auto symbols, liability, and physical damage.',
  [('covered-auto-symbols',
    'Covered Auto Symbols',
    'Business auto policies use numerical symbols to define which autos are covered for each coverage. The symbol matters because not every auto is covered for every coverage.'),
   ('hired-and-nonowned-auto',
    'Hired and Non-Owned Auto',
    'Hired autos are leased, hired, rented, or borrowed. Non-owned autos are not owned, hired, or borrowed by the business but are used in the business, such as employee-owned vehicles.')],
  [('Covered Auto Symbol',
    'A code showing which autos are covered.',
    'A numerical symbol in the business auto policy defining covered autos.',
    'Symbol 7 generally means specifically described autos.'),
   ('Hired Auto',
    'A rented or borrowed vehicle.',
    'An auto the business leases, hires, rents, or borrows.',
    'A rental truck used for business.'),
   ('Non-Owned Auto',
    'Someone else auto used for business.',
    'An auto the business does not own, lease, hire, rent, or borrow but uses in business.',
    'An employee car used for a work errand.')]),
 ('workers-compensation',
  'Workers Compensation and Employers Liability',
  'General workers compensation concepts.',
  [('workers-comp-purpose',
    'Purpose of Workers Compensation',
    'Workers compensation generally provides medical, disability, rehabilitation, and death benefits for employees injured in the course and scope of employment. It is generally no-fault.'),
   ('employers-liability',
    'Employers Liability',
    'Employers liability is Part Two of a standard workers compensation policy. It may respond to certain employer liability claims outside the workers compensation benefit structure.')],
  [('Workers Compensation',
    'Benefits for work-related injury or disease.',
    'Statutory benefits for employees injured or made ill in the course of employment.',
    'A warehouse worker injures a back while lifting boxes.'),
   ('Exclusive Remedy',
    'WC is usually the worker sole remedy.',
    'A principle that generally prevents employees from suing employers for covered work injuries.',
    'The worker receives WC benefits instead of suing.'),
   ('Employers Liability',
    'Coverage for certain employer liability claims.',
    'Part Two of a workers compensation policy covering certain claims by employees or related parties.',
    'A third-party-over action may involve employers liability.')]),
 ('crime-bonds-specialty',
  'Crime, Bonds, and Specialty Coverages',
  'Specialty coverages often tested on general P&C exams.',
  [('crime-coverages',
    'Crime Coverages',
    'Commercial crime coverage can address employee theft, forgery, alteration, theft of money and securities, robbery, burglary, and computer fraud depending on forms selected.'),
   ('surety-vs-insurance',
    'Surety Bonds vs Insurance',
    'A surety bond involves three parties: the principal, obligee, and surety. The surety guarantees performance or payment and expects reimbursement from the principal if it pays.')],
  [('Employee Theft',
    'Dishonest taking by an employee.',
    'Crime coverage for theft by an employee.',
    'An employee steals deposit money.'),
   ('Forgery',
    'False signing or altering of documents.',
    'Crime coverage for loss from forged or altered financial instruments.',
    'A forged company check.'),
   ('Surety Bond',
    'A three-party guarantee.',
    'A bond involving principal, obligee, and surety.',
    'A contractor performance bond.')]),
 ('ethics-producer-responsibilities',
  'Ethics and Producer Responsibilities',
  'General ethical conduct and producer duties.',
  [('producer-authority',
    'Producer Authority',
    'Producer authority may be express, implied, or apparent. Producers must understand what they are authorized to do and avoid promises beyond their authority.'),
   ('unfair-trade-practices',
    'Unfair Trade Practices',
    'Common unfair practices include misrepresentation, twisting, rebating where prohibited, false advertising, unfair discrimination, and defamation.')],
  [('Misrepresentation',
    'A false or misleading statement.',
    'Giving incorrect or misleading information about a policy or insurer.',
    'Saying a policy covers flood when it does not.'),
   ('Twisting',
    'Improper replacement through deception.',
    'Using misrepresentation to induce a policyholder to replace existing insurance.',
    'Lying about an old policy to sell a new one.'),
   ('Fiduciary Duty',
    'Duty to handle money responsibly.',
    'A duty to act with trust and care when handling premiums or client funds.',
    'Remitting collected premium properly.')]),
 ('exam-prep',
  'Exam Prep and Final Review',
  'How to approach exam-style P&C questions.',
  [('reading-exam-questions',
    'Reading Exam Questions',
    'Exam questions often include qualifiers such as except, not, always, never, first, best, and most likely. Read the stem carefully before choosing an answer.'),
   ('building-a-study-plan',
    'Building a Study Plan',
    'A good study plan starts with basics, then property and casualty fundamentals, then personal and commercial lines, and finally ethics and exam strategy. Review missed questions by topic.')],
  [('Keyword',
    'A clue word in the question.',
    'Words like except, not, first, always, and best that change what the question asks.',
    'Which loss is not covered?'),
   ('Best Answer',
    'The most correct choice for the question asked.',
    'The answer that best fits the specific question, even if other choices sound partly true.',
    'Choosing Coverage B for a detached garage.'),
   ('Weak Area',
    'A topic that needs more review.',
    'A subject where the candidate misses questions repeatedly.',
    'Coinsurance may become a weak area.')])]


def _build_course() -> dict:
    course = {"modules": []}
    for idx, (slug, title, description, lessons, terms) in enumerate(RAW_MODULES, start=1):
        module = {
            "slug": slug,
            "title": title,
            "description": description,
            "sort_order": idx,
            "lessons": [],
            "terms": [],
            "questions": [],
        }

        for lesson_idx, (lesson_slug, lesson_title, body) in enumerate(lessons, start=1):
            first_sentence = body.split(".")[0] + "."
            module["lessons"].append({
                "slug": lesson_slug,
                "title": lesson_title,
                "summary": first_sentence,
                "body": body,
                "example": f"Example: This topic may appear in a scenario asking the candidate to identify {lesson_title.lower()} in a real insurance situation.",
                "memory_tip": f"Remember: {lesson_title} is tested by looking for the key fact in the question.",
                "audio_script": f"{lesson_title}. {body}",
                "estimated_minutes": 7,
                "sort_order": lesson_idx,
            })

        for term, plain, exam, example in terms:
            module["terms"].append({
                "term": term,
                "plain_english_definition": plain,
                "exam_definition": exam,
                "example": example,
            })

        first_term = terms[0]
        last_term = terms[-1]
        module["questions"].append({
            "lesson_slug": lessons[0][0],
            "question_text": f"Which statement best describes {first_term[0]}?",
            "question_type": "multiple_choice",
            "difficulty": "standard",
            "explanation": first_term[2],
            "choices": [
                {"choice_text": first_term[1], "is_correct": True, "explanation": "Correct. This matches the term being tested.", "sort_order": 1},
                {"choice_text": "A policy provision that automatically covers every possible loss.", "is_correct": False, "explanation": "No policy covers every possible loss.", "sort_order": 2},
                {"choice_text": "A state-specific licensing appointment requirement.", "is_correct": False, "explanation": "This is not a state appointment issue.", "sort_order": 3},
                {"choice_text": "A type of life insurance settlement option.", "is_correct": False, "explanation": "This is not a life insurance settlement option.", "sort_order": 4},
            ],
        })
        module["questions"].append({
            "lesson_slug": lessons[-1][0],
            "question_text": f"In the lesson '{lessons[-1][1]}', what should the candidate focus on?",
            "question_type": "multiple_choice",
            "difficulty": "beginner",
            "explanation": lessons[-1][2],
            "choices": [
                {"choice_text": lessons[-1][2].split(".")[0] + ".", "is_correct": True, "explanation": "Correct. This is the central point of the lesson.", "sort_order": 1},
                {"choice_text": "Assume coverage applies because the insured expected it.", "is_correct": False, "explanation": "Coverage depends on policy terms, conditions, and exclusions.", "sort_order": 2},
                {"choice_text": "Ignore definitions because they rarely matter.", "is_correct": False, "explanation": "Definitions are frequently tested.", "sort_order": 3},
                {"choice_text": "Only study state law in the general section.", "is_correct": False, "explanation": "This general course is state-neutral.", "sort_order": 4},
            ],
        })
        module["questions"].append({
            "lesson_slug": lessons[0][0],
            "question_text": f"A question describes: {last_term[3]} Which term is most closely related?",
            "question_type": "scenario",
            "difficulty": "standard",
            "explanation": last_term[2],
            "choices": [
                {"choice_text": last_term[0], "is_correct": True, "explanation": "Correct. The scenario matches this term.", "sort_order": 1},
                {"choice_text": "A premium audit", "is_correct": False, "explanation": "The scenario does not involve auditing premium.", "sort_order": 2},
                {"choice_text": "A cancellation notice", "is_correct": False, "explanation": "The scenario does not involve cancellation.", "sort_order": 3},
                {"choice_text": "A policy dividend", "is_correct": False, "explanation": "The scenario does not involve dividends.", "sort_order": 4},
            ],
        })

        course["modules"].append(module)
    return course


DEFAULT_COURSE = _build_course()
